CONTRIBUTING.md
README.md

Initial readme and contributing docs

---

CONTRIBUTING.md

Use the Google naming convention.

---

tools/format.sh

Uses clang-format, cmake-format, and buildifier.

Add tools/format.sh which formats all files automatically.

---

docs/requirements.md

Start documenting requirements.

---

.circleci/config.yml
ci/Dockerfile
ci/install_gcc48.sh

gcc-4.8 is the oldest compiler we've discussed supporting for the API.

Test gcc-4.8 as part of CI

---

CMakeLists.txt
api/include/opentelemetry/nostd/span.h
api/include/opentelemetry/nostd/utility.h
api/test/nostd/BUILD
api/test/nostd/CMakeLists.txt
api/test/nostd/span_test.cc
api/test/nostd/utility_test.cc

Like std::string_view this is another basic non-owning vocabulary type.

Add back port of std::span

---

api/include/opentelemetry/nostd/unique_ptr.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/span.h
api/include/opentelemetry/trace/tracer.h
api/test/CMakeLists.txt
api/test/nostd/BUILD
api/test/nostd/CMakeLists.txt
api/test/nostd/unique_ptr_test.cc
api/test/trace/BUILD
api/test/trace/CMakeLists.txt
api/test/trace/noop_test.cc

Other methods and options will need to be filled in by later PRs.

Add a minimal Tracer and Span API

---

ci/install_format_tools.sh
tools/format.sh

This downloads a pre-compiled version (2.2.1) of the Bazel buildifier. This fixes the currently broken `format` CI rule and should prevent future regressions.
The `format` CI rule currently fails with a message that `strings.ReplaceAll` is missing. This was added in Go 1.12, but Ubuntu 18 by default comes with Go 1.10.

Use newest available Go version in CI container

---

bazel/BUILD
sdk/src/CMakeLists.txt
sdk/src/common/BUILD
sdk/src/common/CMakeLists.txt
sdk/src/common/fast_random_number_generator.h
sdk/src/common/platform/BUILD
sdk/src/common/platform/fork.h
sdk/src/common/platform/fork_unix.cc
sdk/src/common/platform/fork_windows.cc
sdk/src/common/random.cc
sdk/src/common/random.h
sdk/test/CMakeLists.txt
sdk/test/common/BUILD
sdk/test/common/CMakeLists.txt
sdk/test/common/fast_random_number_generator_test.cc
sdk/test/common/random_benchmark.cc
sdk/test/common/random_fork_test.cc
sdk/test/common/random_test.cc

The implementation uses thread-local random number generators and sets up a fork handler so that we can continue to generate unique IDs when the process is forked.

Add utility for generating random 64-bit numbers

---

docs/abi-policy.md

This should conclude the discussions around [vendor stability for SDK vendor hooks](https://github.com/open-telemetry/opentelemetry-cpp/issues/43).

Clarify ABI requirements for the SDK vendor hooks

---

sdk/include/opentelemetry/sdk/common/atomic_shared_ptr.h

This fixes a memory leak for the gcc 4.8 version of `AtomicSharedPtr`.

Fix memory leak

---

api/include/opentelemetry/trace/span_id.h
api/include/opentelemetry/trace/trace_id.h
api/test/trace/span_id_test.cc
api/test/trace/trace_id_test.cc

For trace and span ids, the lowercase base 16 representation should be preferred, as the [W3C TraceContext spec](https://www.w3.org/TR/trace-context/#traceparent-header-field-values) relies on hex digits in ids to be all lowercase.
The documentation of `ToLowerCase16` mentioned a lowercase representation, but the function returned an uppercase representation.

Use lowercase base 16 representation of ids

---

api/include/opentelemetry/core/timestamp.h
api/include/opentelemetry/plugin/tracer.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/span.h
api/test/core/timestamp_test.cc
examples/plugin/plugin/tracer.cc
sdk/src/trace/span.cc
sdk/test/trace/tracer_test.cc

This adds SDK support for setting start and end timestamps on spans.
1. The API is extended to allow for specifying end timestamps manually.
2. Comparison operators to `SystemTimestamp` and `SteadyTimestamp` are added.
3. The `Span` implementation in the SDK is updated to use given timestamps or calculate timestamps based on the current time.

Set span start and end timestamps

---

.github/workflows/ci.yml
CMakeLists.txt
ci/README.md
ci/do_ci.sh
ci/setup_cmake.sh
sdk/include/opentelemetry/sdk/common/atomic_shared_ptr.h
sdk/test/common/random_test.cc

This is a fix for #105. Our code was relying on a [template specialization of `std::atomic` for `std::shared_ptr<T>`](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2), which isn't provided by `g++`.
Instead we now rely on specializations of `std::atomic_store` and `std::atomic_load` for everything except gcc 4.8.
To guard against similar issues in future, I added a C++20 test to the shiny new GHA CI.

Fix AtomicSharedPtr for C++20

---

.github/CODEOWNERS
README.md

Per request from @jmacd.
@jmacd was in the original team to kick off this project, now we've started to make steady progress.

Remove Josh from the approvers

---

CMakeLists.txt
api/include/opentelemetry/nostd/function_ref.h

Fix for #104 : when OpenTelemetry is compiled with latest update of Visual Studio 2019 in C++17 mode - it'd generate a warning, and in C++20 it won't compile because std::result_of has been removed in C++20. Adjust the header to stop using a compiler feature that's been removed from standard.

std::result_of removed in C++20

---

sdk/include/opentelemetry/sdk/trace/sampler.h

This PR fixes two mistakes in the Sampling API `SamplingResult` struct:
- There is a typo making the sampler unable to compile.
- The attribute should be a `unique_ptr<const map>` to be immutable, according to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shouldsample)

SamplingResult attributes fix

---

exporters/otlp/recordable.cc
exporters/otlp/recordable_test.cc
ext/src/zpages/README.md
third_party/opentelemetry-proto/README
third_party/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service_http.yaml
third_party/opentelemetry-proto/opentelemetry/proto/common/v1/common.proto
third_party/opentelemetry-proto/opentelemetry/proto/metrics/v1/metrics.proto
third_party/opentelemetry-proto/opentelemetry/proto/resource/v1/resource.proto
third_party/opentelemetry-proto/opentelemetry/proto/trace/v1/trace.proto

Our vendored version of `opentelemetry-proto` is out of date with https://github.com/open-telemetry/opentelemetry-proto. This PR updates it with the most recent version. This update is required for the OTLP exporter.

Update OpenTelemetry protobuf definitions

---

api/include/opentelemetry/plugin/tracer.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/span.h
api/test/trace/noop_test.cc
examples/plugin/plugin/tracer.cc
exporters/otlp/recordable.cc
exporters/otlp/recordable.h
sdk/include/opentelemetry/sdk/trace/recordable.h
sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/src/trace/span.cc
sdk/src/trace/span.h
sdk/test/trace/tracer_test.cc

Moving a constant object causes a copy to be made. Let's rather pass a reference.
Related to this [comment](https://github.com/open-telemetry/opentelemetry-cpp/pull/117#discussion_r447942171).

Don't move a constant AttributeValue

---

exporters/otlp/BUILD
exporters/otlp/otlp_exporter_benchmark.cc

Benchmark `Export()` for the OTLP exporter using both full and empty spans.
**Sample output:**
**Output after changing `KeepRunning` to `KeepRunningBatch` and using optimized build:**

Add benchmark tests for OTLP exporter

---

sdk/src/trace/span.cc

See [issue](https://github.com/open-telemetry/opentelemetry-cpp/issues/187).

Recordable attributes are set before passing it onto span processor

---

sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/test/trace/span_data_test.cc

Implement `AddEvent` for SpanData. Currently only `name` and `timestamp` can be set due to limitations in the `recordable` interface. In the future, attributes should also be supported in events.

Add events in SpanData

---

api/include/opentelemetry/context/context.h

Moving a temporary object prevents copy elision.

---

.github/workflows/ci.yml
exporters/ostream/src/span_exporter.cc

Setting `CC=/usr/bin/gcc-4.8` was omitted for our GHA legacy test, resulting in the use of the default Ubuntu 18.04 gcc version.
This PR fixes this and makes our legacy tests actually using gcc-4.8 again (and pass). Merging this will fix other PR builder failures.

Use gcc-4.8 for GHA legacy tests

---

sdk/test/metrics/CMakeLists.txt

In resolving merge conflicts in my Exact aggregator PR I accidentally removed the counter_aggregator and histogram_aggregator tests from sdk/test/metrics/CMakeLists.txt. This PR simply adds those back.
My apologies.

Fix Metrics SDK CMake tests

---

sdk/include/opentelemetry/sdk/metrics/meter.h
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/src/metrics/meter_provider.cc

Simple PR to route library_name and library_version into the Meter constructor.

pass in library_name and library_version into meter

---

ci/install_windows_protobuf.ps1
ci/ports/benchmark/CONTROL
ci/ports/benchmark/portfile.cmake
ci/ports/protobuf/CONTROL
ci/ports/protobuf/fix-android-log.patch
ci/ports/protobuf/fix-static-build.patch
ci/ports/protobuf/fix-uwp.patch
ci/ports/protobuf/portfile.cmake
ci/setup_windows_ci_environment.ps1

Our current CI loop `CI / CMake -> exporter proto` is broken due to mainline vcpkg issue.
Solution is to save local copies of vcpkg port files in our repo. That way if mainline vcpkg breaks something in those packages, we're not affected.
Also adding port file for Google Benchmark to be compatible with both vs2017 and vs2019 compilers. So that one library built once can be shared between the two different compilers. Without that patch it is impossible to reuse the library across two different compilers: since vs2019 introduces some new exception handling function that is not available in older runtime - if you build Google Bechmark from vcpkg with vs2019, then try that prebuilt - it is not gonna link in vs2017! This is yet another "LOL" at ABI compat requirement, showing that not …

Fix build break in protobuf by pinning to older version in our local vcpkg port file

---

sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/test/metrics/BUILD
sdk/test/metrics/metric_instrument_test.cc
sdk/test/metrics/sketch_aggregator_test.cc

This PR builds out SDK support for the [Sketch Aggregator](https://github.com/jmacd/opentelemetry-specification/blob/jmacd/draft_metric_sdk_spec/specification/metrics/sdk.md#aggregator-implementations) which combines updates to metric instruments in meaningful values.  This aggregator in particular uses a compression scheme which preserves accuracy when distributions as severely skewed right.  More information about the algorithm can be found in Datadog's paper on [DDSketch](http://www.vldb.org/pvldb/vol12/p2195-masson.pdf).  The aggregator is dependent on the Metric Instruments API  (pending approval in [PR # 161](https://github.com/open-telemetry/opentelemetry-cpp/pull/161)) and the aggregator base classes [PR # 178](https://github.com/open-telemetry/opentelemetry-cpp/pull/178) --  it …

Add Sketch Aggregator

---

ext/include/opentelemetry/ext/zpages/threadsafe_span_data.h
sdk/include/opentelemetry/sdk/trace/attribute_utils.h
sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/test/trace/BUILD
sdk/test/trace/attribute_utils_test.cc
sdk/test/trace/span_data_test.cc

Add support for links and event attributes to `SpanData`. Note that since `SpanContext` is not yet fully implemented, support for populating `trace_id`, `span_id` and `trace_state` will have to be added later (see issue https://github.com/open-telemetry/opentelemetry-cpp/issues/214).
This PR refactors functionality related to attributes into an `attribute_utils.h` file, simplifying `span_data.h`. The `attribute_utils` includes an  `AttributeMap` class that is used to store attributes in `SpanData`, `SpanDataEvent` and `SpanDataLink`. `AttributeMap` wraps `std::unordered_map` under the hood.

Implement links and event attributes in SpanData

---

sdk/include/opentelemetry/sdk/metrics/aggregator/counter_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/histogram_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/include/opentelemetry/sdk/metrics/controller.h
sdk/include/opentelemetry/sdk/metrics/instrument.h
sdk/test/metrics/BUILD
sdk/test/metrics/controller_test.cc

This PR adds the Controller class to the metrics SDK.  The requirements for this class can be found in the current version of the [SDK specification](https://github.com/jmacd/opentelemetry-specification/blob/jmacd/draft_metric_sdk_spec/specification/metrics/sdk.md#controller-implementation).
The component oversees the entire metric pipeline by collecting data from the Accumulator and exporting it at regular intervals.  This is a push controller, meaning it will automatically send data to the exporter with fixed frequency.  The controller is also where the user can customize aspects of the pipeline.  Specifically, users can define the collection interval, timeout, Processor, and Exporter of their choice.  In the current design, a controller owns the Exporter passed into it, meaning that a …

Add Metrics Controller

---

examples/metrics_simple/BUILD
examples/metrics_simple/README.md
examples/metrics_simple/main.cc

Simple example for setting up the metrics pipeline and showing the 3 different ways to updating instrument values. Include a README that goes into more detail on each of the different parts. This example uses the OStreamMetricsExporter and shows the difference between stateful / stateless modes for the Processor.

Add Simple Metrics example

---

.github/workflows/ci.yml
ci/README.md
ci/do_ci.sh
ci/setup_ci_environment.sh
examples/CMakeLists.txt
examples/metrics_simple/CMakeLists.txt
examples/metrics_simple/main.cc
sdk/include/opentelemetry/sdk/metrics/controller.h
sdk/test/metrics/CMakeLists.txt
sdk/test/metrics/controller_test.cc
sdk/test/metrics/metric_instrument_test.cc

This adds a new task `bazel.valgrind` and adds it to our CI.
This task runs all our test via Bazel under the valgrind memory checker, thus exposing any memory leaks or memory violations.

Add a memory check task to the CI

---

api/include/opentelemetry/trace/trace_state.h
api/test/trace/trace_state_test.cc

Currently we're using `strcpy` to copy keys and values into `TraceState` entries. This causes problems when the keys/values are not null-terminated. Fix this by using `memcpy` with the string_view `size`, instead of `strcpy`.

Use memcpy in TraceState

---

api/test/trace/trace_state_test.cc

`TraceState` tests currently call the string_view `data()` method when comparing string_view instances. These calls are unecessary, since the string_view [equality operator](https://en.cppreference.com/w/cpp/string/basic_string_view/operator_cmp) compares the content directly. This PR removes calls to `data()` to simplify the code.

Simplify TraceState tests

---

sdk/include/opentelemetry/sdk/metrics/aggregator/aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/counter_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/exact_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/gauge_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/histogram_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/min_max_sum_count_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/include/opentelemetry/sdk/metrics/sync_instruments.h
sdk/test/metrics/metric_instrument_test.cc

This PR is meant to resolve Issue #255.
I have added a new bool variable to the aggregator base class to track whether or not the aggregator has been updated in the most recent collection cycle. Some additional logic was then added to the SDK sync instrument classes to refrain from creating records from aggregators that have received no recent updates. Since there are no records created from these un-updated (stale) instruments, they will not be exported.
I did not implement the same logic for the SDK async instrument classes as I don't believe it would make sense there. Asynchronous instruments are supposed to be exported by interval rather than by request: Therefore they are never stale.

Add logic to refrain from exporting un-updated metric instruments

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_exporter.h
exporters/otlp/src/otlp_exporter.cc
exporters/otlp/test/otlp_exporter_test.cc

Add an `options` struct to the OTLP exporter to allow exporter configuration (see [OTLP exporter spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md)). Add a new OTLP exporter constructor that accepts and sets these options.
This PR adds an `endpoint` configuration, with a default of `localhost:55680`. In the future, other configuration options will be added, such as `timeout`.
Note that this PR changes the default port used to connect to the OpenTelemetry Collector from `55678` to `55680`, in accordance with https://github.com/open-telemetry/opentelemetry-cpp/issues/239.

Add OTLP exporter configuration

---

examples/otlp/BUILD
examples/otlp/CMakeLists.txt
examples/otlp/README.md
examples/otlp/foo_library/foo_library.cc
examples/otlp/foo_library/foo_library.h
examples/otlp/main.cc

Add an example application using the OTLP exporter. The example includes a detailed README with instructions on how to configure the OpenTelemetry Collector to use the OTLP exporter.
Currently, `foo_library` makes explicit calls to `span->End()` to work around https://github.com/open-telemetry/opentelemetry-cpp/issues/287. These calls should be removed once the issue is resolved. I've added a TODO in the code for this.

Add OTLP exporter example

---

examples/otlp/main.cc
exporters/otlp/README.md

Add a README to the OTLP exporter directory to describe the exporter and how it can be used/configured.

Add OTLP exporter README

---

exporters/otlp/README.md

The link to `otlp_exporter.h` is broken in the current version of the README. Fix it to use the proper path.

Fix broken link in OTLP exporter README

---

api/include/opentelemetry/plugin/tracer.h
api/include/opentelemetry/trace/default_span.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/scope.h
api/include/opentelemetry/trace/span.h
api/include/opentelemetry/trace/tracer.h
api/test/trace/BUILD
api/test/trace/CMakeLists.txt
api/test/trace/noop_test.cc
api/test/trace/scope_test.cc
examples/plugin/plugin/tracer.cc
examples/simple/foo_library/foo_library.cc
sdk/src/trace/span.cc
sdk/src/trace/span.h
sdk/src/trace/tracer.cc
sdk/test/trace/tracer_test.cc

Currently, whenever a new span is created, this span is set as the active span. This is not in line with the specification, which asks for the possibility to create spans that are not set to active, and which even asks that this should be the default.
This PR decouples the the span lifetime from the time the span is active, it does so by introducing a `Scope` object, which is very similar to what [OpenTelemetry Java](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/Tracer.java#L140) does:
```c++
auto span = tracer->StartSpan("f1");
/* span is started, but not active */
auto scope = tracer->WithActiveSpan(span);
/* span is started and active */
scope.reset(nullptr);
/* span is started, but not active anymore */
span->End();
/* span …
```

Add Scope object to control the currently active span

---

api/include/opentelemetry/context/context.h
api/test/context/context_test.cc

A tiny(est) of fixes to prevent crash while creating new context from existing context properties. The reference variable was used to store list head and later to iterate over the context list (at line 46), which eventually crashes. Changed it to non-reference variable, and added test case to validate the scenario.

fix context data structure to support multiple attributes

---

.github/workflows/ci.yml
ci/docfx.cmd
ci/docfx.json
ci/toc.yml
docs/cpp-metrics-api-design.md
docs/cpp-metrics-sdk-design.md
docs/cpp-ostream-exporter-design.md
exporters/otlp/README.md

Changes: 
-Added a docfx ci check after existing ci tests (in ci.yml file)
-Changed 2 markdown links from relative to absolute urls (since absolute URLs are used consistently in all READMEs in this repo and docfx CI tests wouldn't recognize relative urls even though it would be linked properly after uploading to  github) 
-Commented out 4 missing .png source files
-Added 3 new files to /ci folder (docfx.json, toc.yml, docfx.cmd) and 1 new file to /build folder (docfx.yml) - nothing new in top level
-Removed SETLOCAL in docfx.cmd

add docfx ci

---

README.md

I'll need to submit a request to get the triager team created. For now I'll add @jodeev to the approvers list to unblock the access issue.

Add jodeev as a triager

---

sdk/src/trace/span.cc

The no-op reference to input parameter `options` is no longer necessary because it is referenced later in the same function at line 101.

Remove unnecessary reference to StartSpanOptions

---

api/include/opentelemetry/trace/tracer.h
api/test/trace/BUILD
api/test/trace/CMakeLists.txt
api/test/trace/tracer_test.cc

This adds a method `GetCurrentSpan` on the tracer, which returns the currently active span.
This is defined in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracer-operations) as an optional operation on the tracer.
Fixes #317.

Add method to get currently active span

---

api/include/opentelemetry/trace/noop.h
sdk/src/trace/tracer.cc

Don't create a `NoopSpan` for each `NoopTracer::StartSpan` call or for each `DROP` sampling decision, but instead use a static singleton in both cases.
This causes a significant performance improvement for the [BM_NoopSpanCreation](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/test/trace/sampler_benchmark.cc#L173) benchmark.

Optimize no-op span creation

---

sdk/src/trace/span.cc
sdk/test/trace/tracer_test.cc

As per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events), add events for Span to the field of `Recordable` object.

AddEvent support for Span

---

.github/.codecov.yaml

This disables the flaky patch coverage check (documented [here](https://docs.codecov.io/docs/commit-status#disabling-a-status)).

Disable flaky patch coverage checks

---

api/include/opentelemetry/context/runtime_context.h

Parameter `new_capacity` for `RuntimeContext::Resize()` should be in type `size_t` instead of `int`, to be consistent with `size_`.
This could cause issue because `size_t` could have larger range than `int` (this is the case on Windows 64-bit system which is in LLP64 data model), so convert `size_t` to `int` could cause data loss.

Change type of Resize capacity from int to size_t

---

ext/test/zpages/tracez_data_aggregator_test.cc
sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/test/trace/probability_sampler_test.cc

Add explicit type conversion and more fixes to consistency of using `size_t` and `int`.

Add explicit type conversion to narrower data type

---

ext/test/zpages/tracez_processor_test.cc

A minor fix of the result type of `size_t - size_t`.

Correct type of size_t - size_t to be size_t in tracez_processor_test

---

.github/workflows/ci.yml
ci/do_ci.sh
ci/setup_cmake.sh

We support experimental C++11 on gcc4.8 , but cmake build is missing for that. Adding a GitHub action for that.

cmake build with gcc4.8

---

api/include/opentelemetry/context/context.h
exporters/ostream/include/opentelemetry/exporters/ostream/metrics_exporter.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/prometheus_collector.h
exporters/prometheus/src/prometheus_collector.cc
exporters/prometheus/src/prometheus_exporter_utils.cc
exporters/prometheus/test/prometheus_collector_test.cc
exporters/prometheus/test/prometheus_exporter_utils_test.cc
sdk/src/metrics/meter.cc
sdk/test/metrics/sketch_aggregator_test.cc

As indicated in subject, quick fix to eliminate compile time warnings originating from `-Wsign-compare` and `-Wreorder` flags.

fix compile time warnings

---

README.md

Discussed during the Oct. 7th, 2020 SIG meeting.
@lalitb has been actively contributing to OpenTelemetry C++ across many modules as well as general improvements to the CI and infrastructure. He is also actively driving the better design of OpenTelemetry C++ API/SDK.
PRs @lalitb has authored:
* #354
* #352
* #351 
* #309
* #330
PRs @lalitb has contributed:
* #349
* #211
* #322
* #353
* #54
* #290
* #301
* #315
@ThomsonTan has been activity contributing to the overall OpenTelemetry project, including the specs, .NET client and C++ client.
PRs @ThomsonTan has authored in OpenTelemetry C++:
* #300
* #301
* #327
* #338
* #343
* #346
* #347
* #353
@ThomsonTan has also contributed to several PRs in multiple OpenTelemetry repositories, there are too many to list out here.

Add lalitb and ThomsonTan as approvers

---

api/include/opentelemetry/trace/default_span.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/span.h
api/include/opentelemetry/trace/span_context.h
api/test/trace/propagation/http_text_format_test.cc
api/test/trace/span_context_test.cc
examples/plugin/plugin/tracer.cc
sdk/src/trace/tracer.cc
sdk/test/trace/tracer_test.cc

This PR extends the `StartSpanOptions` struct by a `parent` SpanContext. If this is given, it will be used as a parent for a given span.
While I was at it, I cleaned up some things in the `SpanContext` implementation.
Closes #318.

Add functionality to explicitely specify a span parent

---

exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h

In `OStreamSpanExporter` class, it prints the value of `SpanDataAttributeValue` which is in type `nostd::variant`. The print function enumerates (`if/else if/...`) all the types in this `nostd::variant`, but the output of the value is almost the same (categorized into vector and primitive types) and it needs to be updated for any change in the associated `nostd::variant` type.
The PR replaces the type enumeration by `nostd::visit` which visits the variant with correct type, and dispatches to right overloaded `print_value` function.

Simplify walking the values in SpanDataAttributeValue

---

api/include/opentelemetry/common/spin_lock_mutex.h
api/include/opentelemetry/metrics/provider.h
api/include/opentelemetry/trace/provider.h
sdk/include/opentelemetry/sdk/trace/exporter.h
sdk/include/opentelemetry/sdk/trace/processor.h
sdk/include/opentelemetry/sdk/trace/simple_processor.h
sdk/test/trace/simple_processor_test.cc

Changes:
- Ensure calls to the configured `Exporter` are locked behind an atomic_flag.
- We use a spin-lock for now, under the assumption that Exporter calls are fast.
Notes:
1. I tried really really hard to write a test that would fail if the locking wasn't in place, and was unable to make anything consistent/worthwhile, so that's dropped.  If you have a good idea to how to write a test to ensure locking is done properly and failure to lock causes an issue, more than happy to add it.
2. I thought spin-lock usage was "ok" given two assumptions: (a) Exporter calls will be 'fast' and (b) "simple" processor is not likely to be used over the buffering processor.   If either of these are wrong, please let me know.
3. The spin-lock itself could easily be improved w/ C++20x mechanisms or by …

Add thread safety to SimpleSpanProcessor

---

README.md

As discussed in the Oct. 12th, 2020 SIG meeting, I added the supported C++ standard versions to the README.

Document the supported C++ versions

---

api/include/opentelemetry/context/context.h
api/include/opentelemetry/context/runtime_context.h
api/include/opentelemetry/trace/scope.h
api/test/context/runtime_context_test.cc

This PR simplifies the context implementation and fixes some minor glitches:
* `Token` objects are stored on the heap now. They were stored on the stack before, but they included heap-allocated shared pointers of `ContextDetacher` objects. Giving out `Token` objects as `unique_ptr`s greatly simplifies the implementation. It's also more efficient (managing a `unique_ptr` instead of a `shared_ptr`). If there need to be copies of a token, it can be transferred into a `shared_ptr`. With that design, we can get completely rid of the `ContextDetacher` class.
* Some optimizations around making class members `const`.
This relates to #219.

Simplify context implementation

---

api/include/opentelemetry/context/runtime_context.h
api/test/context/runtime_context_test.cc

With the existing solution, users had to make sure that they always detached contexts in exactly the reverse orders they were attached. So, for attaching contexts in the order `A - B - C`, they have to be detached in the order `C - B - A`. If a user would try to detach `B` before `C`, this would lead to an error (which the user doesn't notice if they don't explicitly check the return code of `Detach`). This can lead problems if a user forgets to detach a context (in this case, this context would never be detached).
With this PR the strategy is changed so that if a context is detached, all it's active child contexts are detached too. So if a user attaches contexts in the order `A - B - C`, and then detached `B`, both `B` and `C` will be detached. This is a much more robust solution that …

Change strategy for detaching contexts

---

examples/plugin/load/main.cc

`strerror` triggers  below warning when building by MSVC. Follow the
suggestion and switch to `strerror_s`.
warning C4996: 'strerror': This function or variable may be unsafe.
Consider using strerror_s instead. To disable deprecation, use
_CRT_SECURE_NO_WARNINGS. See online help for details.

Switch strerror to strerror_s

---

sdk/include/opentelemetry/sdk/trace/sampler.h
sdk/include/opentelemetry/sdk/trace/samplers/always_off.h
sdk/include/opentelemetry/sdk/trace/samplers/always_on.h
sdk/include/opentelemetry/sdk/trace/samplers/parent.h
sdk/include/opentelemetry/sdk/trace/samplers/trace_id_ratio.h
sdk/src/trace/samplers/parent.cc
sdk/src/trace/samplers/trace_id_ratio.cc
sdk/src/trace/tracer.cc
sdk/test/trace/always_off_sampler_test.cc
sdk/test/trace/always_on_sampler_test.cc
sdk/test/trace/parent_sampler_test.cc
sdk/test/trace/sampler_benchmark.cc
sdk/test/trace/trace_id_ratio_sampler_test.cc
sdk/test/trace/tracer_test.cc

Passing links to sampler API

---

sdk/include/opentelemetry/sdk/logs/logger.h
sdk/include/opentelemetry/sdk/logs/logger_provider.h
sdk/include/opentelemetry/sdk/logs/processor.h
sdk/src/CMakeLists.txt
sdk/src/logs/BUILD
sdk/src/logs/CMakeLists.txt
sdk/src/logs/logger.cc
sdk/src/logs/logger_provider.cc
sdk/test/CMakeLists.txt
sdk/test/logs/BUILD
sdk/test/logs/CMakeLists.txt
sdk/test/logs/logger_provider_sdk_test.cc
sdk/test/logs/logger_sdk_test.cc

This PR contains an initial implementation of the Logging SDK, which follows from the [initial API commit](https://github.com/open-telemetry/opentelemetry-cpp/pull/378#partial-pull-merging) and the [logging prototype issue](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/overview.md). 
This PR adds:
* SDK LoggerProvider class - returns instances of the SDK Logger and stores a common processor
* SDK Logger class - filters logs based off severity and sends to a processor
* Processor Interface - interface that defines what a processor implementation will require. A future PR will contain concrete processor classes derived from this
* Unit tests for the LoggerProvider and Logger classes
Any suggestions or feedback would be greatly appreciated! The …

Add Logging SDK implementation for Logging API

---

ci/README.md

This PR adds the missing Github Actions CI test, `Cmake gcc 4.8`, to the `ci/README.md` file. 
cc @alolita

Add missing CI test to README

---

README.md

Discussed during the Nov. 23rd, 2020 SIG meeting.
@jsuereth has been actively contributing to OpenTelemetry C++ across many modules as well as general improvements to the CI and infrastructure. He has also expressed the willing to make more contributions in the future.
PRs @jsuereth has authored:
* #358
* #402
PRs @jsuereth has contributed to:
* #275
* #373
* #374
* #376
* #377
* #385
* #392
* #399
* #403

Add jsuereth as an Approver

---

README.md

@alolita has been helping multiple projects across the OpenTelemetry community. She has been one of the key stakeholders of the OpenTelemetry C++ metrics prototype, and now driving the C++ logging prototype.
Related to #410.
https://github.com/open-telemetry/community/blob/master/community-membership.md#triager

Add alolita as a Triager

---

CONTRIBUTING.md

Trying to update existing PR guidelines to ensure smoother ( and probably faster ) merge process:
- With current small number of Approvers ( and their distribution across different companies ), making number of required approvals ( from different company ) as 1 ( from existing 2 ). We can review this after course of time once we have good distribution.
- Requirement for Updating the changelog (CHANGELOG.md) for non-trivial changes.
- Handling lots of discussions in given PR.

Updating PR Guidelines

---

sdk/test/logs/simple_log_processor_test.cc

`batch_size_received` in [sdk/test/logs/simple_log_processor_test.cc](https://github.com/open-telemetry/opentelemetry-cpp/blob/master/sdk/test/logs/simple_log_processor_test.cc) has inconsistent usage between `size_t` and `int`. Change it to `size_t` to be consistent.

Change type of batch_size_received to size_t

---

.gitattributes
CONTRIBUTING.md

`-resursive` is available an option for git since 1.6.5 which clones all submodules. The current version of git is 2.28 or above so I think it is fine to expect `-recursive` for git. This would be very helpful as we added many dependencies as submodule to this repo.
Also add line-ending setting for `.cc` file which is missing.

Add -recursive to recommended git clone command line

---

docs/cpp-metrics-api-design.md
docs/cpp-metrics-sdk-design.md
docs/cpp-ostream-exporter-design.md

The code samples in the design docs were not always using syntax highlight, some of the comments were misaligned, I found a couple of typos, and in some comments two lines were merged. I also fixed some really wide code so it would not require scrolling to see the whole line.

doc: fix formatting for code samples

---

examples/otlp/foo_library/foo_library.cc

`End()` calls are added to Span so explicit call is no longer necessary, see https://github.com/open-telemetry/opentelemetry-cpp/issues/287#issuecomment-699019923

Remove unnecessary call on Span::End()

---

api/test/nostd/shared_ptr_test.cc

`size_t` could be wider than `int` could make the conversion explicit.

Add explicit conversion from size_t to int for shared_ptr_test

---

api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/scope.h
api/include/opentelemetry/trace/span.h
api/include/opentelemetry/trace/tracer.h
api/test/trace/CMakeLists.txt
api/test/trace/propagation/http_text_format_test.cc
api/test/trace/scope_test.cc
sdk/src/trace/tracer.cc

The `Extract` call on the W3C propagator used to store the extracted span under the key `current-span` in the context, whereas on other places we rely on the current span being stored under the key `span_key`. This discrepancy will break context propagation.
This PR unifies this to use a constant `kSpanKey` in all relevant places and also adds tests.

Use a consistent key for the current span in the context

---

api/include/opentelemetry/common/spin_lock_mutex.h
api/include/opentelemetry/nostd/string_view.h
api/include/opentelemetry/plugin/detail/dynamic_load_windows.h
api/include/opentelemetry/std/span.h
ext/include/opentelemetry/ext/http/server/socket_tools.h
sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/src/common/fast_random_number_generator.h

The issue is that `Windows.h` redefines both `min` and `max` as macros.
There are several fixes possible:
- targeted fix: surround the usage of `std::min` and `std::max` with parenthesis; OR
- globally define `NOMINMAX` for the entire project in CMake; OR
- in those modules where it is known that `std::*` is going to be used, `#define NOMINMAX` right before the inclusion of Windows.h
Since there were two recent hits @mishal23 @jsuereth , I'm applying targeted fix to avoid this issue wherever possible.
Not defining `NOMINMAX` globally, as this may lead to other interesting side-effects inside the bowels of Windows SDK 😁

Resolve NOMINMAX issues where possible

---

cmake/opentelemetry-proto.cmake

Build protobuf generated files and skeleton as object library could requires adding it directly to `add_executable(...)` or `add_library(...)` instead of linking it via `target_link_libraries(...)`. Build these files as static library to better fit linking as library.

Build opentelemetry-proto as static instead of object library

---

bazel/repository.bzl

Looks like in tools there is a script that uses the submodule, for whatever reasons :)... leaving for the moment the submodule.

Use google benchmarks directly from released tags in bazel

---

api/include/opentelemetry/trace/propagation/http_trace_context.h

When SDK is compiled with STL (standard library) classes flavor, this code won't compile with vs2019 in C++20 mode:
```cpp
nostd::string_view string;
...
const char *str_id = string.begin();
```
with an error `Error	C2440	'initializing': cannot convert from 'std::_String_view_iterator<_Traits>' to 'const char *'	http_text_format_test	6	C:\work\opentelemetry-cpp-etw\api\include\opentelemetry\trace\propagation	C:\work\opentelemetry-cpp-etw\api\include\opentelemetry\trace\propagation\http_trace_context.h	132			CL`
The fix is to use `.data()` instead of `.begin()` . `data()` always points to `const char *` buffer.

GenerateHexFromString http_trace_context.h uses non-standard assignment

---

WORKSPACE
bazel/repository.bzl

Split from https://github.com/open-telemetry/opentelemetry-cpp/pull/459, this should be trivial.

Remove protobuf dependency from bazel, not used anywhere

---

bazel/repository.bzl

The problem is that when using in third-party bazel complains that the there needs to be a "//bazel:opentelemetry_proto.BUILD" file in the dependent project, which there is not. This way we setup bazel to use the build file from the dependency project. This was a mistake in the previous PR I submitted. I tested this now and it works.

Use bazel build relative to this repository

---

cmake/opentelemetry-proto.cmake

The protobuf generated header files are not installed in CMake script so the OTLP header files cannot included from the installed package. This PR installs the generated header files to the correct location.

Install protobuf generated header file for OTLP

---

exporters/etw/include/opentelemetry/exporters/etw/etw_provider_exporter.h
exporters/etw/include/opentelemetry/exporters/etw/uuid.h

Do explicit type narrow down cast from `size_t` to `ULONG`, and also change unsafe CRT call `sscanf` to `sscanf_s`.

Fix unsafe type cast and CRT call

---

ci/setup_cmake.sh

The Windows build installs CMake version 3.15.2 (see below link), so upgrade Linux to the same version. This version upgrade for Linux is helpful because the CMake from `apt install` on Ubuntu 18.10 is 3.10, and this version of CMake doesn't support installation from submodule (this affects gRPC installation from source tree, see [here](https://github.com/grpc/grpc/blob/0539a63274cd73288ec13fea16fa855b01c73e61/CMakeLists.txt#L62)).
https://github.com/open-telemetry/opentelemetry-cpp/blob/master/ci/setup_windows_cmake.ps1#L4

Upgrade CMake to 3.15.2 for Linux

---

examples/otlp/README.md
exporters/otlp/README.md
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_exporter.h

From specification - https://github.com/open-telemetry/opentelemetry-specification/pull/1221

OTLP change default port number

---

CONTRIBUTING.md

As agreed in community meeting dated 13th Jan 2021 ( https://docs.google.com/document/d/1i1E4-_y4uJ083lCutKGDhkpi3n4_e774SBLi9hPLocw/ ) , proposing changes in Contribution Guide to allow maintainers merge PRs which doesn't meet minimum approval requirement. 
We can revisit this again once we are nearing GA release, and/or there are sufficient approvers from multiple companies.

Update PR merge requirement.

---

api/include/opentelemetry/trace/trace_state.h

small fix for namespace scoping of `TraceState`.

fix namespace scoping for TraceState

---

cmake/opentelemetry-proto.cmake

When building with `-DWITH_OTLP=ON` then `gRPC_CPP_PLUGIN_EXECUTABLE` can't be imported from a current gRPC build, changing it to `TARGET_FILE` fixes the issue. (gRPC examples use the same method: https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/CMakeLists.txt#L123)

CMake: fix gRPC_CPP_PLUGIN_EXECUTABLE import

---

CMakeLists.txt
opentelemetry-cpp-config.cmake.in

This fixes https://github.com/open-telemetry/opentelemetry-cpp/issues/513 by passing the missing `INCLUDE_INSTALL_DIR` to `configure_package_config_file` as `PATH_VARS`.

Fix missing include dir for configure_package_config_file

---

api/include/opentelemetry/trace/span_context.h
api/test/trace/propagation/http_text_format_test.cc
api/test/trace/span_context_test.cc

As defined in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#isremote), the `SpanContext` should have a method `IsRemote`, and not `HasRemoteParent`.

Rename SpanContext.HasRemoteParent to SpanContext.IsRemote

---

cmake/opentelemetry-proto.cmake

CMake `target_link_libraries()` should be called instead of `target_include_directories()` to link to library like protobuf.

Fix calling target_include_directories on library

---

.github/workflows/ci.yml
buildscripts/pre_release.sh

Follow up on #531.
Please run the following commands on your local clone to migrate over:
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
```

Move from master to main (step2)

---

api/include/opentelemetry/trace/span_id.h

The current check of `SpanId::IsValid` constructs a default instance of `SpanId` and then make comparison between the 2 instance. Improve this by assuming the 8 bytes `SpanId` as unsigned 64-bit integer and comparing it with 0 directly.

Improve invalid span Id check

---

api/include/opentelemetry/plugin/tracer.h
api/include/opentelemetry/trace/default_span.h
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/span.h
api/test/trace/noop_test.cc
examples/plugin/plugin/tracer.cc
examples/zpages/zpages_example.cc
exporters/etw/include/opentelemetry/exporters/etw/etw_data.h
exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/ostream/test/ostream_span_test.cc
exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h
exporters/otlp/src/recordable.cc
exporters/otlp/test/recordable_test.cc
ext/include/opentelemetry/ext/zpages/threadsafe_span_data.h
ext/src/zpages/tracez_data_aggregator.cc
ext/test/zpages/threadsafe_span_data_test.cc
ext/test/zpages/tracez_data_aggregator_test.cc
sdk/include/opentelemetry/sdk/trace/recordable.h
sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/src/trace/span.cc
sdk/src/trace/span.h
sdk/test/trace/span_data_test.cc

update StatusCode as per specs.  Permitted values : `Unset`, `Ok`, `Error` , and NOT the grpc values.
Specs: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md
--clip--
**Set Status**
Sets the Status of the Span. If used, this will override the default Span status, which is Unset.
Status is structurally defined by the following properties:
StatusCode, one of the values listed below.
Optional Description that provides a descriptive message of the Status. Description MUST only be used with the Error StatusCode value.
StatusCode is one of the following values:
_Unset_
The default status.
_Ok_
The operation has been validated by an Application developer or Operator to have completed successfully.
_Error_
The operation contains an error.
The …

Update StatusCode as per specs

---

CONTRIBUTING.md
README.md
api/include/opentelemetry/trace/propagation/b3_propagator.h
docs/cpp-metrics-api-design.md
docs/cpp-metrics-sdk-design.md
docs/library-distribution.md
examples/otlp/README.md
exporters/otlp/README.md
ext/src/zpages/README.md
sdk/include/opentelemetry/sdk/logs/log_record.h

Changed the branch to main in all links to OpenTelemetry repos.

Fix branch name to main in links

---

api/include/opentelemetry/common/key_value_iterable.h
api/include/opentelemetry/common/key_value_iterable_view.h
api/include/opentelemetry/nostd/mpark/variant.h
api/include/opentelemetry/nostd/unique_ptr.h
api/include/opentelemetry/plugin/factory.h
api/include/opentelemetry/trace/span_context_kv_iterable_view.h
api/test/trace/key_value_iterable_view_test.cc
bazel/otel_cc_benchmark.bzl
ci/install_format_tools.sh
exporters/etw/include/opentelemetry/exporters/etw/etw_data.h
exporters/etw/include/opentelemetry/exporters/etw/etw_provider_exporter.h
exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_data.h
exporters/ostream/include/opentelemetry/exporters/ostream/log_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/metrics_exporter.h
exporters/prometheus/src/prometheus_exporter_utils.cc
exporters/prometheus/test/prometheus_collector_test.cc
exporters/prometheus/test/prometheus_exporter_utils_test.cc
ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
ext/include/opentelemetry/ext/http/client/http_client.h
ext/include/opentelemetry/ext/http/server/socket_tools.h
sdk/include/opentelemetry/sdk/common/attribute_utils.h
sdk/include/opentelemetry/sdk/common/circular_buffer.h
sdk/src/logs/batch_log_processor.cc
sdk/src/logs/logger.cc
sdk/src/trace/batch_span_processor.cc
sdk/src/trace/span.cc
sdk/test/common/circular_buffer_benchmark.cc
sdk/test/common/circular_buffer_test.cc
tools/format.sh

Upgrade clang-format to 10.0.0, run ./tools/format.sh

---

CONTRIBUTING.md

The passcode was added to `CONTRIBUTING` section in https://github.com/open-telemetry/opentelemetry-cpp/blob/main/README.md but got missed in https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CONTRIBUTING.md.

Add Zoom meeting passcode to meeting link in contributing.md

---

ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

cURL defines status code for HTTP response as `enum` (see doc [here](https://curl.se/libcurl/c/libcurl-errors.html)) and our http_client defines it as `uint16_t` as below. This PR changes the cURL wrapper `HttpOperation` to return `uint16_t` as well.
https://github.com/open-telemetry/opentelemetry-cpp/blob/dafd82a417abb85e8271f83d2c632a945c3e4fc9/ext/include/opentelemetry/ext/http/client/http_client.h#L95

Assign HTTP status code from cURL to uint16_t type

---

README.md

Add C++20 was published in Dec 2020 (https://www.iso.org/standard/79358.html) and our `cmake.c++20.test` also passes, we should add C++20 to the listed of supported C++ standards.

Add C++20 to the doc as supported standard

---

CONTRIBUTING.md
ext/include/opentelemetry/ext/zpages/tracez_processor.h
ext/src/zpages/tracez_processor.cc
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/include/opentelemetry/sdk/trace/processor.h
sdk/include/opentelemetry/sdk/trace/simple_processor.h
sdk/src/trace/batch_span_processor.cc
sdk/src/trace/span.cc
sdk/test/trace/simple_processor_test.cc

as per spec https://github.com/open-telemetry/opentelemetry-specification/blob/7e0c10260178b947777cf9c11d7f7ac4d4700725/specification/trace/sdk.md#onstart
`SpanProcessor.onStart()` should have a parent Context as parameter.
fixes: #550

Passing parent context to SpanProcessor::OnStart()

---

api/include/opentelemetry/trace/trace_state.h
api/test/trace/CMakeLists.txt
api/test/trace/trace_state_test.cc

Current tracestate api is not compliant to `opentelemetry` and `w3c trace` specs. Attempt to fix in this PR. 
To Summaries the changes
- As per the opentelemetry specs (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#tracestate), TraceState object is immutable, and `add`, `update` and `delete` methds should return newly created object. Added/updated needed methods.
- Methods to serialize and de-serialize TraceState object to/from w3c trace header ( as defined here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#tracestate)
- Much accurate validation check for tracestate list members using regex in non-gcc4.8 compiler.
#537

TraceState implementation as per spec

---

ci/README.md

The build target `code.coverage` will build target with coverage data and run tests, but it will not upload the result coverage data to https://codecov.io. The latter work is done by GitHub action at
https://github.com/open-telemetry/opentelemetry-cpp/blob/main/.github/workflows/ci.yml#L330.

Remove incorrection description on code.coverage in CI doc

---

api/include/opentelemetry/context/context.h
api/include/opentelemetry/context/runtime_context.h
api/include/opentelemetry/nostd/absl/.clang-format
api/include/opentelemetry/nostd/absl/README.md
api/include/opentelemetry/nostd/absl/base/attributes.h
api/include/opentelemetry/nostd/absl/base/config.h
api/include/opentelemetry/nostd/absl/base/internal/identity.h
api/include/opentelemetry/nostd/absl/base/internal/inline_variable.h
api/include/opentelemetry/nostd/absl/base/internal/invoke.h
api/include/opentelemetry/nostd/absl/base/macros.h
api/include/opentelemetry/nostd/absl/base/optimization.h
api/include/opentelemetry/nostd/absl/base/options.h
api/include/opentelemetry/nostd/absl/base/policy_checks.h
api/include/opentelemetry/nostd/absl/base/port.h
api/include/opentelemetry/nostd/absl/meta/type_traits.h
api/include/opentelemetry/nostd/absl/types/bad_variant_access.h
api/include/opentelemetry/nostd/absl/types/internal/variant.h
api/include/opentelemetry/nostd/absl/types/variant.h
api/include/opentelemetry/nostd/absl/utility/utility.h
api/include/opentelemetry/nostd/variant.h

Fixes #314 . It does not yet add the build system for supporting vs2015 builds in CI, as it is quite involved (there is no GitHub Actions runner with preinstalled vs2015 and installing one may need some tweaking, and IS SLOW.. unless we cache some docker container image for that). Best we can do is deploy additional vs2015 community build tools. I'll cover CI for vs2015 in a separate PR. I verified the code locally with ETW exporter on Windows with Visual Studio 2015 - Update 2. It compiles and works well.
- MPark variant that we use in the SDK is NOT compiling with Visual Studio 2015. Abseil Variant is compiling and working well with Visual Studio 2015 Update 2+. This visual studio version requirement is coming from Abseil itself, but it's a reasonable requirement. The solution is to add …

Patches to enable Visual Studio 2015 - Update 2 support

---

.markdownlint.yml
CONTRIBUTING.md
README.md
RELEASING.md
Versioning.md
api/include/opentelemetry/nostd/absl/README.md
ci/README.md
docs/abi-compatibility.md
docs/abi-policy.md
docs/building-with-stdlib.md
docs/building-with-vcpkg.md
docs/cpp-metrics-api-design.md
docs/cpp-metrics-sdk-design.md
docs/cpp-ostream-exporter-design.md
docs/library-distribution.md
docs/requirements.md
docs/using-clang-format.md
examples/metrics_simple/README.md
examples/otlp/README.md
examples/simple/README.md
exporters/otlp/README.md
ext/src/zpages/README.md
ext/test/w3c_tracecontext_test/README.md
tools/ports/opentelemetry/TODO.md

Follow up #578.
No content change, just reformatted markdown files and enforce all markdownlint policy in CI.

Lint and reformat markdown

---

CONTRIBUTING.md
README.md

As agreed and announced [here](https://medium.com/opentelemetry/opentelemetry-specification-v1-0-0-tracing-edition-72dd08936978#), we're moving to to Slack for all the IMs.

Move from Gitter to Slack

---

api/docs/Doxyfile
api/docs/Overview.md
buildscripts/pre-commit

This PR adds a main page for the API reference documentation.
It also makes sure the version in the API documentation is updated by our release build scripts.

Add main page for API documentation

---

api/include/opentelemetry/trace/propagation/b3_propagator.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/propagation/text_map_propagator.h
api/test/trace/propagation/b3_propagation_test.cc
api/test/trace/propagation/http_text_format_test.cc

Fixes #536
As per spec open-telemetry/opentelemetry-specification#793
Trivial change.

Rename HTTPTextFormat to TextMapPropagator

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/trace/tracer_provider.h
sdk/src/logs/logger.cc
sdk/src/trace/tracer_provider.cc
sdk/test/trace/tracer_provider_test.cc

Fixes #587 
Add `ForceFlush` to TracerProvider as per the spec PR https://github.com/open-telemetry/opentelemetry-specification/pull/1452

Add ForceFlush to TracerProvider in SDK

---

CHANGELOG.md
api/docs/Doxyfile
api/include/opentelemetry/version.h
sdk/src/version/version.cc

Release 0.2.0
New alpha release 0.2.0
As of now, it's ok to have same semver for both api and sdk, and hence single source package release. Once we start deviating in release number, we can plan to have separate source packages for api, and sdk  ( including exporters, propagators, instrumentations )

Release for  0.2.0

---

cmake/opentelemetry-proto.cmake

We found the issue in our internal integration of opentelemetry-cpp.
If opentelemetry-cpp is included by other projects directly via CMake, `CMAKE_SOURCE_DIR` would be the root of the referencing project instead of opentelemetry-cpp, then the relative path which assumes `CMAKE_SOURCE_DIR` is the root dir of opentelemetry-cpp will be incorrect. This PR fixes the issue by replacing `CMAKE_SOURCE_DIR` by `CMAKE_CURRENT_SOURCE_DIR`.

Set proto file path based on CMAKE_CURRENT_SOURCE_DIR

---

sdk/src/trace/span.cc
sdk/src/trace/span.h
sdk/src/trace/tracer.cc
sdk/test/trace/tracer_test.cc

Fixes #602 
`trace_flags` is propagated from parent span to child span at span creation time.

Propagate trace_flags from parent span to child span

---

exporters/zipkin/src/recordable.cc

Cast timestamp to microseconds to match the api

Zipkin timestamp should be in microseconds according to the api

---

CHANGELOG.md
CONTRIBUTING.md
api/include/opentelemetry/context/context.h
api/include/opentelemetry/trace/propagation/b3_propagator.h
api/include/opentelemetry/trace/propagation/detail/context.h
api/include/opentelemetry/trace/propagation/detail/hex.h
api/include/opentelemetry/trace/propagation/detail/string.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/propagation/jaeger.h
api/test/trace/propagation/BUILD
api/test/trace/propagation/CMakeLists.txt
api/test/trace/propagation/jaeger_propagation_test.cc
api/test/trace/propagation/util.h

Fixes #542 
Adds Jaeger trace extraction and injection as specified [here](https://www.jaegertracing.io/docs/1.22/client-libraries/#propagation-format).
Baggage is not part of the PR as it's not supported by the otel-cpp API yet.
Miscellaneous:
* Removed `GetCurrentSpan` duplication from each propagator. Moved it to context's member function.
* Added hex (zero left-padded parse) and string helper (split) functions. These can be used in the b3 and http propagators to simplify code and remove duplication. Not part of this PR though, I will do a follow up if this one gets merged.

Add Jaeger propagator

---

CHANGELOG.md
sdk/src/resource/resource.cc
sdk/test/resource/resource_test.cc

The `service.name` attribute of Resource is mandatory and SDK should set the default value if not specified. This attribute is necessary for certain backends to identify the service that produced the spans.
as in [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service):
* service.name
MUST be the same for all instances of horizontally scaled services. If the value was not specified, SDKs MUST fallback to unknown_service: concatenated with process.executable.name, e.g. `unknown_service:bash`. If process.executable.name is not available, the value MUST be set to `unknown_service`.

Set default service.name if missing

---

sdk/include/opentelemetry/sdk/common/atomic_shared_ptr.h
sdk/include/opentelemetry/sdk/logs/logger_provider.h
sdk/include/opentelemetry/sdk/trace/tracer.h
sdk/include/opentelemetry/sdk/trace/tracer_provider.h

Fixes #589 
Slight cleanup, moved `atomic_shared_ptr` into `common` namespace.

move atomic_shared_ptr to sdk common namespace

---

exporters/otlp/CMakeLists.txt

gmock.lib is specified to otlp exporter for linking which cannot be found by linker if it is not in system path. Actually the full path returned by `find_library()` should be used.

Use gmock full path for linking in CMake script

---

exporters/otlp/CMakeLists.txt

@ThomsonTan  - There's a minor regression (build break on Windows) introduced by #630 for Windows-CMake builds:
I found this while rebasing my other PR to latest. We should probably add Windows CMake builds with OTLP testing enabled to the loop (maybe in another PR, this one is just to fix the build break).
- vcpkg-installed GMock on Windows for **Debug** build lives in `gmockd.dll` , so searching for `gmock` is morally wrong... 😄 This is idiosyncrasy of Google Test library itself, that it names the two flavors differently and does not provide an easy-to-use CMake config for that.
- vcpkg-installed GMock on Windows requires `#define GTEST_LINKED_AS_SHARED_LIBRARY 1`

Fix GMock linkage error on Windows

---

RELEASING.md

Related to #636.
Added a small section to remind the maintainers to update the opentelemetry.io docs.

Mention doc update in the release process

---

api/test/context/runtime_context_test.cc

Fixes build issue on 32bit linux builds (no github issue, due to trivial fix)
One-liner, see code, the rest of this template seems irrelevant given how trivial this is, so I've removed it
I was unable to build a 32bit linux build due to the following error:
```
2021/03/31 04:40:14 ERROR bldroot_builddeb(100211): //opt/bb/libexec/build-base/g++ -D_GLIBCXX_USE_CXX11_ABI=0 -march=westmere -m64 -g -O2 -fno-strict-aliasing -fasynchronous-unwind-tables -Wl,--enable-new-dtags -Wl,--gc-sections -Wl,-uplink_timestamp___ -rdynamic CMakeFiles/dynami
c_load_test.dir/dynamic_load_test.cc.o -o dynamic_load_test  -Wl,-rpath,/opt/SUNWspro12/lib/amd64:/opt/SUNWspro12/rtlibs/amd64:/usr/lib64:/lib64:.:/bb/bin/so/64/NS02:/bb/bin/so/64:/bb/bin //opt/bb/lib64/libgtest.a //opt/bb/lib64/libgtest_main.a -lpthread …
```

Fix 32bit build error

---

cmake/opentelemetry-proto.cmake
exporters/otlp/BUILD
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/protobuf_include_prefix.h
exporters/otlp/include/opentelemetry/exporters/otlp/protobuf_include_suffix.h
exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h
exporters/otlp/test/otlp_exporter_test.cc
exporters/otlp/test/recordable_test.cc

Related to #249 
Remove warnings of protobuf. There is no functional change.

Remove warnings of protobuf

---

sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/test/trace/span_data_test.cc

Fixes #657
Although the context was stored, it was not accessible. I've extended
tests to also validate that a valid context has been passed.

Add SpanContext accessor SpanDataLink

---

exporters/ostream/BUILD
exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/ostream/src/span_exporter.cc
exporters/ostream/test/ostream_capture.h
exporters/ostream/test/ostream_span_test.cc

(No Issue, can create if necessary)
*NOTE: This was primarily to help with testing as we look to adopt otel*
Previously these were just ignored. Summary of changes:
- Moved print methods into the translation unit
- Added new print methods for links and events
- Refactored tests
- Added new convenience OStream capture utility
- Restructured tests to focus on stream tests and feature tests
- Added new tests for links and events
---
I've dumped the expected values within their tests to help visualise the formatted changes
```
Running main() from /build/googletest-j5yxiC/googletest-1.10.0/googletest/src/gtest_main.cc
[==========] Running 10 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 10 tests from OStreamSpanExporter
[ RUN      ] …
```

Add Links and Events to OStreamSpanExporter

---

api/include/opentelemetry/context/context.h
api/test/context/context_test.cc

Fixes #670 
- Update `Context::HasKey` to be const
- Add const qualifier in tests for HasKey, GetValue to validate constness

Make `Context::HasKey` const

---

CHANGELOG.md
api/docs/Doxyfile
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/src/version/version.cc

Release 0.4.0
New alpha release 0.4.0

Release for 0.4.0 

---

api/include/opentelemetry/common/kv_properties.h
exporters/ostream/src/span_exporter.cc
exporters/ostream/test/ostream_span_test.cc
exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h
exporters/otlp/src/recordable.cc
exporters/otlp/test/otlp_exporter_benchmark.cc
exporters/otlp/test/recordable_test.cc
exporters/zipkin/include/opentelemetry/exporters/zipkin/recordable.h
exporters/zipkin/src/recordable.cc
exporters/zipkin/test/zipkin_recordable_test.cc
ext/include/opentelemetry/ext/zpages/threadsafe_span_data.h
ext/test/zpages/threadsafe_span_data_test.cc
sdk/include/opentelemetry/sdk/trace/recordable.h
sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/src/trace/span.cc
sdk/test/trace/span_data_test.cc

Fixes #661
- Updated Recordable interface to take a span context and parent span id
rather than just the trace/span ids.
- Updated SpanData to new interface and added new getters for accessing
SpanContext
- Updated ThreadsafeSpanData with the same
- Updated tests for both (and made consistent)
- Updated OStreamSpanExporter to print tracestate and tests

Add SpanContext (and TraceState) to Recordable

---

api/include/opentelemetry/nostd/variant.h

If SDK is compiled with `HAVE_ABSEIL_VARIANT` option, i.e. using Google `absl::variant` implementation instead of MPark Variant, then the code emits a few warnings at "Level 4" if compiled with Visual Studio 2017. These warnings are all benign and do not impact the actual functionality. The fix is to disable / suppress specific warnings for the compilation unit, then restore back to original setting.
Warnings are:
- in Google Abseil - 4245: conversion from int to const unsigned _int64
- in Google Abseil - 4127: conditional expression is constant
- in nostd/variant  - [4211: nonstandard extension used: redefined extern to static](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4211?view=msvc-160)
Last one is emitted because we do not link the …

Disable noisy `nostd::variant` compiler warnings with Visual Studio 2015/2017

---

api/include/opentelemetry/trace/default_span.h
api/include/opentelemetry/trace/span_context_kv_iterable.h

Main motivation for this PR is to resolve ALL compilation warnings in Visual Studio, including (somewhat silly) Level 4 warnings.
API headers contain "interface definition" / Default implementation of `Span`. Plus `NullSpanContext` - empty context. In both cases the methods declare parameters that are not used. This is tripping a (fairly useless) [Level 4 warning](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4100?view=msvc-160) in Visual Studio.
There are two implementation options here:
- comment out parameter names : this may be causing a potential problem for tools like Doxygen. But it's a universal approach that resolves the issue in a compiler-agnostic way. Approach works well even if the same paranoid warning is enabled with gcc or …

Resolve "Level 4" warnings about unused parameter in interface definitions in span API headers

---

api/include/opentelemetry/context/context.h
api/include/opentelemetry/context/runtime_context.h

Two minor warnings clean-up:
- One functional clean-up - build warning: deleting object of polymorphic class which has non-virtual destructor might cause undefined behavior. Adding virtual destructor to resolve it.
- Another warning is purely aesthetic: Cpp Core Guidelines checker in latest Visual Studio 2019 complains that the method should be marked as `noexcept`.

More vs2019 minor warnings cleanup

---

README.md

Trivial change
Added a reference to API and Getting Started doc from opentelemetry-cpp.readthedocs.io

Add reference to getting started doc and api doc

---

exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h

(passing this to lambda does not resolve method names correctly)
this is just a small fix in order to get a build with gcc v5.4.0 with -std=c++14 to work. 
With current implementation I get the following compile error:
```cpp
...include/opentelemetry/exporters/ostream/span_exporter.h:103:39: error: cannot call member function ‘void opentelemetry::v0::exporter::trace::OStreamSpanExporter::print_value(const std::vector<T>&) [with T = std::__cxx11::basic_string<char>]’ without object
```
This solves this issue for me:
```cpp
nostd::visit([this](auto &&arg) { **this->**print_value(arg); }, value);
```
It seems to be an inconsistent behaviour of gcc in this specific version.
Please takeover if you agree with the fix.

compiler error with gcc 5.4.0 fixed 

---

api/docs/Doxyfile
api/include/opentelemetry/common/attribute_value.h
exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
exporters/otlp/src/recordable.cc
exporters/zipkin/src/recordable.cc
sdk/include/opentelemetry/sdk/common/attribute_utils.h

Fixes #634.
This change is based on discussion we recently had (in #634 and in SIG meetings).
This PR purposely tries to keep the scope of `AttributeValue` very wide, as any change to this `variant` will require us to release a new major version, as any change to the `variant` is a breaking API change.
* `std::span<uint8_t>` is included as there's an [open issue](https://github.com/open-telemetry/opentelemetry-specification/issues/780) for adding this, and there's interest from user side to have this.
* `uint64_t` and `std::span<uint64_t>` are added to provide complete support for primitive C++ types.
The documentation adds a warning that those types are not part of the specification and that supports from exporter side is not guaranteed.

Attribute value cleanup

---

sdk/src/resource/resource_detector.cc

Fixes # 655
Replacing `std::getenv` by `getenv_s` for MSVC build to avoid the warning of calling unsafe CRT function.

Fix MSVC build warning by replacing std::getenv by getenv_s

---

api/include/opentelemetry/trace/propagation/b3_propagator.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/propagation/jaeger.h
exporters/ostream/test/ostream_log_test.cc
exporters/otlp/test/otlp_exporter_test.cc
sdk/test/logs/logger_provider_sdk_test.cc

Fixes #703
There are no API changes. Clean-up of the build failures with Visual Studio 2019, C++20 and `WITH_STL` ( `-DHAVE_CPP_STDLIB` ) option. Not a _significant_ contribution. However, we could mention that now the entire SDK can be compiled using vs2019 w/c++latest.

Fixing Visual Studio 2019 with `c++latest` (C++20) and `WITH_STL` build option

---

api/include/opentelemetry/nostd/function_ref.h
api/include/opentelemetry/nostd/span.h
api/include/opentelemetry/std/span.h

There are three fundamental changes here:
- Better detection of compiler features in Visual Studio 2019. For example, you can't just assume that if `<span>` exists, then the feature is available. It is shielded beyond `c++latest` flag, so have to check for that flag too. That way if you build with Visual Studio 2019 IDE and latest headers, but using `c++17` flag - the code would still compile successfully.
- compiler error fix in case if `__cplusplus` has incorrect value. This is long-standing issue, that even [has its own Reddit thread here](https://www.reddit.com/r/cpp/comments/bqsyss/zc_cplusplus_by_default/) ... We solve this in CMake and Bazel builds by defining corresponding build flag (`/Zc:__cplusplus`). But other build systems and libraries may not have that flag set. This …

Visual Studio 2019 fixes for API headers

---

exporters/zipkin/test/zipkin_recordable_test.cc

As the mentioned in [gtest](https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-internal.h#L1305), `TYPED_TEST_CASE` is deprecated and `TYPED_TEST_SUITE` should be used.

Remove deprecated use of TYPED_TEST_CASE

---

exporters/zipkin/src/recordable.cc
exporters/zipkin/test/zipkin_recordable_test.cc

Small fix to populate spankind attribute for Zipkin exporter.
specs : https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md#spankind

Set Spankind for Zipkin exporter

---

exporters/otlp/CMakeLists.txt

`find_library` is used to get the path of gmock, and build type (`CMAKE_BUILD_TYPE`) is checked to link to either gmockd.lib for debug build or gmock.lib for others.
The problem is that `find_library` stores the found library in cache variable which will **NOT** be re-checked for the CMake re-run, so if the re-run changes build type, it will link to the previous gmock, which causes runtime exception, as the OTLP test and gmock then run with 2 different flavors of CRT library, and trigger exception when passing C++ types around, such as `std::string`.

Unset GMOCK_LIB before find_library to force lookup

---

tools/build.cmd
tools/setup-buildtools.cmd

Fixes #701 
This is quite small and simple change to start respecting [`VCPKG_ROOT` variable](https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_root). This fix (partially) addresses the corner-case, when it turns out that the path to gRPC build tree is too long on Windows.
Developers may provide a short path to their own `vcpkg` installation. Such as `set VCPKG_ROOT=c:\vcpkg`, then the `setup-buildtools.cmd` is going to honor that short path. gRPC is then building successfully.
One side-effect is that developer-provided snapshot of `vcpkg` is going to be used in that case instead of opentelemetry submodule-provided version of `vcpkg`.
In my case I'm running an Azure pipeline build, where the project name and, subsequently, the path to project directory …

Allow to build with alternate vcpkg.exe by respecting VCPKG_ROOT variable

---

api/docs/Doxyfile
api/include/opentelemetry/common/key_value_iterable.h

* Remove documentation references for internal `common` classes that are not relevant to users.
* Remove documentation references for `nostd` classes. We shouldn't confuse the users with documentation for those classes, as we must strive for 100% compatibility with the standard library anyway.
* Remove `NullKeyValueIterable`. It isn't used anywhere in the code.
Cleanup of documentation in the `opentelemetry::trace` namespace will come in a separate PR.

Minor api documentation cleanup

---

examples/http/tracer_common.h

In the new http example, the extraction of `TraceState` from `HttpTextMapCarrier` doesn't use the right key. This is not currently expose because we default `TraceState` is used is coincidently displayed as empty string.

Fix extracting TraceState from HttpTextMapCarrier

---

tools/setup-buildtools.cmd

**Minor Developer Experience Improvement**
Minor build infra change would enable to build all exporters with the following workflow.
Run as - Administrator, in `cmd.exe`
```console
cd tools
setup-buildtools.cmd
build.cmd
```
Subsequently the directory may be opened `as directory` in [Visual Studio 2019+CMake](https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-160), to enjoy the benefits of hassle-free build system, built-in test integration, as well as `ninja` (much faster builds).
This time with ALL exporters available to be built in this flow, including Elastic and Zipkin that presently rely on `libcurl` on Windows.

Add curl via vcpkg to Windows builds

---

INSTALL.md

Add option `--recursive` to `git clone` command to out install document, in case the user build any components which require submodule like OTLP proto files, etc.
Some minor cleanup.

Add --recursive git option to install doc

---

sdk/include/opentelemetry/sdk/metrics/async_instruments.h
sdk/include/opentelemetry/sdk/metrics/instrument.h
sdk/include/opentelemetry/sdk/metrics/sync_instruments.h

Metrics SDK class `SynchronousInstrument` has multiple inheritance path from API `Instrument`, but only the SDK `instrument` class contains implementation of the virtual method, so it is safe to ignore C4250 (inherit via dominance) warning here.

Disable MSVC warning C4250 for metrics Instrument

---

ext/src/http/client/curl/CMakeLists.txt

Cleaning up build warning. No code changes.
Fix CMake 3.20+ warning. If you are building with fresh CMake that comes in latest Visual Studio 2019 update, then it complains about filenames in `CMakeLists.txt` not having extensions. This is happening due to [new policy CMP0115 described here](https://cmake.org/cmake/help/git-stage/policy/CMP0115.html) - `Source file extensions must be explicit.`. This logically makes sense when target library name matches that one of a source file name, to clearly disambiguate between the two: what is target name, and what is source file name.

Fix CMake 3.20 warning in curl http client

---

api/docs/Doxyfile

Change includes
- Include  header files from `/include/opentelemetry/baggage` and `/include/opentelemetry/context` subdirectories 
- Remove `/include/opentelemetry/core` subdirectory as it no longer exists.
- Excluding internal classes from context api.
This is how it will look after merge:
https://labhas-opentelemetry-cpp.readthedocs.io/en/latest/index.html
Need to update `Getting Started` doc for extracting and injecting context from/to w3c header as separate PR

update api doxygen conf file

---

exporters/otlp/BUILD
exporters/otlp/CMakeLists.txt
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_recordable.h
exporters/otlp/src/otlp_exporter.cc
exporters/otlp/src/otlp_recordable.cc
exporters/otlp/test/otlp_exporter_benchmark.cc
exporters/otlp/test/otlp_recordable_test.cc

There is `class Recordable` from API, SDK and exporters. Share the same name could cause confuse and hinder extending it with multiple variants in one exporter.

Rename Recordable under OTLP exporter to OtlpRecordable

---

sdk/src/trace/span.cc
sdk/src/trace/span.h
sdk/src/trace/tracer.cc
sdk/test/trace/tracer_test.cc

Fixes #782 
Move span_context creation from sdk::Span to sdk::Tracer, and pass it in sdk::Span constructor. This also allows passing valid trace_id of root span to Sampler, and in accordance with how other languages implement.

fix for sampling root span

---

ci/setup_grpc.sh

grpc repo with submodules has size close to 2GB. Eliminating clone the git history could save the size to ~300MB and also accelerate the clone process significantly.

Clone grpc and submodules with 1 level of git history

---

examples/http/server.cc
examples/http/tracer_common.h

Now that #723 is merged, `GetSpan()` function introduced in that PR can be reused to get the span object from provided context.

Small cleanup in http example to use GetSpan() function.

---

README.md

action-badges.now.sh seems deprecated (see [here](https://github.com/JasonEtco/action-badges)) and doesn't show the build status of this repo (currently `build: unknown` is displayed on the badge https://action-badges.vercel.app/open-telemetry/opentelemetry-cpp). Replace it with the github action badge.

Fix build status icon

---

docs/public/GettingStarted.rst

Added Nested spans and Context Propagation in API Getting started guide.
Here is how it looks like:
https://labhas-opentelemetry-cpp.readthedocs.io/en/latest/GettingStarted.html

Update readthedocs api guide: nested spans and context propagator

---

ci/do_ci.sh

Some CI failures could be hard to be reproduced locally, including race condition. Set `CTEST_OUTPUT_ON_FAILURE` to 1 will ask CTest to output more detail for the failure which will help offline investigation.

Output verbose error for failed unit-test in CI

---

exporters/etw/test/etw_tracer_test.cc

Fixes #783 
Discussed with @maxgolov and confirmed these `sleep_for` calls are not necessary. Remove them could save us 5 seconds when running ETW `TracerCheck` test.

Remove sleep_for in ETW TracerCheck test

---

.github/.codecov.yaml

This is a humble attempt to make our codecov settings more forgiving.
Main motivation for this PR is that our current codecov settings are flaky and trigger A LOT of false-positives.
Practical illustration. See those red marks - false-positives mostly associated with badly tuned codecov settings:
Hopefully the new settings are going to:
- drop the codecov to informational.
- allow some float / slack in the settings.
- devs should still treat the generated report with respect and dignity, and use their best judgement to decide if they need to improve their newly added code code coverage.

Make our codecov settings more forgiving

---

Versioning.md

Update Versioning.md for:
- Clarity on release policy as we would have a single release package containing SDK, API, and all exporters.
- Clarity on versioning, as we have a single version for the entire release. 
- Clarity on ABI compatibility vs ABI breaking across releases.

Versioning doc update

---

CMakeLists.txt
exporters/jaeger/CMakeLists.txt
tools/setup-buildtools.cmd

Can't build `WITH_JAEGER` on Windows via Visual Studio 2019, and/or via `tools/build.cmd`
Changes:
- install Thrift via vcpkg in `setup-buildtools.cmd`
- add Thrift detection logic in the main `CMakeLists.txt`
- respect the path that is auto-detected by vcpkg-installed Thrift : it's 1-level up from what thrift-gen is expecting, i.e. the include dir name contains `thrift/` but the code also includes `thrift/*.h`, so we need to append a dir that's 1-level up to make thrift-gen happy.
These changes allow to build `WITH_JAGER` on Windows.
UNRELATED ISSUE: Thrift is extremely bulky and requires Boost.. takes quite a bit of time to build.

Allow to build `WITH_JAEGER` in Visual Studio 2019 + CMake

---

api/include/opentelemetry/baggage/baggage.h

Fixes #808
Add `#include <cctype>` to make `isdigit`, `isalnum`, etc. available in `baggage.h`.
I also tested against the Abseil-variant branch and confirmed that 1) without this, we still get errors under MSVC2015 and 2) with this, there are no errors.
* (N/A) `CHANGELOG.md` updated for non-trivial changes
* (N/A) Unit tests have been added
* (N/A) Changes in public API reviewed

Add #include <cctype> to baggage.h

---

sdk/src/trace/batch_span_processor.cc

Fixes #826

---

CMakeLists.txt
api/include/opentelemetry/trace/propagation/b3_propagator.h
api/test/nostd/variant_test.cc
examples/grpc/client.cpp
exporters/etw/include/opentelemetry/exporters/etw/etw_traceloggingdynamic.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
exporters/etw/test/etw_perf_test.cc
exporters/etw/test/etw_tracer_test.cc

These are all the changes needed to compile OpenTelemetry C++ SDK with Visual Studio 2015.
I manually tested ad-hoc that the entire SDK works well with all optional component included.
Fixing warnings, errors, and warnings treated as errors.
Fixes #756 
Partially addresses #215 , manually tested ad-hoc. No CI yet. CI loop (scripts, no code changes) will be added in #839
- `CMAKE_VERSION` check was not properly working on very OLD cmake lower than 3.3.
- `b3_propagator.h` triggers an error about narrowing cast of `kTraceIdHexStrLength`. Add explicit static cast to `size_t`.
- `nostd::variant_alternative_t` test does not compile in Visual Studio 2015. I suspect we are missing one of the headers. The rest of it works. And it's a lower priority - since we do not use any comparison of variant …

More fixes to build all with Visual Studio 2015

---

api/include/opentelemetry/std/span.h

This issue is applicable to the following environment:
- build with `WITH_STL` ( `-DHAVE_CPP_STDLIB` )
- build with GSL span implementation available in the build tree ( `-DHAVE_GSL` )
- build with Visual Studio 2017 , `C++14` or `C++17` language standard, i.e. no `C++20` yet.
In that case, a portion of code in ETW exporter uses `nostd::dynamic_extent` here:
https://github.com/open-telemetry/opentelemetry-cpp/blob/3741a8f07256a2ff94ad944fb8cc1075289c9b40/exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h#L83
The issue is that the feature `std::dynamic_extent` is only available in `C++20` - [link](https://en.cppreference.com/w/cpp/container/span/dynamic_extent) , so while the construct works well when we compile with Visual Studio 2019, it fails to compile with older …

Fix dynamic_extent issue when compiling with vs2017 (C++14 or C++17)

---

api/CMakeLists.txt
api/include/opentelemetry/nostd/variant.h
api/test/baggage/CMakeLists.txt
api/test/baggage/propagation/CMakeLists.txt
api/test/common/CMakeLists.txt
api/test/context/CMakeLists.txt
api/test/context/propagation/CMakeLists.txt
api/test/core/CMakeLists.txt
api/test/metrics/CMakeLists.txt
api/test/nostd/CMakeLists.txt
api/test/plugin/CMakeLists.txt
api/test/trace/CMakeLists.txt
api/test/trace/propagation/CMakeLists.txt
examples/batch/CMakeLists.txt
examples/http/CMakeLists.txt
examples/jaeger/CMakeLists.txt
examples/metrics_simple/CMakeLists.txt
examples/otlp/CMakeLists.txt
examples/plugin/load/CMakeLists.txt
examples/plugin/plugin/CMakeLists.txt
sdk/src/common/CMakeLists.txt
sdk/test/common/CMakeLists.txt
sdk/test/instrumentationlibrary/CMakeLists.txt
sdk/test/trace/CMakeLists.txt

Fixes #849
+ Move `CORE_RUNTIME_LIBS` into dependency of `opentelemetry_api`
> I found all targets link `CORE_RUNTIME_LIBS` alse depend `opentelemetry_api`. So I move `CORE_RUNTIME_LIBS` into dependency of `opentelemetry_api` for easier usage.
+ Add alias of `nostd::bad_variant_access` to `absl::bad_variant_access` when have abseil

Fix definitions for `bad_variant_access` and dependencies of some examples.

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/src/otlp_http_exporter.cc
ext/include/opentelemetry/ext/http/common/url_parser.h

Fixes #852
Use `HttpClient` to replace `HttpClientSync` .

Optimize OtlpHttpExporter to support timeout and cancle

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/test/otlp_http_exporter_test.cc
ext/test/http/curl_http_test.cc

Fixes #857 
Added `notify_one` call to `cv_got_events` right after HTTP response processing.

Fix missing notify of conditional variable in OTLP HTTP exporter test

---

api/test/trace/BUILD
api/test/trace/CMakeLists.txt
api/test/trace/span_benchmark.cc

As we are discussing performance changes for the api, it's important to get some numbers for span creation and context management involved in the process. The tests are:
- Test to measure performance for single-span creation
- Test to measure performance for single-span creation with scope ( involves stack )
- Test to measure performance for nested span creation with scope 
- Test to measure performance for nested span creation with manual span context management (no stack involved)
- Test to measure performance for nested span creation with context propagation
These are the numbers as tested locally:
```
------------------------------------------------------------------------------------------
Benchmark                                                Time             CPU   Iterations …
```

Perf benchmark tests for span creation ( along with context management )

---

exporters/jaeger/src/recordable.cc
exporters/jaeger/test/jaeger_recordable_test.cc

Fixes #768 
Adding instrumentation library (name and version) in jaeger span as tags using thrift add tags.
* Unit tests have been added

reporing instumentation library as tags in jaeger span

---

api/test/baggage/BUILD
api/test/baggage/CMakeLists.txt
api/test/baggage/baggage_benchmark.cc

Fixes #837 
Add performance benchmark tests for Baggage. This would be important to evaluate the performance of the internal key-value data structure used for `Baggage` and `TraceState`.
Tests are using
- 10 key-value pair entries in baggage ( Optimal scenario used most of the time).
- 180 key-value pair entries in baggage ( Max possible entries).
with decently sized keys and values.
The result from running locally:
```
CPU Caches:
L1 Data 32K (x4)
L1 Instruction 32K (x4)
L2 Unified 256K (x4)
L3 Unified 8192K (x1)
Load Average: 0.38, 0.44, 0.35
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
---------------------------------------------------------------------------- …
```

Adding Baggage api benchmark tests

---

api/include/opentelemetry/common/string_util.h
exporters/jaeger/src/recordable.cc
exporters/zipkin/src/recordable.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h
sdk/include/opentelemetry/sdk/resource/semantic_conventions_old.h
sdk/src/resource/resource.cc
sdk/test/resource/resource_test.cc

This PR adds semantics as defined here:
https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions
This will let us use uniform attributes/events/exceptions names across services.

Adding semantic-convention attributes for resources

---

exporters/jaeger/include/opentelemetry/exporters/jaeger/recordable.h
exporters/jaeger/src/recordable.cc
exporters/jaeger/test/jaeger_recordable_test.cc

Fixes #875 
On some platforms, bswap_64 is a macro. Rename the OpenTelemetry utility to otel_bswap_64 to avoid clashing with this.
* N/A `CHANGELOG.md` updated for non-trivial changes
* N/A Unit tests have been added
I believe this isn't part of the public API?

Rename bswap_64 to otel_bswap_64 to avoid clash with macro (#875)

---

exporters/otlp/CMakeLists.txt

nlohmann_json::nlohmann_json added as target_lik_library for the opentelemetry_exporter_otlp_http
Fixes build error for the case WITH_OTLP=ON as exporters/otlp/src/otlp_http_exporter.cc directly includes nlohmann/json.hpp
This does not work if library is not added to the target.

nlohmann_json::nlohmann_json added

---

CONTRIBUTING.md

We updated Zoom meeting in README in https://github.com/open-telemetry/opentelemetry-cpp/pull/887, but we also have the same link in contributing doc which needs to be fixed as well. Instead, this PR removes the duplicated link in the contributing doc.

Remove meeting link in contributing doc

---

exporters/otlp/src/otlp_recordable.cc

We assert on `AttirbuteValue` while we are using `OwnedAttributeValue` in [PopulateAttribute](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/src/otlp_recordable.cc#L141) from OTLP exporter.

Fix assertion to check the correct attribute value type

---

bazel/curl.BUILD
examples/http/BUILD
exporters/elasticsearch/BUILD
ext/src/http/client/curl/BUILD
ext/test/w3c_tracecontext_test/BUILD

Fixes #892 
Links some system libraries into curl, just like https://github.com/jupp0r/prometheus-cpp/blob/master/bazel/curl.BUILD .

Fix issue 892

---

exporters/jaeger/include/opentelemetry/exporters/jaeger/recordable.h
exporters/jaeger/src/recordable.cc
exporters/jaeger/src/thrift_sender.cc
exporters/jaeger/test/jaeger_recordable_test.cc

Fixes #767
Current only `service.name` is set to Jaeger span, this PR populates all other resources attributes into tags in Jaeger process object.

Populate resource attributes into process tags in Jaeger

---

exporters/zipkin/include/opentelemetry/exporters/zipkin/recordable.h

The following method is marked override but it doesn't override:
`exporter::zipkin::Recordable::SetStatus(trace::StatusCode code, nostd::string_view description) noexcept override;`
compile error:
```
In file included from <path>/include/opentelemetry/exporters/zipkin/zipkin_exporter.h:6,
from /opt/otel/main.cc:11:
<path>/include/opentelemetry/exporters/zipkin/recordable.h:43:25: error: 'opentelemetry::v0::exporter::trace::StatusCode' has not been declared
43 |   void SetStatus(trace::StatusCode code, nostd::string_view description) noexcept override;
|                         ^~~~~~~~~~
<path>/include/opentelemetry/exporters/zipkin/recordable.h:43:8: error: 'void opentelemetry::v0::exporter::zipkin::Recordable::SetStatus(int, opentelemetry::v0::nostd::string_view)' marked …
```

🐛 fix zipkin exporter compile failure

---

examples/jaeger/BUILD
examples/jaeger/foo_library/foo_library.cc
exporters/jaeger/README.md

Fix the Jaeger example code to make it buildable after copy/paste.
The current example has issue to build as mentioned in https://github.com/open-telemetry/opentelemetry-cpp/issues/901.

Fixes missing namespace in Jaeger exporter config doc

---

exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/ostream/src/span_exporter.cc
exporters/ostream/test/ostream_span_test.cc
sdk/include/opentelemetry/sdk/trace/span_data.h

OStreamSpanExporter span exporter doesn't export resources and instrumentation library. This makes it difficult to debug issues related to resources/instrumentation library. This PR adds support for it. 

Add resource and instrumentation library support for OStreamSpanExporter

---

WORKSPACE
examples/grpc/BUILD
examples/grpc/client.cpp
examples/grpc/server.cpp

https://github.com/open-telemetry/opentelemetry-cpp/issues/838#issue-915238543
Add `bazel` build support to build `gRPC` example.

✨ add bazel build for grpc example

---

exporters/jaeger/include/opentelemetry/exporters/jaeger/recordable.h
exporters/jaeger/src/jaeger_exporter.cc
exporters/jaeger/src/recordable.cc
exporters/jaeger/src/sender.h
exporters/jaeger/src/thrift_sender.cc
exporters/jaeger/src/thrift_sender.h
exporters/jaeger/test/jaeger_recordable_test.cc

Fixes #735
The Recordable applies to Jaeger exporter. The concrete protocols are abstracted to the `ThriftSender`, so no need to include the protocol name here.

Rename Recordable to JaegerRecordable in Jaeger exporter

---

CHANGELOG.md
CMakeLists.txt

Fixes # 914
Allow to us elocal GSL.
Maybe need more discussion about using [gsl-lite](https://github.com/gsl-lite/gsl-lite) for old compilers?

Allow to use local GSL

---

exporters/jaeger/CMakeLists.txt
opentelemetry-cpp-config.cmake.in

I believe it was introduced in https://github.com/open-telemetry/opentelemetry-cpp/pull/918
When doing `make install` the generated `opentelemetry-cpp-config.cmake` was trying to find a non-existent target, thus the `OPENTELEMETRY_CPP_LIBRARIES` variable did not have Jaeger exporter set.

Fix exporting of Jaeger exporter target name

---

exporters/elasticsearch/CMakeLists.txt
exporters/jaeger/CMakeLists.txt
exporters/otlp/CMakeLists.txt
exporters/zipkin/CMakeLists.txt
exporters/zipkin/include/opentelemetry/exporters/zipkin/recordable.h
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h

As discussed here ( https://github.com/open-telemetry/opentelemetry-cpp/discussions/922#discussioncomment-1045351 ), exporter specific recordable.h shouldn't be included in the exporter's install targets. This header shouldn't be used by application developers. So this PR excludes this header from the exporter's install rule.

remove recordable header from CMake install rules for exporters

---

sdk/test/common/circular_buffer_test.cc

Fixes #841
This is long existing bug which fails our CI run intermittently. The original intention is that the consumer thread checks whether the `exit` flag is true, then checks the share buffer with producer thread and makes sure it is empty before exit, but the problem is it checks a cached peek result on the buffer which was generated before checking the `exit` flag, so when the consumer thread gets `exit` signal, it can only make sure the old stale snapshot of buffer is empty, not the buffer in real-time, and finally leads to early exit of the consumer thread if there is actually some data in the buffer.
It is very hard to repro this issue in local devbox even with many repeated runs, but it could be reproduced easily with some artificial sleep injected between taking snapshot of …

Fix race condition in circular buffer simulation test

---

exporters/otlp/test/otlp_grpc_exporter_test.cc

Fixes compilation warning C4996.
> ..\exporters\otlp\test\otlp_grpc_exporter_test.cc(139): warning C4996: 'putenv': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _putenv. See online help for details.
Replace `putenv` by ISO conformant name `_putenv`.

Fix warning of deprecation of putenv for MSVC

---

api/include/opentelemetry/context/runtime_context.h

Fix for Stack::Resize that new_capacity is not assigned to capacity_ , caused stack to constantly allocate memory when size_>0.

🐛 Fix for Stack::Resize that new_capacity is not assigned to capacity_

---

api/include/opentelemetry/trace/tracer.h

std::chrono::duration can be converted to integral value via count() function

Fix casting to microseconds

---

exporters/otlp/README.md
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h

The default OTLP over HTTP port was changed from `4317` to `4318`. Update our exporter to comply with the spec.
https://github.com/open-telemetry/opentelemetry-specification/pull/1839

Update default OTLP http port

---

exporters/zipkin/src/recordable.cc
exporters/zipkin/test/zipkin_recordable_test.cc

The root Span is not displayed in SignalFX (Splunk APM) when data is exported via Zipkin exporter.
According to https://zipkin.io/zipkin-api/#/ (ListOfSpans seection) the **parentId** element should be absent for root span
added logic into Zipkin's recordable implementation to add parentId element only when parentId is valid.

Not set parentId in case parentId is empty

---

exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
exporters/zipkin/src/zipkin_exporter.cc

add possibility to provide custom http headers via Zipkin options. 
http headers are useful for custom authentication mechanism into collector

extend zipkin exporter with ability to provide headers

---

CMakeLists.txt

We have dependency on cURL which dpendes on zlib. The latest vcpkg port of zlib introduced `ZLIB_ROOT` in [this PR](https://github.com/microsoft/vcpkg/pull/18914). The default policy of CMake 3.12 and above is warning on the user of this variable and ignore it. This PR asks CMake to follow the new behavior and honor `ZLIB_ROOT` accordingly.

Enable CMake to search the new package variable <PackageName>_ROOT

---

sdk/include/opentelemetry/sdk/common/env_variables.h

When `NO_GETENV` is used, it is unnecessary to define a pointer to save the result as it is always `nullptr`.

Cleanup GetEnvironmentVariable and remove unused variable under NO_GETENV

---

CMakeLists.txt

If opentelemetry is configured with WITH_STL option enabled but target project uses C++17 standard - build fails since <span> header can't be found.

Do not override CMAKE_CXX_STANDARD

---

CHANGELOG.md
exporters/otlp/BUILD
exporters/otlp/README.md
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/src/otlp_grpc_exporter.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/test/otlp_grpc_exporter_test.cc
exporters/otlp/test/otlp_http_exporter_test.cc

Fixes #978 
Fixes #909 
1. Add `otlp_environment.h` to maintain shared codes of `OtlpGrpcExporter` and `OtlpHttpExporter`
2. Add `timeout` and `metadata` options for `OtlpGrpcExporter`
3. Use environment variables `OTEL_EXPORTER_OTLP_TIMEOUT` , `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT` , `OTEL_EXPORTER_OTLP_HEADERS` , `OTEL_EXPORTER_OTLP_TRACES_HEADERS` to initialize default options of `OtlpGrpcExporter` and `OtlpHttpExporter`
4. Use environment variables `OTEL_EXPORTER_OTLP_ENDPOINT` , `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` to initialize default options of `OtlpHttpExporter`

Support environment variables for both `OtlpGrpcExporter` and `OtlpHttpExporter`

---

bazel/repository.bzl

Our OpenTelemetry-proto submodule was updated to 0.9.0 in https://github.com/open-telemetry/opentelemetry-cpp/pull/825, update bazel build script to consume the same version of OpenTelemetry-proto for consistency.

Update opentelemetry-proto for bazel build to 0.9.0

---

CHANGELOG.md
api/include/opentelemetry/common/kv_properties.h

Fixes #985 
Add include statement of _cstring_ to opentelemetry-cpp/api/include/opentelemetry/common/kv_properties.h which caused build error for missing _memcpy_ in scope.

Idar oss/build error memcpy

---

exporters/otlp/test/otlp_http_exporter_test.cc

`putenv` is deprecated in MSVC, replace it by `_putenv`.

Fix deprecated usage of putenv for MSVC

---

README.md

Add further clarification that gcc 4.8 cannot build gRPC 1.38 and above.

Clarify gRPC cannot be built with gcc 4.8 in README

---

api/include/opentelemetry/logs/logger.h
sdk/include/opentelemetry/sdk/logs/logger.h

This is to add the `Logger: Log()` method for the below use-case:
```cpp
Properties attribs = {{"attrib1", 1}, {"attrib2", 2}};
logger.log(severity, name, attribs);
```
where `Properties` class implements `common::KeyValueIterable`.
Similar method is supported by `Traccer::StartSpan()`:
https://github.com/open-telemetry/opentelemetry-cpp/blob/21a441e2be80ca335a7d6abd033af2f1cdf477ab/api/include/opentelemetry/trace/tracer.h#L60-L65
Also, a minor change to use full `tracer` namespace in logger sdk, in order to avoid including unnecessary tracer headers for logger instrumentation.

Adding new Logger:log() method

---

exporters/etw/CMakeLists.txt
exporters/etw/include/opentelemetry/exporters/etw/etw_config.h
exporters/etw/include/opentelemetry/exporters/etw/etw_fields.h
exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
exporters/etw/include/opentelemetry/exporters/etw/etw_logger_exporter.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer_exporter.h
exporters/etw/test/etw_logger_test.cc
exporters/etw/test/etw_perf_test.cc

This PR adds ETW Log exporter using the current preview Logger API. 

ETW Log Exporter

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
exporters/otlp/src/otlp_grpc_exporter.cc
exporters/otlp/test/otlp_grpc_exporter_test.cc

according to the exporter [specifications](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-2), export after shutdown should fail

otlp_grpc_exporter export after shutdown should fail

---

api/include/opentelemetry/trace/propagation/http_trace_context.h

fix: redefinition

---

INSTALL.md

As there are otel-cpp ports made available for `vcpkg` and `conan` from outside this project, it is worth adding them in a separate section in the INSTALL document, with a note that these are not official packages. We can monitor them and remove them in the future if there are no regular updates to them for new otel-cpp releases.

List otel-cpp ports for conan and vcpkg

---

ci/README.md
ci/do_ci.sh
third_party_release

Related to #1051 (issue)
checkout opentelemetry-proto v0.11.0 and store the third_party release tags in a file

checkout opentelemetry-proto v0.11.0

---

.github/workflows/stale.yml

Based on the discussion in our community meeting, adding bot to detect stale issues and PRs will help us track progress.

Add action to mark and close stale issues after timeout

---

exporters/zipkin/CMakeLists.txt

`http_client_curl` is required to build Zipkin exporter. It is better to report error when running CMake files if cURL is not found for Zipkin, or it will be surfaced as link error during later linking stage.

Mark cURL as required dependence for building Zipkin exporter

---

.github/workflows/stale.yml

It seems `days-before-stale` and `days-before-close` apply to both issues and PRs, even without the message specified. This PR use the more concrete property `days-before-issue-stale` and `days-before-issue-close` to get the expected behavior we agreed.

Remove stale bot to operate on PRs

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_exporter.h
exporters/otlp/src/otlp_grpc_log_exporter.cc
exporters/otlp/test/otlp_grpc_log_exporter_test.cc

according to the exporter [specifications](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-2), export after shutdown should fail
Also fixes compiler warning

otlp gRPC log export should fail after shutdown

---

api/include/opentelemetry/trace/span_id.h

Improvement: span_id should not break strict aliasing.

---

exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_exporter_test.cc

Fixes #1049
Increase timeout for `OtlpHttpExporterTestPeer` and `OtlpHttpLogExporterTestPeer` .

Fix timeout of `OtlpHttpExporterTestPeer` and `OtlpHttpLogExporterTestPeer` when run under valgrind.

---

README.md

Removes Zoom link and points viewers to the calendar

Remove hardcoded Zoom link

---

bazel/otel_cc_benchmark.bzl
examples/batch/BUILD
examples/grpc/BUILD
examples/http/BUILD
examples/metrics_simple/BUILD
examples/multi_processor/BUILD
examples/multithreaded/BUILD
examples/otlp/BUILD
examples/simple/BUILD
exporters/elasticsearch/BUILD
exporters/etw/BUILD
exporters/memory/BUILD
exporters/ostream/BUILD
exporters/otlp/BUILD
exporters/prometheus/BUILD
exporters/zipkin/BUILD

Fixes #1072 (issue)
mark tags to bazel targets.
can exclude targets e.g.
`bazel build //... --build_tag_filters=-otlp,-es,-etw,-prometheus,-zipkin`

Mark tags to bazel targets

---

cmake/opentelemetry-cpp-config.cmake.in
exporters/prometheus/CMakeLists.txt

Fixes #1096 
Remove missing target and fix document for exported config file.

Remove missing target in legacy prometheus

---

exporters/memory/BUILD

Fixes in memory exporter test bazel
Adds the missing `src` files in the `cc_test` rules of in memory exporter.

fix in memory exporter test bazel

---

CHANGELOG.md
exporters/otlp/src/otlp_recordable.cc
exporters/otlp/test/otlp_recordable_test.cc

Fix otlp generates null span ids

---

exporters/jaeger/src/thrift_sender.cc
exporters/jaeger/src/udp_transport.cc

Fixes #1103 (issue)
adds missing buffer size in allocations.
adds a log message when `ThriftSender::Append()` fails because of the size of the span

Jaeger exporter: spans over 512 bytes

---

INSTALL.md

Fixes #1108 (issue)
Adds dependencies to INSTALL.md.

Document dependencies

---

ci/run_docker.sh

Fixes file permission change after using `./ci/run_docker.sh tools/format.sh `
by running the container with the current user id and group id we can avoid file permission change after running the script.

run_docker user

---

exporters/otlp/src/otlp_http_client.cc

Fixes #1132 (issue)
Use proper [overload](https://github.com/protocolbuffers/protobuf/blob/29b3d01572d50c0e5bc0ab2eea32f9779c7576f4/src/google/protobuf/stubs/strutil.h#L854).

Otlp http cmake build fail

---

INSTALL.md
exporters/otlp/src/otlp_http_client.cc

This PR is to propose the changes in instructions for building with bazel and adding the note to not to have GoogleTest installed.
Bazel will download, build and install gtest version from [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/5e258b0c0c192620fe3410b9e56c7480fa278a82/bazel/repository.bzl#L27) and it will fail if it gets different gtest headers from system defined path.
Please feel free to add review comments.

Improve the instructions for Bazel build.

---

api/include/opentelemetry/nostd/absl/meta/type_traits.h

C++20 not Building with VS2019

---

exporters/etw/BUILD

Fixes etw logger bazel
Adds etw logger bazel.

etw logger test bazel

---

exporters/jaeger/include/opentelemetry/exporters/jaeger/jaeger_exporter.h
exporters/jaeger/src/jaeger_exporter.cc

Fixes Jaeger exporter shutdown
Jaeger exporter shutdown should set shutdown before return

Jaeger exporter shutdown

---

INSTALL.md

This PR is to add prerequisite in the installation steps for Cmake build. It was missing in the documentation earlier which leads to the error as shown in attachment below

Adding prerequisite to the installation steps for Cmake build [new PR]

---

exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
exporters/zipkin/src/zipkin_exporter.cc

Fixes ZipkinExporter shutdown
ZipkinExporter shutdown should set shutdown before return

ZipkinExporter shutdown

---

exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_exporter.h

Fixes `InMemorySpanExporter` shutdown
The `::export()` stops exporting when the exporter was shutdown. 

InMemorySpanExporter shutdown

---

exporters/otlp/src/otlp_http_client.cc

Fixes #1141
fix deadlock when notify_all() called before wait().

fix: otlp http exporter block thread (#1141)

---

exporters/jaeger/src/thrift_sender.cc

During our introduction of Jaeger and using the `JaegerExporter` we found this memory leak.
There is currently no unittest for the `JaegerExporter` in opentelemetry-cpp that could have caught this, but maybe we should add something similar to the ongoing `ZipkinExporter` test (#1155)?
The jaeger_span was never destroyed after its release from the JaegerRecordable.
This change let a `std::unique_ptr` handle the destruction when going out of scope, first allowing the`thrift::Span` to be copied to the `span_buffer_`.

Fix leak in Jaeger exporter

---

exporters/jaeger/BUILD
exporters/jaeger/CMakeLists.txt
exporters/jaeger/test/jaeger_exporter_test.cc

Adds unit test to cover the memory leak issue reported in #1160
Mocks `Transport` so that we can reach `ThriftSender::Append` when `JaegerExporter::Export` was called.

Jaeger: ThriftSender unit test

---

CMakeLists.txt
cmake/opentelemetry-proto.cmake
cmake/proto-options-patch.cmake
examples/grpc/CMakeLists.txt

Fixes #1130
Using system installed grpc,curl,protobuf to enable otlp exporters by default

Using system installed grpc,curl,protobuf to enable otlp exporters by default

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_exporter.h
exporters/elasticsearch/src/es_log_exporter.cc
exporters/jaeger/include/opentelemetry/exporters/jaeger/jaeger_exporter.h
exporters/jaeger/src/jaeger_exporter.cc
exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/log_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/ostream/src/log_exporter.cc
exporters/ostream/src/span_exporter.cc
exporters/ostream/test/ostream_log_test.cc
exporters/ostream/test/ostream_span_test.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/src/otlp_grpc_exporter.cc
exporters/otlp/src/otlp_grpc_log_exporter.cc
exporters/otlp/src/otlp_http_client.cc
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
exporters/zipkin/src/zipkin_exporter.cc

Fixes #1158 (issue)
Protects `is_shutdown_` read and writes using `opentelemetry::common::SpinLockMutex`.

Synchronized calls to Exporter::Export & Shutdown

---

exporters/zipkin/BUILD
exporters/zipkin/CMakeLists.txt
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
exporters/zipkin/src/zipkin_exporter.cc
exporters/zipkin/test/zipkin_exporter_test.cc

Fixes #1143 (issue)
Add unit tests for ZipkinExporter.

ZipkinExporter unit-tests

---

exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_exporter_test.cc
exporters/zipkin/test/zipkin_exporter_test.cc
ext/test/http/curl_http_test.cc

Fixes #1049
Increase timeout for http client. We find 8s is not enough sometime.
> https://github.com/open-telemetry/opentelemetry-cpp/runs/4793495501

Waiting a longer time when run unit tests of http client, which may take a long time when run under valgrind.

---

.github/workflows/ci.yml
.gitignore
api/include/opentelemetry/common/spin_lock_mutex.h
exporters/jaeger/CMakeLists.txt
exporters/jaeger/test/jaeger_exporter_test.cc
exporters/zipkin/CMakeLists.txt
exporters/zipkin/test/zipkin_exporter_test.cc
ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

Zipkin exporter doesn't build on Windows but Jaeger exporter builds fine. This PR ports the necessary Jaeger build scripts to Zipkin exporter as well.

Fix build test of Zipkin exporter on Windows

---

.github/workflows/benchmark.yml
bazel/otel_cc_benchmark.bzl
ci/do_ci.sh
exporters/otlp/BUILD
exporters/otlp/test/otlp_grpc_exporter_benchmark.cc

Fixes #1170 (issue)
Runs  benchmark tests at every push to the `main` branch and pushes the results to `gh-pages` branch. The results are grouped into api, sdk and exporters.
An example of working graphs can be seen [here](https://esigo.github.io/opentelemetry-cpp/benchmarks/index.html).

Continuous benchmark tests as part of the CI

---

ci/do_ci.sh
exporters/ostream/test/ostream_log_test.cc

related to #1187 (issue)
enables metrics and logs for Mac ci also disables failing log test in ostream_log.
To prevent introducing new issues on metrics and logs for Mac I think it makes sense to enable both for Mac and temporarily disable the failing test until we have a fix for it.

Mac CI metric and logs

---

docs/public/sdk/GettingStarted.rst

Fixes #1199 (issue)
fix errors in SDK documentation for trace provider, resource_attributes and samplers.

fix errors in SDK documentation

---

README.md

As agreed in the last couple of community meetings, we are changing Monday's community meeting time to 13:00 PT - 14:00 PT. This will allow members from the European region to join the meeting.
Google calendar is updated too.

Change Monday's community meeting time (13:00 PT - 14:00 PT)

---

docs/performance/benchmarks.rst
docs/public/index.rst

This PR adds the [result of benchmarks](https://open-telemetry.github.io/opentelemetry-cpp/benchmarks/index.html) to the documentation under the performance section.

Benchmark documentation

---

exporters/ostream/test/ostream_log_test.cc

Fixes #1187 (issue)
The issue is because of `std::unordered_map` that is used for [printing](https://github.com/open-telemetry/opentelemetry-cpp/blob/e89e5b3dd65b0e73435c12b9fdeb54f9420f4bb4/exporters/ostream/src/log_exporter.cc#L80) resource attributes. The order in printing is not guaranteed. In this PR the key-value pairs are tested one-by-one.

fix ostream_log_test Mac

---

bazel/repository.bzl
ci/do_ci.sh
ci/setup_grpc.sh
third_party_release

Fixes #1206
Upgrade grpc to v1.43.2

Update grpc to v1.43.2 to support VS2022/MSVC 19.30 and bazel 5.0

---

ci/setup_thrift.sh

No need to install  libboost-all-dev for CI
This should also fix CI bazel build failures happening [recently]( libboost-all-dev install from the CI).
We need `boost locale` only for building thrift. This PR installs boost locale and removes `libboost-all-dev` install from the CI.

thrift boost deps

---

ci/setup_thrift.sh

The current apt cache could be stale when running `setup_thrift.sh`, so update the cache before installing any dependency.
Fixes build error like https://github.com/open-telemetry/opentelemetry-cpp/runs/5255793986?check_suite_focus=true.

Run apt update before install thrift dependencies

---

api/include/opentelemetry/context/runtime_context.h

Fixes #1211 (issue)
The specifications require the context to be [immutable](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/context.md#overview), but does not talk about whether the users are allowed to have access to the storage.
The change in this PR allows the users to get a shared_ptr to const so they can't do anything with the pointer but extending the lifetime of the storage.

allow extension of the lifetime of ContextStorage.

---

docker/Dockerfile.centos

Adds Centos image
There have been some issues reported with e.g. building opentelemetry in Centos. This PR adds a Dockerfile with Centos  as base, which builds opentelemetry  and its dependencies using `devtoolset-11` . We can use this image for reproducing issues if any reported. 

centos image

---

bazel/repository.bzl
third_party_release

Fixes: I didn't file an issue, but the bazel build seems to fail w/o this PR because of an error building prometheus-cpp
```
ERROR: /usr/local/google/home/jgm/.cache/bazel/_bazel_jgm/2be8259a0f7f7767cb8723c5dffd593f/external/com_github_jupp0r_prometheus_cpp/core/BUILD.bazel:9:11: Compiling core/src/histogram.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 19 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_jupp0r_prometheus_cpp/core/src/histogram.cc: In member function 'prometheus::ClientMetric prometheus::Histogram::Collect() const': …
```

chore: update prometheus to 1.0 version

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_recordable.h
exporters/ostream/src/log_exporter.cc
exporters/otlp/src/otlp_grpc_exporter.cc
exporters/otlp/src/otlp_grpc_log_exporter.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/src/otlp_http_log_exporter.cc
exporters/otlp/test/otlp_http_log_exporter_test.cc
ext/test/http/curl_http_test.cc
sdk/include/opentelemetry/sdk/_metrics/controller.h
sdk/include/opentelemetry/sdk/logs/batch_log_processor.h
sdk/include/opentelemetry/sdk/logs/logger.h
sdk/include/opentelemetry/sdk/logs/logger_provider.h
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/include/opentelemetry/sdk/trace/tracer_provider.h
sdk/src/logs/batch_log_processor.cc
sdk/src/logs/logger.cc
sdk/src/logs/logger_provider.cc
sdk/src/logs/multi_log_processor.cc
sdk/src/logs/simple_log_processor.cc
sdk/src/trace/batch_span_processor.cc
sdk/src/trace/tracer_provider.cc
sdk/test/logs/batch_log_processor_test.cc
sdk/test/logs/logger_provider_sdk_test.cc
sdk/test/logs/simple_log_processor_test.cc
sdk/test/trace/batch_span_processor_test.cc
sdk/test/trace/tracer_provider_test.cc

…r. It's safe to shutdown multiple times.(Fix #1244)
Fixes #1244 
1. Reorder the destructor of members in LoggerProvider and TracerProvider.
2. It's safe to shutdown multiple times.

Reorder the destructor of members in LoggerProvider and TracerProvider

---

CHANGELOG.md
exporters/jaeger/include/opentelemetry/exporters/jaeger/recordable.h
exporters/jaeger/src/recordable.cc
exporters/jaeger/src/thrift_sender.cc
exporters/jaeger/test/jaeger_recordable_test.cc

~~Fixes # (issue)~~ (no existing issue found)
Add support for span links to Jaeger export.
* ~~[ ] Changes in public API reviewed~~ (no API changes)

Add support for span links to Jaeger export.

---

ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

Fixes #1258
Support OtlpHttpExporter's timeout less than 1s.

fix: use CURLOPT_TIMEOUT_MS to config OtlpHttpExporter's timeout instead of CURLOPT_TIMEOUT

---

sdk/include/opentelemetry/sdk/metrics/view/attributes_processor.h

Fixes AttributesProcessor dtor
Adds AttributesProcessor missing virtual dtor.

AttributesProcessor dtor

---

.gitignore
sdk/include/opentelemetry/sdk/metrics/state/metric_storage.h

Adds missing MetricStorage virtual dtors
Also adds clangd cache to gitignore.

MetricStorage dtors

---

CHANGELOG.md
api/include/opentelemetry/common/timestamp.h
exporters/ostream/src/log_exporter.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_exporter.h
exporters/otlp/src/otlp_http_client.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/src/otlp_http_log_exporter.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_exporter_test.cc
ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
ext/include/opentelemetry/ext/http/client/nosend/http_client_nosend.h
sdk/include/opentelemetry/sdk/logs/batch_log_processor.h
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/src/logs/batch_log_processor.cc
sdk/src/trace/batch_span_processor.cc

Move from #1209 
+ Allow multiple running http sessions in `OtlpHttpClient`
+ Add `concurrency_sessions` to control the max concurrency http sessions.

Cocurrency otlp http session

---

README.md

As discussed in the community meeting, and separately with @owent
@owent has been actively contributing to OpenTelemetry C++ across many modules as well as focusing on performance improvements of SDK.
Some of the PRs @owent has authored:
* #1274 
* #1245
* #1172 
* #1082 
* #1026 
* #983 
* #915 
* #810 
Some of the PRs @owent has reviewed:
* #974 
* #858 
* #771 
* #1252 

 Add owent as an Approver

---

.github/.codecov.yaml

Annotate pull request with coverage data could distract code review process on web UI, disable it for now. We'll need triage coverage data separately.

Don't show coverage annotation for pull requests

---

.github/workflows/stale.yml

`do-not-stale` was incorrectly applied to PR instead of issue which forced some issue to be staled like https://github.com/open-telemetry/opentelemetry-cpp/issues/1027.

Exempt should be applied on issue instead of PR

---

CMakeLists.txt
api/CMakeLists.txt

Fixes #1311 
Move definitions to `opentelemetry_api` and set them as `INTERFACE` definitions.

Move public definitions to `opentelemetry_api`.

---

exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
exporters/etw/test/etw_provider_test.cc

Fixes:
ETW provider `handle` is not cleaned-up properly when ETW logger is destroyed. While the handle is deregistered, it is not removed properly from the list of active providers ( because deletion is done wrongly on the copy of the provider map). The provider map gets corrupted and results in event loss if the logger with the same name is created again.
Tiny one character change to ensure deletion of provider handle happens through the reference of the provider list, and not from the copy. 

[ETW Exporter] - ETW provider handle cleanup

---

examples/common/metrics_foo_library/BUILD
examples/common/metrics_foo_library/foo_library.cc
examples/common/metrics_foo_library/foo_library.h
examples/metrics_simple/BUILD
examples/metrics_simple/metrics_ostream.cc
exporters/ostream/BUILD
exporters/ostream/include/opentelemetry/exporters/ostream/metric_exporter.h
exporters/ostream/src/metric_exporter.cc
exporters/ostream/test/ostream_metric_test.cc
sdk/include/opentelemetry/sdk/metrics/metric_exporter.h
sdk/include/opentelemetry/sdk/metrics/view/instrument_selector.h

related to #1092 (issue)
For testing end-end metrics
Adds ostream metrics example and fixes Export().

ostream metrics example

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Prepare v1.3.0 release

---

api/include/opentelemetry/common/spin_lock_mutex.h
api/test/common/spinlock_benchmark.cc

Currently for ARM processor, we are using `__yield` intrinsic to yield processor while waiting in tight spin lock loop. This intrinsic is defined as part of ARM C Language Extension, and its implementation is not provided in GCC library. Being part of the language extension, the ARM Vendor may choose not to implement this intrinsic as part of its compiler toolchain. More details here: https://stackoverflow.com/questions/70069855/is-there-a-yield-intrinsic-on-arm. The otel-cpp build in that case fails with error:
```
/opentelemetry-cpp/api/include/opentelemetry/common/spin_lock_mutex.h: In member function ‘void opentelemetry::v1::common::SpinLockMutex::lock()’:
/opentelemetry-cpp/api/include/opentelemetry/common/spin_lock_mutex.h:105:9: error: ‘__yield’ was not declared in this scope
105 | …
```

Update yield logic for ARM processor

---

tools/build.cmd

Fixes #1292
This fix just wrap %NINJA% with quotes to be able to call ninja binary when it is located in a path with spaces

Fix for #1292

---

sdk/include/opentelemetry/sdk/metrics/view/attributes_processor.h
sdk/src/metrics/meter.cc
sdk/test/metrics/attributes_hashmap_benchmark.cc
sdk/test/metrics/attributes_hashmap_test.cc

Fixes metrics compiler warnings

fix metrics compiler warnings

---

sdk/test/metrics/sync_metric_storage_test.cc

`INSTANTIATE_TEST_CASE_P` is deprecated in googletest, instead, `INSTANTIATE_TEST_SUITE_P` should be used.
https://github.com/google/googletest/blob/80600e56cc9afe7ee02737429f9177aa87025054/googletest/include/gtest/internal/gtest-internal.h#L1302

Replace deprecated googletest API

---

exporters/elasticsearch/CMakeLists.txt
exporters/etw/CMakeLists.txt
exporters/jaeger/CMakeLists.txt
exporters/memory/CMakeLists.txt
exporters/ostream/CMakeLists.txt
exporters/otlp/CMakeLists.txt
exporters/prometheus/CMakeLists.txt
exporters/zipkin/CMakeLists.txt
sdk/CMakeLists.txt

Remove the redundant `/` at the end of DESTINATION in cmake function `install()`.
Also merged 2 identical CMake `install()` which only diff in exclude pattern.

Remove redundant tail / in DESTINATION in CMake install

---

examples/metrics_simple/metrics_ostream.cc
sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/src/metrics/meter_context.cc
sdk/src/metrics/meter_provider.cc
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/meter_provider_sdk_test.cc
sdk/test/metrics/metric_reader_test.cc

Currently we [register ](https://github.com/open-telemetry/opentelemetry-cpp/blob/bf8f433cae41ad682cf9e390650158a2751373c1/sdk/include/opentelemetry/sdk/metrics/meter_provider.h#L38)MetricExporter(s) to MeterProvider, but it is never used. This registration is un-necessary in current implementation as the life-cycle of MetricExporter is managed by MetricReader as [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/e6fb935f75c9c5a34ca3422ebdb47bb7e620f405/sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h#L44).
This PR removes the MetricExporter registration from MeterProvider, and let the registration be managed through MetricReader.

Simplifying SDK Configuration: Removing Exporter Registration from Meter Provider

---

api/include/opentelemetry/baggage/baggage.h

Fixes C4244 warning in baggage.
Added explicit type cast to declare below conversion is safe in the specific code.
> api\include\opentelemetry\baggage\baggage.h(252,26): warning C4244: 'return': conversion from 'int' to 'char', possible loss of data

Add explicit type cast in baggage UrlDecode

---

exporters/etw/include/opentelemetry/exporters/etw/utils.h

`delete []` should be used for the memory allocated by `new[]`, or it is undefined behavior.

Fix scalar delete against array

---

.github/.codecov.yaml

Adds codecov ignore
We can ignore `docs docker examples test` folder and `md` files. 

 codecov ignore

---

exporters/elasticsearch/CMakeLists.txt

Fixes: `es_log_exporter.h` includes "nlohmann/json.hpp".

fix: missing link to nlohmann_json

---

CHANGELOG.md
README.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

This release includes the alpha support of OpenTelemetry metrics.

Prepare v1.4.0 release

---

ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

Fixes select return code is not well handled, and when curl sockfd above FD_SETSIZE (1024), select can not handle it.
Changes:
1. According docs, select return -1 on error, 0 when timeout, and >0 for expected events return. The original cast the int code to bool, so when invalid sock provided, the procedure treat as good, the following procedure crash. So the code carefully check the select return code, and the really events we get.
2. Even though select is POSIX standard and cross platform, but can not handle the case when fd above FD_SETSIZE. In our production environment, we see CURL sock fd far more above it, so when Linux environment possible, we use poll instead of select.

fix: WaitOnSocket select error when sockfd above FD_SETSIZE

---

api/include/opentelemetry/trace/span_context.h
exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h

ETW exporter doesn't make a copy of the passed in `nostd::string_view` value which could be freed after the call of `SetAttribute` while ETW exporter still holds reference on it.
Also add `noexcept` for `opentelemetry::v1::trace::SpanContext::GetInvalid`.

Copy string_view passed to ETW exporter in PropertyVariant

---

sdk/CMakeLists.txt

Fixes #1272
#1273 install `sdk-config.h` to the wrong directory
```
$ tree /usr/local/include/opentelemetry/opentelemetry/
/usr/local/include/opentelemetry/opentelemetry/
└── sdk_config.h
0 directories, 1 file
``` 

install sdk-config.h

---

docs/public/sdk/GettingStarted.rst

Fixes #1347 (issue)
Fixed the Jaeger HTTP port number in the GettingStarted documentation.

Fix GettingStarted documentation for Jaeger HTTP exporter (#1347)

---

exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_utils.cc

Fixes #1437 , #1432
Add measurement attributes in Prometheus time series data for Histogram.
The sample data generated would be:
```
prometheus_metric_example_count{key1="value1",key4="value4"} 0 1654821769617
prometheus_metric_example_sum{key1="value1",key4="value4"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="0"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="5"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="10"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="25"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="50"} 0 1654821769617
prometheus_metric_example_bucket{key1="value1",key4="value4",le="75"} 0 1654821769617 …
```

Add measurement attributes in Prometheus time series data for Histogram

---

bazel/repository.bzl
third_party_release

Fixes #1438 (issue)
Upgrade nlohmann_json to 3.10.5

Upgrade nlohmann_json to 3.10.5 (#1438)

---

RELEASING.md

Fixes #1445 (issue)
Fixed broken link to OpenTelemetry.io

Fixed broken link to OpenTelemetry.io (#1445)

---

sdk/src/metrics/metric_reader.cc

PeriodicExportingMetricReader ::DoBackgroundWork() exited immedialty because of IsShutdown()
MetricReader ctor missed shutdown_(false) initialization

Fix variables inizialization

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Prepare for v1.4.1 patch release.

Prepare v1.4.1 patch release

---

sdk/src/trace/samplers/trace_id_ratio.cc

Fixing a build warning about missing initialize for aggregate initialization.

Fix build warnings about missing aggregates

---

docs/public/sdk/GettingStarted.rst

The value for `opts.endpoint` for otlp grpc exporter had an extra colon that would cause an exception if used as is.
Minor fix to an example in the opentelemetry-cpp documentation.

Fix otlp grpc exporter example in the documentation

---

INSTALL.md

Remove `--config Debug` when installing.

---

exporters/otlp/CMakeLists.txt
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_metric_utils.h
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/otlp/src/otlp_metric_utils.cc
exporters/otlp/test/otlp_metrics_serialization_test.cc

Fixes #1484 
Rename 
- OtlpGrpcMetricsExporter to OtlpGrpcMetricExporter
- OtlpGrpcMetricsExporterOptions to OtlpGrpcMetricExporterOptions
- OtlpMetricsUtils to OtlpMetricUtils

Fix #1484 (Rename OTLP gRPC metric exporter)

---

bazel/opentelemetry_proto.BUILD

`~/bazel/opentelemetry_proto.BUILD` file only contains the build rules for traces and logs. Adding build rules for metrics too.

Enable bazel build for metrics proto files

---

sdk/include/opentelemetry/sdk/metrics/view/attributes_processor.h
sdk/src/metrics/metric_reader.cc
sdk/src/metrics/state/sync_metric_storage.cc
sdk/test/metrics/async_metric_storage_test.cc

Fixes some metrics compiler warnings
added a virtual dtor, removed unused variables also fixed init order.

fix compiler warnings

---

CHANGELOG.md
cmake/opentelemetry-cpp-config.cmake.in
exporters/otlp/BUILD
exporters/otlp/CMakeLists.txt
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_metric_utils.h
exporters/otlp/src/otlp_http_client.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/src/otlp_http_log_exporter.cc
exporters/otlp/src/otlp_http_metric_exporter.cc
exporters/otlp/src/otlp_metric_utils.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc
exporters/otlp/test/otlp_metrics_serialization_test.cc

[Metrics] Add OTLP http metric exporter

---

CMakeLists.txt

Fixes #1502 
Try to build nlohmann-json only it's depended.

Try to build nlohmann-json only it's depended.

---

ext/include/opentelemetry/ext/http/common/url_parser.h
ext/test/http/url_parser_test.cc

Fixes  issue #1509
urlParser incorrect url which "@" not in first segment, like "http://abc.com/xxx@xxx".
So I modified that it will judge if "@" is in first segment, that means before the first "/",  otherwise ignore handle it.

fix: urlParser will incorrect parsing url like http://abc.com/xxx@xxx/a/b

---

exporters/ostream/include/opentelemetry/exporters/ostream/common_utils.h

The common_utils.h header is being used in multiple build targets in the ostream exporter. This header defines the print_value() function, and because it's not inlined, it causes the build to fail in case it tries to link to more than one ostream exporter.
Solution: inline function.

Inline print_value() in ostream exporter

---

ext/src/http/client/curl/CMakeLists.txt

Fixes #1517
Changed link of libcurl (CMake CURL::libcurl) to opentelemetry_http_client_curl to be PRIVATE. This fixes the build issue for me on my Linux system using shared libraries, however I've not tested this anywhere else.

Don't require applications using jaeger exporter to know about libcurl

---

sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/sync_metric_storage_test.cc

Fixes #1532 (issue)
fixes the leaks by using smart pointer.

Fix metrics unit test memory leack

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_exporter.h
exporters/elasticsearch/src/es_log_exporter.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/prometheus/src/collector.cc

Fixes #1538 
+ Optimize header dependency to of `es_log_exporter`.
+ Fix GCC 4.8 compatibility for new metrics implementation and `emplace_back(unique_ptr<HttpSessionData>(...))`.
+ Add implementation of `OtlpGrpcMetricExporter::ForceFlush`, `OtlpGrpcMetricExporter::Shutdown` and `OtlpGrpcMetricExporter::isShutdown`.

Fix several compiling/linking errors

---

exporters/ostream/include/opentelemetry/exporters/ostream/metric_exporter.h
exporters/ostream/src/metric_exporter.cc
exporters/ostream/test/ostream_metric_test.cc

While debugging my `Resource` definition for a metrics exporter, I realized
the `OStreamExporter` did not support printing out `Resource` contents. 
I plan on expanding upon the existing unit(s) for checking the resource
attributes, but wanted to "test the waters" first. 
My goal was to attach git branch/sha information to metrics that are collected
for easier A/B testing, and a `Resource` seemed like a natural place for that. 
For example, using the attributes:
```
service.git.branch
service.git.commit_sha
service.git.commit_sha_short
```
However, there seems to be some debate around [using resources and metrics
with prometheus](https://github.com/open-telemetry/opentelemetry-specification/issues/2640), which is what led me down my debugging path of using the ostream exporter first.

fix(metrics): ostream exporter should print out resource attributes

---

exporters/ostream/include/opentelemetry/exporters/ostream/metric_exporter.h
exporters/ostream/src/metric_exporter.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_metric_utils.h
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/otlp/src/otlp_http_metric_exporter.cc
exporters/otlp/src/otlp_metric_utils.cc
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter.h
exporters/prometheus/src/exporter.cc
sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h
sdk/include/opentelemetry/sdk/metrics/instruments.h
sdk/include/opentelemetry/sdk/metrics/metric_exporter.h
sdk/include/opentelemetry/sdk/metrics/metric_reader.h
sdk/include/opentelemetry/sdk/metrics/state/metric_collector.h
sdk/src/metrics/export/periodic_exporting_metric_reader.cc
sdk/src/metrics/metric_reader.cc
sdk/src/metrics/state/metric_collector.cc
sdk/src/metrics/state/temporal_metric_storage.cc
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/meter_provider_sdk_test.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/periodic_exporting_metric_reader_test.cc
sdk/test/metrics/sync_metric_storage_test.cc

Fixes #1339
As preferred aggregation temporality concept is removed from specs, and is made as function of instrument-kind (see section here - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader) , following changes are done -
- Modify `GetAggregationTemporality()` method in MetricReader. The methods now take in instrument type/kind, that lets exporter find which temporality to use based on the instrument.
- Add  `GetAggregationTemporality()` method in MetricExporter. This method takes the instrument type/kind, and returns the correct temporality to use based on the exporter used - 
- OTLP exporter can be configured with a preferred temporality
- Prometheus only uses cumulative (as it doesn't support delta).
For significant …

[Metrics SDK] Metric aggregation temporality controls 

---

exporters/otlp/src/otlp_http_client.cc
ext/src/http/client/curl/http_client_curl.cc
ext/src/http/client/curl/http_operation_curl.cc

Fix infinitely waiting when shutdown with more than one running http sessions.

---

exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc

Fixes #1551 (issue)
Prometheus exporter supports Gauge Type and added error handling.

Prometheus exporter support Gauge Type

---

exporters/ostream/src/metric_exporter.cc
exporters/ostream/test/ostream_metric_test.cc

Previously, we were overloading the `name` key in the metrics ostream
exporter. This patch qualifies the `name` key with the appropriate prefix
based on the structures they represent.

[NFC] Improve scope/instrument names in metrics ostream exporter

---

sdk/include/opentelemetry/sdk/metrics/aggregation/histogram_aggregation.h
sdk/include/opentelemetry/sdk/metrics/aggregation/lastvalue_aggregation.h
sdk/include/opentelemetry/sdk/metrics/aggregation/sum_aggregation.h
sdk/src/metrics/aggregation/histogram_aggregation.cc
sdk/src/metrics/aggregation/lastvalue_aggregation.cc
sdk/src/metrics/aggregation/sum_aggregation.cc

Fixes #1542 (issue)
protects reads in aggregations.

fix metrics race condition

---

api/test/metrics/noop_sync_instrument_test.cc
sdk/test/metrics/aggregation_test.cc
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/exemplar/no_exemplar_reservoir_test.cc
sdk/test/metrics/meter_provider_sdk_test.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/multi_metric_storage_test.cc
sdk/test/metrics/sync_instruments_test.cc
sdk/test/metrics/sync_metric_storage_test.cc

remove throw check from metrics  with noexcept

---

sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/attributes_hashmap_benchmark.cc

Fixes metrics asan and tsan CI
We have false positive on attributes_hashmap_benchmark.cc, this can be removed if we store the lambda in a variable and construct threads with it.
also a raw pointer was used in test, changed to smart pointer.

Fix metrics asan and tsan CI

---

.github/workflows/ci.yml
ci/do_ci.sh

Fixes #1494 (issue)
makes all jobs testing the new metrics and adds `bazel` and `cmake`, <del>`gcc 4.8`</del> jobs for testing deprecated metrics.

Add CI jobs for new and deprecated metrics

---

sdk/include/opentelemetry/sdk/metrics/async_instruments.h
sdk/include/opentelemetry/sdk/metrics/meter.h
sdk/src/metrics/async_instruments.cc
sdk/src/metrics/meter.cc
sdk/test/metrics/CMakeLists.txt
sdk/test/metrics/async_instruments_test.cc
sdk/test/metrics/meter_test.cc

Fixes #1550, #1556
1. Create ObservableRegistry during Meter creation.
2. Store the reference to ObservableRegistry while Instruments created from that Meter.
3. During the collection (in `Meter::Collect()`), call all the registered callbacks once.

METRICS SDK - Calling Observable Instruments callback during metrics collection

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

https://github.com/open-telemetry/opentelemetry-cpp/milestone/13

Prepare for metrics release candidate v1.6.0

---

exporters/elasticsearch/src/es_log_exporter.cc
exporters/otlp/src/otlp_http_client.cc

Fixes #1578 
+ Add error log when OTLP HTTP exportor and ES exportor get a http error code

Add error log when getting a http error code

---

sdk/src/metrics/async_instruments.cc

This PR fixes the issue of not being able to de-register async instrument callbacks.

[MINOR]: Fix ObservableInstrument::RemoveCallback

---

sdk/include/opentelemetry/sdk/metrics/instruments.h
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/metric_reader_test.cc

Fixes Metrics warnings
removes unused variables.

Metrics warnings

---

sdk/src/metrics/state/temporal_metric_storage.cc
sdk/test/metrics/sync_metric_storage_test.cc

Fixes #1585 
In case cumulative metric collection is done without any measurement recorded in between, the same metrics should be returned. Merge was not happening properly if there is no unreported metrics. This is fixed now. Also added the tests to validate.

Fix 1585 - Multiple cumulative metric collections without measurement recording.

---

.github/workflows/ci.yml

Remove running CI on async-changes on PR because all async-changes commits had already been merged to main.

Remove running CI on async-changes branch on PR

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h

Fixes #1600
Fix default value of `OtlpHttpMetricExporterOptions::aggregation_temporality`.

Fix default value of `OtlpHttpMetricExporterOptions::aggregation_temporality`.

---

sdk/include/opentelemetry/sdk/resource/resource.h

The documented behaviour of Resource::Merge is the opposite of what it actually does.
As per https://cplusplus.com/reference/unordered_map/unordered_map/insert/, when calling `insert` on an unordered_map, each element is inserted only if its key is not equivalent to the key of any other element already in the container.

resource sdk: Update Resource::Merge function docs

---

examples/grpc/tracer_common.h

The GrpcClient/ServerCarrier in the gRPC examples assume that the provided string_views are null-terminated, 
which is not necessarily the case, e.g. when they are provided by the HttpTraceContext:
https://github.com/open-telemetry/opentelemetry-cpp/blob/82a81157a98c7120ab90e06295df0ff5ff328e56/api/include/opentelemetry/trace/propagation/http_trace_context.h#L89-L102

[gRPC]: Fix oob access of string_view in example

---

README.md

As discussed and agreed in the last SIG meeting - https://docs.google.com/document/d/1i1E4-_y4uJ083lCutKGDhkpi3n4_e774SBLi9hPLocw/edit?usp=sharing
PR to change in otel-community repo  - https://github.com/open-telemetry/community/pull/1199. 
Google calendar would be updated today.

Change Wednesday meeting time to 9:00 PT

---

sdk/test/trace/sampler_benchmark.cc

Fixes #1612 
The sampler parameter was ignored in benchmark span creation test.
Now BM_NoopSpanCreation() uses the always off sampler, measuring the Noop creation code.

Fixes span creation benchmark issue #1612.

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
examples/grpc/client.cc
examples/http/server.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #1624 
Upgrade semantic conventions to opentelemetry-specification v1.13.0
BREAKING: rename `net.peer.ip` to `net.sock.peer.addr`, `net.host.ip` to `net.sock.host.addr`,
`net.peer.name` to `net.sock.peer.name` for socket-level instrumentation.
See the opentelemetry-specification v.1.13.0 release notes,
section Semantic Conventions, for full details.

[Semantic Conventions] Align on the specification 1.13.0

---

README.md

Add Marc Alff in cpp-approvers
Per discussion in C++ SIG Meeting, 2022-09-26.

Add Marc Alff in cpp-approvers

---

docs/dependencies.md

This is a minor fix of a typo in the dependencies documentation.`@io_opentelemetry_cpp/api:with_abseil` is not a valid Bazel target name, I believe that it should instead be @io_opentelemetry_cpp//api:with_abseil.

Fix typo in package name in documentation.

---

third_party_release

| library                  | version                                  |
|--------------------------|------------------------------------------|
| google-benchmark         | v1.5.0                                   |
| google-googletest        | release-1.12.1                           |
| nlohmann-json            | v3.11.2                                  |
| protocolbuffers-protobuf | 31ebe2ac71400344a5db91ffc13c4ddfb7589f92 |

bump vcpk to 2022.08.15

---

exporters/ostream/src/metric_exporter.cc
exporters/ostream/test/ostream_metric_test.cc
exporters/otlp/src/otlp_metric_utils.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/prometheus_test_helper.h
sdk/include/opentelemetry/sdk/metrics/aggregation/aggregation_config.h
sdk/include/opentelemetry/sdk/metrics/data/point_data.h
sdk/src/metrics/aggregation/histogram_aggregation.cc
sdk/test/metrics/aggregation_test.cc

Fixes: #1628, #1629
Irrespective of the aggregation data type (`long` or `double`) for values stored in buckets, the boundaries range should be always of type `double`.
As mentioned in the specs - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation
This PR fixes it.
Also, change the default buckets as per specs changes - https://github.com/open-telemetry/opentelemetry-specification/pull/2770 from
`0, 5, 10, 25, 50, 75, 100, 250, 500, 1000` to `0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000`

[Metrics SDK] Change boundry type to `double` for Explicit Bucket Histogram Aggregation, and change default bucket range

---

sdk/include/opentelemetry/sdk/logs/batch_log_processor.h
sdk/include/opentelemetry/sdk/logs/multi_log_processor.h
sdk/include/opentelemetry/sdk/logs/processor.h
sdk/include/opentelemetry/sdk/logs/simple_log_processor.h
sdk/src/logs/batch_log_processor.cc
sdk/src/logs/logger.cc
sdk/src/logs/multi_log_processor.cc
sdk/src/logs/simple_log_processor.cc
sdk/test/logs/batch_log_processor_test.cc
sdk/test/logs/logger_provider_sdk_test.cc
sdk/test/logs/logger_sdk_test.cc
sdk/test/logs/simple_log_processor_test.cc

Fixes #1291 
There are a lot changes of logs specification since #1291 . I think we can change `OnReceive` to `OnEmit` and close #1291 first. And we may need more discussion about the changes of logs API and SDK before the rest changes. #1653 
+ Rename `OnReceive` to `OnEmit`

Rename `OnReceive` to `OnEmit`

---

CMakeLists.txt

Fixes #1659 
Detect ARCH=sparc in CMake.

Detect ARCH=sparc in CMake

---

sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/src/metrics/meter_context.cc

Fixes #1667 (issue)
adds a lock for reads and writes of `MeterContext::meters_`.

fix data race on MeterContext::meters_

---

examples/metrics_simple/metrics_ostream.cc
sdk/include/opentelemetry/sdk/metrics/aggregation/aggregation_config.h
sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h
sdk/include/opentelemetry/sdk/metrics/aggregation/histogram_aggregation.h
sdk/include/opentelemetry/sdk/metrics/state/async_metric_storage.h
sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h
sdk/include/opentelemetry/sdk/metrics/state/temporal_metric_storage.h
sdk/include/opentelemetry/sdk/metrics/view/view.h
sdk/src/metrics/aggregation/histogram_aggregation.cc
sdk/src/metrics/state/temporal_metric_storage.cc
sdk/test/metrics/aggregation_test.cc
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/sync_metric_storage_counter_test.cc
sdk/test/metrics/sync_metric_storage_histogram_test.cc

Fixes #1665 (issue)
One of the `CreateAggregation` overloads was not passing the aggregation config to the histogram ctors. Also replaced nostd with `std::shared_ptr`.

fix Histogram crash

---

sdk/include/opentelemetry/sdk/metrics/exemplar/histogram_exemplar_reservoir.h

Fix a potential precision loss on integer in ReservoirCellIndexFor

---

exporters/elasticsearch/src/es_log_exporter.cc
exporters/otlp/src/otlp_http_client.cc

Fixes #1702 
+ Fix debug log of OTLP HTTP exporter and ES log exporter

Fix debug log of OTLP HTTP exporter and ES log exporter

---

CHANGELOG.md
examples/metrics_simple/README.md
examples/metrics_simple/metrics_ostream.cc
examples/prometheus/README.md
examples/prometheus/main.cc
exporters/ostream/include/opentelemetry/exporters/ostream/metric_exporter.h
exporters/ostream/test/ostream_metric_test.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_factory.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter_factory.h
exporters/otlp/src/otlp_grpc_metric_exporter_factory.cc
exporters/otlp/src/otlp_http_metric_exporter_factory.cc
exporters/otlp/test/otlp_grpc_metric_exporter_factory_test.cc
exporters/otlp/test/otlp_http_metric_exporter_factory_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter.h
sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h
sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/include/opentelemetry/sdk/metrics/push_metric_exporter.h
sdk/include/opentelemetry/sdk/metrics/state/metric_collector.h
sdk/src/metrics/export/periodic_exporting_metric_reader.cc
sdk/src/metrics/meter_context.cc
sdk/src/metrics/meter_provider.cc
sdk/src/metrics/state/metric_collector.cc
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/meter_provider_sdk_test.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/periodic_exporting_metric_reader_test.cc

[Metrics SDK] Add support for Pull Metric Reader

---

CMakeLists.txt
api/CMakeLists.txt
ci/do_ci.sh
sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h

Exemplar are still experimental, so exemplar processing is moved behind feature flag macro - `ENABLE_METRICS_EXEMPLAR_PREVIEW`. The exemplar would be processed in hot path only if the flag is enabled. The flag needs to be explicitly enabled in build script to use exemplars.
This allows us 
- to give a message to users that this functionality could change in future.
- and achieve (slight) performance gain during measurement recording, even while using the non-sampling exemplar.
The CI tests still continue to test the full metrics functionality with feature flag enabled for both cmake and bazel.

[Metrics SDK] Move Metrics Exemplar processing behind feature flag

---

docs/dependencies.md

Document libthrift 0.12.0 doesn't work with Jaeger exporter

---

README.md

- Tag Metrics as stable in README.md
- Remove section "OpenTelemetry Specification Compatibility Matrix". This was supposed to map the compatibility between specs version and otel-cpp version, but not much use is coming out of it.

Update Metrics status in README.md

---

api/include/opentelemetry/nostd/span.h

Fixes #1705 
Remove misleading comments about ABI compatibility for nostd::span

Remove misleading comments about ABI compatibility for nostd::span

---

.github/workflows/ci.yml
CHANGELOG.md
ci/do_ci.ps1
ci/do_ci.sh

This does cleanup of first part of #1573 - Removing old metrics build/tests from GitHub CI

[Old Metrics Cleanup] Remove old metric from GitHub CI 

---

ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

Fixes #1738 
Use include "curl/curl.h" instead of <curl/curl.h>,
to build with the proper CURL package.

[Build] Multiple CURL packages leads to invalid build (#1738)

---

exporters/otlp/README.md

Format the OTLP exporter config options for better visibility in mark down editor without entering preview mode (help dev cycle).

Format config options in OTLP exporter readme

---

INSTALL.md

Cleanup INSTALL.md

---

examples/prometheus/CMakeLists.txt
exporters/prometheus/CMakeLists.txt
exporters/prometheus/test/CMakeLists.txt

Fixes #1764
Changed the target name to `opentelemetry_exporter_prometheus` .
```bash
$ ls /usr/local/lib/libopentelemetry_* -ltr
-rw-r--r-- 1 root root  5884858 Oct 28 08:10 /usr/local/lib/libopentelemetry_proto.a
-rw-r--r-- 1 root root   874006 Oct 28 16:19 /usr/local/lib/libopentelemetry_otlp_recordable.a
-rw-r--r-- 1 root root     3300 Nov 10 16:11 /usr/local/lib/libopentelemetry_version.a
-rw-r--r-- 1 root root   144904 Nov 10 16:11 /usr/local/lib/libopentelemetry_common.a
-rw-r--r-- 1 root root  2794826 Nov 10 16:11 /usr/local/lib/libopentelemetry_resources.a
-rw-r--r-- 1 root root  1910868 Nov 10 16:11 /usr/local/lib/libopentelemetry_http_client_curl.a
-rw-r--r-- 1 root root  5777388 Nov 10 16:11 /usr/local/lib/libopentelemetry_trace.a
-rw-r--r-- 1 root root 19873766 Nov 10 16:11 …
```

[Metrics SDK] Change Prometheus CMake target name

---

sdk/include/opentelemetry/sdk/common/global_log_handler.h
sdk/src/logs/logger_provider.cc
sdk/src/metrics/meter_provider.cc
sdk/src/trace/tracer_provider.cc

Fixes #1718 
`GlobalLogHandler` and  `MeterProvider` are lazy singletons. As of now, `MeterProvider` singleton is first initialized, followed by `GlobalLogHandler` (when the first message is logged).  This order of initialization means `GlobalLogHandler` is destroyed before `MeterProvider`, which further results in segfault when trying to use the logger from MeterProvider destructor.
The easy solution would be to use `GlobalLogHandler` to log message from inside the `MeterProvider` constructor. This makes the complier to guarantee that the GlobalLogHandler is constructed before MeterProvider, and so destroyed after MeterProvider. Have tested the changes locally by reproducing the segfault, and then ensuring there is no segfault with the change.
To demonstrate the order of initialization, …

Fix GlobalLogHandler singleton creation order

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
buildscripts/semantic-convention/templates/SemanticAttributes.h.j2
examples/grpc/client.cc
examples/grpc/server.cc
examples/http/client.cc
examples/http/server.cc
exporters/otlp/test/otlp_log_recordable_test.cc
exporters/zipkin/src/recordable.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h
sdk/src/resource/resource.cc
sdk/test/resource/resource_test.cc

Fixes #1758
Upgrade semantic conventions to opentelemetry-specification 1.15.0
Change naming to use camel case, to avoid collisions with macros.

[SEMANTIC CONVENTIONS] Upgrade to version 1.15.0

---

bazel/repository.bzl

Fixes #1778
Bazel build:
Upgrade Abseil to abseil-cpp-20220623.1

[BUILD] Upgrade bazel build to use abseil-cpp-20220623.1

---

CONTRIBUTING.md
tools/format.sh

Fixes #1781 
In CONTRIBUTING.md,
clarify that clang-format version 10.0 is used.

[DOC] Document that clang-format version 10.0 is used.

---

sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/src/metrics/meter_context.cc
sdk/src/metrics/state/metric_collector.cc

Fixes #1720 
Another approach to fix #1720 (refer #1777 for first approach) by adding `MeterContext::ForEachMeter`, which invokes callback to process each meter in thread-safe manner. This will ensure that metric collection doesn't crash for existing meters while new meter is being added.

Add MeterContext::ForEachMeter() method to process callbacks on Meter in thread-safe manner

---

exporters/otlp/src/otlp_http_client.cc

Fixes #1759 
+ Fix session lock of `OtlpHttpClient`

Fix session lock of `OtlpHttpClient`

---

.github/workflows/ci.yml

Fix clang-format in CI
ubuntu-20.04 contains:
Clang-format 10.0.0, 11.0.0, 12.0.0
ubuntu-22.04 contains:
Clang-format 12.0.1, 13.0.1, 14.0.0
Opentelemetry-cpp CI uses Clang-format 10 on ubuntu-latest.
This now breaks because ubuntu-latest was upgraded from 20.04 to 22.04.
Change the format workflow to use ubuntu 20.04 explicitly, to restore a working CI.

Fix clang-format in CI

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

Fixes #1791
Fix CI build
ubuntu-latest upgraded from 20.04 to 22.04
ubuntu-20.04, used in CI before, had gcc 9 and gcc 10
ubuntu-22.04, used in CI now, has gcc 9, gcc 10 and gcc 11
Use gcc 10 instead of gcc 11 on ubuntu 22.04 (now latest), where this is sufficient.
Use ubuntu-20.04 when more dependencies fail (asan, abseil, grpc)

Fix CI build

---

bazel/repository.bzl
ci/do_ci.sh
exporters/otlp/test/otlp_grpc_exporter_benchmark.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc

#1634 (issue) step 1/2
This PR bumps gRPC to v1.48.1 for bazel CIs. It also adds the latest gRPC with C++11 support, so that in a separate PR we can hava e2e C++11 test: https://github.com/open-telemetry/opentelemetry-cpp/blob/21ced217aa96bee528d7c028b68213d26a2e3c70/examples/e2e/WORKSPACE#L15

bump to gRPC v1.48.1 for bazel CIs

---

.github/workflows/benchmark.yml

Fixes #1800
Fix `OpenTelemetry-cpp benchmarks / Run OpenTelemetry-cpp benchmarks` in CI
The ubuntu-latest upgrade from 20.04 to 22.04 broke benchmarks.
Restoring ubuntu-20.04

Fix CI benchmark

---

CMakeLists.txt
api/test/baggage/BUILD
api/test/baggage/CMakeLists.txt
api/test/common/BUILD
api/test/common/CMakeLists.txt
api/test/trace/BUILD
api/test/trace/CMakeLists.txt
exporters/etw/CMakeLists.txt
exporters/otlp/BUILD
sdk/test/common/BUILD
sdk/test/common/CMakeLists.txt
sdk/test/instrumentationscope/BUILD
sdk/test/metrics/BUILD
sdk/test/metrics/CMakeLists.txt
sdk/test/trace/BUILD
sdk/test/trace/CMakeLists.txt

Add option WITH_BENCHMARK to disable building benchmarks

---

INSTALL.md
WORKSPACE
bazel/extra_deps.bzl

Signed-off-by: Roshan Chaudhari rochaudhari@nvidia.com
Fixes https://github.com/open-telemetry/opentelemetry-cpp/issues/1728
For prometheus exporter, required dependencies are not loaded in repository.bzl. When Opentelemetry is imported in some other project, these dependencies are missing.

[Exporter] add fix for prometheus exporter build

---

CMakeLists.txt

Fixes #1804 
Remove an extra character from CMakeLists.txt

Remove extra character from CMakeLists.txt

---

.github/workflows/benchmark.yml

Fixes benchmark CI
Uses g++-10 in ubuntu latest
tested [here](https://github.com/esigo/opentelemetry-cpp/actions/runs/3550556294/jobs/5964047235)

[BUILD] Fix benchmark CI

---

ci/do_ci.sh
ci/install_abseil.sh
third_party_release

Bump `abseil-cpp` for cmake CI
from `20210324.0` to `20220623.1`
also fixes `gRPC` version in `third_party_release`

[BUILD] Bump abseil-cpp for cmake CI

---

test_common/src/http/client/nosend/http_client_factory_nosend.cc

Fixes #1802 (issue)
can be tested with (no test target):
` bazel query '//... except kind(.*test, //...)' | xargs bazel build --cxxopt=-std=c++14`
moves `HttpClientFactory::CreateNoSend()` under `ENABLE_TEST` flag.

[BUILD] Fix default bazel build

---

exporters/prometheus/CMakeLists.txt

Fixes #1819
Revert back the target name for Prometheus in otel-cpp cmake config.
This is incorrect in the latest release, probably we have to plan next release bit sooner, let's discuss in community meeting. 

Fix Prometheus target name

---

api/include/opentelemetry/nostd/shared_ptr.h

Fixes #1806 
Fix type mismatch when move `nostd::shared_ptr`.

Fix type mismatch when move `nostd::shared_ptr`

---

CHANGELOG.md
cmake/opentelemetry-proto.cmake

Fixes #1823
Fix CMake `EXISTS` syntax

Fix opentelemetry-proto file exists check

---

exporters/otlp/BUILD
exporters/otlp/CMakeLists.txt

Fixes #1826
Moved otlp_grpc_utils.cc to opentelemetry_exporter_otlp_grpc_client.

Moved otlp_grpc_utils.cc to opentelemetry_exporter_otlp_grpc_client.

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter_options.h
exporters/otlp/test/otlp_http_metric_exporter_test.cc

Fixes #1821 
Add default temporality as "Cumulative" for OTLP exporter - https://github.com/open-telemetry/opentelemetry-specification/blob/v1.15.0/specification/metrics/sdk_exporters/otlp.md#additional-configuration

Change default temporality as "Cumulative" for OTLP metrics exporters

---

exporters/otlp/src/otlp_grpc_utils.cc

fix `enum-compare-switch` warning

---

exporters/otlp/src/otlp_metric_utils.cc

Trivial obvious typo affecting uint historgam max in otlp exported metrics

fix typo [affecting otlp exported histogram metrics  max<uint>]

---

examples/otlp/http_log_main.cc
examples/otlp/http_main.cc
exporters/elasticsearch/src/es_log_record_exporter.cc
exporters/otlp/src/otlp_http_client.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/src/otlp_http_log_record_exporter.cc
exporters/otlp/src/otlp_http_metric_exporter.cc
sdk/src/common/global_log_handler.cc

Fixes #1847 
Fixed console debug logs for otlp exporters.
- Removed `DEBUG:` text from logs, redundant with `OTEL_INTERNAL_LOG_DEBUG`
- Fixed a broken `OTLP HTTP Client]` tag
- Added a space after `FILE:LINE` to separate from the log message
- Added usage comments in examples
- Set `GlobalLogHandler::SetLogLevel(LogLevel::Debug)` in examples when `console_log` is enabled

Fix console debug logs for otlp exporters.

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #1853 
Upgrade semantic conventions to opentelemetry-specification 1.16.0

[SEMANTIC CONVENTIONS] Upgrade to version 1.16.0 (#1853)

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/common/global_log_handler.h
sdk/include/opentelemetry/sdk/logs/batch_log_record_processor_factory.h

Change BatchLogRecordProcessorFactory::Create to static method.
Fixed a typo in a comment.
* [METRICS] Change BatchLogRecordProcessorFactory::Create to static method

Change BatchLogRecordProcessorFactory::Create to static method

---

CHANGELOG.md
sdk/src/trace/batch_span_processor.cc
sdk/test/trace/batch_span_processor_test.cc

Fixes #1870 
Adds a warning when a span is dropped in case the `BatchSpanProcessor` queue is full.
* [n/a] Changes in public API reviewed

Log a warning when the BatchSpanProcessor queue is full.

---

exporters/otlp/test/otlp_http_log_record_exporter_test.cc
sdk/src/logs/logger.cc

Signed-off-by: WenTao Ou <admin@owent.net>
Fixes #1880 
+ Fix missing scope and resource in new Logs implementation.

Fix resource and scope of new Logs SDK implementation.

---

CHANGELOG.md
bazel/BUILD
bazel/curl.BUILD
bazel/repository.bzl
ci/do_ci.sh
ci/setup_grpc.sh
exporters/jaeger/BUILD
third_party_release

This MR migrates [platforms](https://bazel.build/extending/platforms) constraints from the deprecated `@bazel_tools//platforms` target to instead depend on the `https://github.com/bazelbuild/platforms` repository, per https://github.com/bazelbuild/bazel/issues/8622
This enables compatibility with the newly released [Bazel 6.0.0](https://github.com/bazelbuild/bazel/releases).

Migrate from @bazel_tools//platforms to https://github.com/bazelbuild/platforms

---

sdk/src/metrics/state/metric_collector.cc
sdk/src/metrics/state/temporal_metric_storage.cc

Minor metrics handling optimizations:
- avoid few unnecessary copies
- avoid empty exports with no data points

minor metrics handling optimizations

---

examples/batch/main.cc
examples/grpc/client.cc
examples/grpc/server.cc
examples/grpc/tracer_common.h
examples/http/client.cc
examples/http/server.cc
examples/http/tracer_common.h
examples/jaeger/main.cc
examples/metrics_simple/metrics_ostream.cc
examples/multi_processor/main.cc
examples/multithreaded/main.cc
examples/otlp/grpc_log_main.cc
examples/otlp/grpc_main.cc
examples/otlp/grpc_metric_main.cc
examples/otlp/http_log_main.cc
examples/otlp/http_main.cc
examples/prometheus/main.cc
examples/simple/main.cc
examples/zipkin/main.cc

Fixes #1867
Implemented explicit cleanup for:
- The global Tracer provider
- The global Meter provider
- The global Logger provider
in examples.
This is needed to shutdown opentelemetry-cpp in a controlled way.

Fix #1867 Orderly shutdown in examples

---

sdk/include/opentelemetry/sdk/resource/resource.h
sdk/src/resource/resource.cc

Fixes #1898 (issue)
changes `sdk::resource::Resource::Merge` to const.

sdk::resource::Resource::Merge should be const

---

CHANGELOG.md
CMakeLists.txt
cmake/nlohmann-json.cmake

Fixes #1910 
Moved nlohmann_json dependency logic to cmake/nlohmann-json.cmake
No behavior change.
Added documentation for various ways to add the nlohmann_json dependency.

Cleanup CMake makefiles for nlohmann_json.

---

api/include/opentelemetry/common/macros.h
api/include/opentelemetry/trace/trace_state.h
api/include/opentelemetry/version.h
sdk/include/opentelemetry/sdk/metrics/instrument_metadata_validator.h
sdk/include/opentelemetry/sdk/metrics/view/predicate.h
sdk/src/metrics/instrument_metadata_validator.cc
sdk/test/metrics/histogram_test.cc
sdk/test/metrics/view_registry_test.cc

As the macros defined in `macros.h` is general for all sources, including it in `version.h` to make it available for all sources (no need for separate `#include "opentelemetry/common/macros.h"` statement.

Make macros.h available for all source files via version.h

---

sdk/src/metrics/export/periodic_exporting_metric_reader.cc

The periodically exporting metric reader requires the timeout field to be strictly less than the interval field. However, the warning that is logged out gives the opposite requirement. The existing logic in the code is correct.

Fix warning for misconfiguration of PeriodicExportingMetricReader

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #1915
Upgrade semantic convention to spec 1.17.0

[SEMANTIC CONVENTIONS] Upgrade to version 1.17.0

---

INSTALL.md

Fix documentation to use `cmake -DBUILD_PACKAGE=ON ..` to configure building package.

Small fix in INSTALL.md for enabling building package.

---

api/include/opentelemetry/nostd/shared_ptr.h

Remove redundant macro check in nostd::shared_ptr

---

.github/workflows/ci.yml
CHANGELOG.md
ci/do_ci.sh
ci/install_protobuf.sh
exporters/otlp/src/otlp_metric_utils.cc
sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h

Fixes #1942
Fixed build warnings in the OTLP HTTP exporter.
Added OTLP HTTP to the `MAINTAINER_MODE` CI.

[BUILD] OTLP HTTP Exporter has build warnings in maintainer mode

---

CHANGELOG.md
bazel/repository.bzl
exporters/prometheus/test/exporter_utils_test.cc
third_party_release

The earlier version v1.0.0 was released on Nov 2021.

upgrade prometheus-cpp to v1.1.0

---

INSTALL.md

As discussed in #1950 a minor update to INSTALL.md to also mention the alpine packages.

Add alpine packages to INSTALL.md

---

api/CMakeLists.txt

Noticed this while making some adjustments to the Conan recipe for opentelemetry-cpp.
Fix a typo to align with the cmake `option` defined in the top level `CMakeLists.txt`.

Fix typo GENENV -> GETENV

---

sdk/include/opentelemetry/sdk/common/env_variables.h

Fixes #1970
Fixed `unique_ptr<char>` to `unique_ptr<char[]>` in `GetEnvironmentVariable()`,
so that `delete[]` is used instead of `delete`, when freeing the `char[]` data.

 GetEnvironmentVariable(), mismatched delete / delete[] on windows

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #1973
Upgraded semantic conventions to 1.18.0

Upgraded semantic conventions to 1.18.0

---

ext/src/http/client/curl/http_client_curl.cc

Fixes #1976 
+ Do not reset curl handle and just wake background thread to finish the removing.

Fix thread-safety when shutdown.

---

sdk/src/logs/logger.cc
sdk/test/logs/logger_sdk_test.cc

Fixes #1984 
+ Fix missing ObservedTimestamp.

Fix missing ObservedTimestamp.

---

sdk/test/metrics/sync_instruments_test.cc

Found while doing some performance tests on metrics.

[Metrics SDK] Small fix in variable names in Sync Instrument unit tests

---

CHANGELOG.md
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h

Check attribute name is "ParentId“， and bypass set attribute if so.

[ETW Exporter]Do not overwrite ParentId when setting attribute on Span

---

CHANGELOG.md
CMakeLists.txt
buildscripts/pre-commit
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Avoid using the general macro like name as `MAJOR_VERSION`. It could clash with the macro definition form other header files even it is under namespace. Add the prefix `OPENTELEMETRY_SDK_` to make the name more specific.

Rename the global SDK version variables to avoid naming clash

---

.github/workflows/ci.yml
README.md

Fixes #2019 
- Use ubuntu-20.04 instead of ubuntu-18.04
- Add Xenial package repo to download GCC 4.8 
- Update Supported Development Platforms (based on CI pipeline) in README.md

Remove ubuntu 18.04 runner image from CI

---

opentracing-shim/README.md

- Followup to #1909
- Adds a direct link to the [Migrating from OpenTracing][migrating] page from the OTel website (that page contains a link to the corresponding specification page).
- Makes a few copyedits
- Related: https://github.com/open-telemetry/opentelemetry.io/pull/2466
**Preview**: https://github.com/open-telemetry/opentelemetry-cpp/blob/79ecce82bb29d2a71a66f8fd79c8d33c26b17ce9/opentracing-shim/README.md
/cc @chusitoo @lalitb @reyang 
[migrating]: https://opentelemetry.io/docs/migration/opentracing/

OT shim page adjustments

---

CHANGELOG.md
ci/do_ci.sh

Fixes #1952 
It is no longer needed to run the metrics ostream example in CI.

Remove separate run of metrics ostream example

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/resource/resource.h
sdk/src/resource/resource.cc
sdk/test/resource/resource_test.cc

Fixes #2035 
In `Resource::Merge` this PR will cause the old schema url to be used if the updating schema url is empty. This is in accord with [the specification](https://opentelemetry.io/docs/reference/specification/resource/sdk/#merge).

Pick old schema url when updating schema url is empty according to specification in Resource::Merge

---

api/include/opentelemetry/logs/provider.h

Export factory class of log provider

---

INSTALL.md
README.md
docs/dependencies.md
docs/library-distribution.md
docs/using-clang-format.md
examples/grpc/README.md
examples/http/README.md
examples/otlp/README.md

Hi! I'm new for op-cpp and I found some typo when reading docs.

Fix some docs typo

---

examples/prometheus/README.md
examples/prometheus/main.cc

As far as I can see View should have the same name as Instrument
> The name of the View (optional). If not provided, the **Instrument name** MUST be used by default. This will be used as the name of the [metrics stream](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#events--data-stream--timeseries).
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view

Fix view names in Prometheus example

---

CHANGELOG.md
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter_options.h
exporters/otlp/src/otlp_environment.cc
exporters/otlp/test/otlp_grpc_exporter_test.cc

Fixes #2058
The logic to decide whether or not an OLTP GRPC exporter uses SSL has changed, to comply with the specification.
In particular, the endpoint scheme ("http" or "https") takes precedence.

[EXPORTER] GRPC endpoint scheme should take precedence over OTEL_EXPORTER_OTLP_TRACES_INSECURE

---

CHANGELOG.md
CMakeLists.txt

Fixes #2061 
The default value of `OPENTELEMETRY_INSTALL_default` should be `ON` when otel-cpp in on top level.

Fix default value of `OPENTELEMETRY_INSTALL_default`.

---

exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tail_sampler.h

Cleanup warnings in ETW exporters

---

examples/prometheus/README.md
examples/prometheus/prometheus.yml

Alerting is not used in this example and port 9464 can't be reused for this purpose

Remove unused 'alerting' section from prometheus.yml in examples

---

exporters/otlp/include/opentelemetry/exporters/otlp/protobuf_include_prefix.h

Fixes #2065 
Ignore more warning of generated protobuf files than not included in `-Wall` and `-Wextra`.

Ignore more warning of generated protobuf files than not included in `-Wall` and `-Wextra`

---

ci/do_ci.sh

Fixes #2074
Some of targets does not contain parallel build mechanism which was supported by default.

Make some targets parallel in CI pipeline (UNIX)

---

INSTALL.md

Hi! I try to integrate opentelemery into my Bazel project. 
I found that `extra_deps.bzl` was introduced after v1.8.0, we should make some hints to avoid misleading users.:)

[Docs] Make some hints

---

ci/do_ci.ps1

Make Windows build environment parallel

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

[SEMANTIC CONVENTIONS] Upgrade to version 1.20.0

---

CHANGELOG.md
sdk/src/metrics/state/temporal_metric_storage.cc
sdk/test/metrics/sync_metric_storage_counter_test.cc
sdk/test/metrics/sync_metric_storage_histogram_test.cc
sdk/test/metrics/sync_metric_storage_up_down_counter_test.cc

The [OpenTelemetry data model for metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#metric-points) states that "with cumulative aggregation temporality ... we expect to report the full sum since 'start'", and the accompanying diagram illustrates the same `start_time` present in each report.
However, prior to this change, cumulative metrics were being reported with a start time equal to the last report time. This broke compatibility with services expecting the documented behavior. (For example, without this change, Counter metrics submitted to the Google Cloud Monitoring API via the googlecloudexporter are not represented correctly). 

Use sdk_start_ts for MetricData start_ts for instruments having cumulative aggregation temporality.

---

CHANGELOG.md
ext/src/http/client/curl/http_operation_curl.cc

Fixes #2101
Provide macro `CURL_VERSION_BITS`, when building old (< 7.43.0) CURL versions.

[BUILD] Build break with old curl, macro CURL_VERSION_BITS unknown

---

ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h

Fixes #2106 
+ Add missing STL header.

Add missing STL header.

---

CMakeLists.txt

To resolve #1926, we'll remove `WITH_OTLP` CMake option as we discussed. But this option could be used by users, so emit warning for now to about its deprecation.

Show warning message if WITH_OTLP is enabled

---

CMakeLists.txt
examples/common/foo_library/CMakeLists.txt
examples/common/logs_foo_library/CMakeLists.txt
examples/common/metrics_foo_library/CMakeLists.txt
exporters/elasticsearch/CMakeLists.txt
exporters/jaeger/CMakeLists.txt
exporters/memory/CMakeLists.txt
exporters/ostream/CMakeLists.txt
exporters/otlp/CMakeLists.txt
exporters/prometheus/CMakeLists.txt
exporters/zipkin/CMakeLists.txt
ext/src/http/client/curl/CMakeLists.txt
ext/src/zpages/CMakeLists.txt
opentracing-shim/CMakeLists.txt
sdk/src/common/CMakeLists.txt
sdk/src/logs/CMakeLists.txt
sdk/src/metrics/CMakeLists.txt
sdk/src/resource/CMakeLists.txt
sdk/src/trace/CMakeLists.txt
sdk/src/version/CMakeLists.txt

Fixes #2100
Versioning policy is described here for debian - https://www.debian.org/doc/debian-policy/ch-sharedlibs.html. In general same is followed across other *unix distributoins. 
- Added CMake option OTELCPP_VERSIONED_LIBS to enable generating versioned shared libs.
- Currently using OPENTELEMETRY_ABI_VERSION_NO as SOVERSION, we can also use MAJOR version. But as per the recommendation, SOVERSION should change for any ABI breaking change.
- The output is as below:
```console
$ ls -ltr /usr/local/lib/libopentelemetry_*common*so*
-rw-r--r-- 1 root root 281640 Apr 20 21:59 /usr/local/lib/libopentelemetry_common.so.1.9.0
lrwxrwxrwx 1 root root     32 Apr 20 22:01 /usr/local/lib/libopentelemetry_common.so.1 -> libopentelemetry_common.so.1.9.0
lrwxrwxrwx 1 root root     28 Apr 20 22:01 …
```

Fix: #2100 Building shared libraries with version suffix, along with the symbolic link

---

cmake/nlohmann-json.cmake

Fix if JSON library already added another CMake target

---

CHANGELOG.md
exporters/otlp/CMakeLists.txt
ext/src/http/client/curl/CMakeLists.txt
sdk/src/metrics/CMakeLists.txt

Fixes #2113 
Fixes missing target dependencies for 3 libraries:
Before fix:
```
$ ldd -r -d libopentelemetry_*so  2>&1 | grep undefin
undefined symbol: _ZNK13opentelemetry2v13sdk8resource8Resource13GetAttributesEv (./libopentelemetry_exporter_ostream_metrics.so)
undefined symbol: _ZN13opentelemetry2v13sdk6common12internal_log16GlobalLogHandler18GetHandlerAndLevelEv        (./libopentelemetry_exporter_otlp_grpc_client.so)
undefined symbol: _ZN13opentelemetry2v13sdk6common12internal_log16GlobalLogHandler18GetHandlerAndLevelEv        (./libopentelemetry_http_client_curl.so)
undefined symbol: _ZN13opentelemetry2v13sdk6common12internal_log16GlobalLogHandler18GetHandlerAndLevelEv        (./libopentelemetry_exporter_otlp_http_client.so)
undefined symbol: …
```

Add missing target dependencies

---

sdk/test/logs/log_record_test.cc

Fixes #2135 
+ Add unit test for log body implicit conversions.

Add unit test for log body implicit conversions.

---

ext/include/opentelemetry/ext/http/common/url_parser.h

Fixes #2134
Single character assignment causes a warning with GCC 12 and get rid of it by wrapping this with `std::string`.

Single character wrapped by std::string to get rid of warning

---

CHANGELOG.md
DEPRECATED.md

Fixes #1830
Announce end of C++11 support for September 2023.

[DEPRECATION] Drop C++11 support

---

exporters/otlp/CMakeLists.txt

Fixes #2153 
Change nlohmann_json and protobuf dependencies of the otlp http exporter to be private not public so that applications/libraries linking with this exporter don't need to have the cmake config nor the header files for them present in their builds.
##Comments
As far as I can see these don't need to be public or even interface dependencies because they are only used by the exporter itself in its own code. They aren't exposed either by the exporter header files by a transitive include or by the header files mentioning a symbol that is only in one of these libraries.
Using this change allows my builds to proceed.

 [BUILD] Transitive dependency issue with the otlp http exporter

---

exporters/otlp/src/otlp_http_client.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc

Fixes #2157 
+ Change OTLP Json field name to camelCase

Change OTLP Json field name to camelCase

---

exporters/otlp/src/otlp_populate_attribute_utils.cc
exporters/otlp/test/otlp_recordable_test.cc

This PR changes behavior for empty array attribute values in `OtlpRecordable`. Empty array attribute values did not set the  `AnyValue` field to `ArrayValue`.
However, following the spec it seems we should forward empty arrays.
https://github.com/open-telemetry/opentelemetry-specification/blob/ce2c5946faa9c961ea01d89c7aed83621865b67b/specification/common/README.md?plain=1#L37-L39
Invoking `mutable_array_value()` before looping over the values sets the `AnyValue` variant to `ArrayValue` regardless of the number of items in the iterator.

[EXPORTER] Support empty arrays in `OtlpRecordable` attributes

---

CMakeLists.txt
CMakeSettings.json
INSTALL.md
ci/do_ci.sh
docker/Dockerfile
docker/Dockerfile.centos
docker/ubuntuLatest/Dockerfile
exporters/CMakeLists.txt

Fixes #1926, #2160.
Remove `WITH_OTLP` option and raise error on its definition as it causes confusions (see the above issues). Also make `WITH_OTLP_GRPC` as a plain option like `WITH_OTLP_HTTP`.

[BUILD] Remove option WITH_OTLP

---

exporters/otlp/src/otlp_metric_utils.cc
exporters/otlp/test/otlp_metrics_serialization_test.cc

Fixes #2170
Metrics that are inherently non-monotonic nature are exported by OTLP exporter with `IsMonotonic` set to `true`.
Updates the OTLP exporter to set `IsMonotonic` to `true` only when the instrument type in use is `kCounter` and otherwise `false`.

[EXPORTER] set is_monotonic only for instrument type kCounter

---

sdk/include/opentelemetry/sdk/metrics/aggregation/base2_exponential_histogram_indexer.h
sdk/src/metrics/CMakeLists.txt
sdk/src/metrics/aggregation/base2_exponential_histogram_indexer.cc
sdk/test/metrics/BUILD
sdk/test/metrics/CMakeLists.txt
sdk/test/metrics/base2_exponential_histogram_indexer_test.cc

Updates #1391 
Add Base2ExponentialHistogramIndexer for calculating index for a given value and scale.
It will be used in base2 exponential histogram in followup changes.

[SDK] Add base2 exponential histogram indexer

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
ext/src/dll/CMakeLists.txt

[DLL Build] link to opentelemetry_logs even without OTLP

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h

Fixes #2169
Simplify the header dependencies for file:
- `exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter.h`
The declaration of class `OtlpHttpMetricExporter` does not need to see code in `otlp_metric_utils.h`, only the implementation does.
Depending on `otlp_metric_utils.h` from a header file is problematic, because it brings a transitive dependency on protobuf generated code, which is not installed.
This fix allows an application to instantiate a `OtlpHttpMetricExporter` object, to configure the SDK to export metrics.

[BUILD] Avoid dependency on protobuf from the OTLP HTTP metrics exporter header

---

exporters/ostream/src/metric_exporter.cc

Fixes #2186 
Header file `ctime` is needed for using `std::time_t` in `std::strftime`.

Add ctime header to metrics_exporter.cc

---

README.md

It would make sense to remove me from the approvers since I haven't been actively contributing to this project for long time. It is awesome to see the project getting more traction and now we have a good number of active maintainers/approvers well distributed across different companies!! ❤️
CC @jsuereth

Move Reiley Yang to emeritus

---

exporters/prometheus/src/exporter_utils.cc

[EXPORTER] Prometheus: Error on ingesting samples with different value but same timestamp

---

cmake/opentelemetry-build-external-component.cmake

Fixes #2206 
Fix the environment variable check, and also check if the same name (OPENTELEMETRY_EXTERNAL_COMPONENT_PATH) is defined as CMake variable. I'd prefer the cmake variable as it shows in the command line and help troubleshoot and create reproducible build, and env var is also taking effect in session global scope while CMake var is only for the CMake instance which is more restricted in scope.

[BUILD] Fix if check on environment variable and add CMake variable

---

api/CMakeLists.txt
ci/do_ci.sh
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter_options.h
exporters/otlp/src/otlp_grpc_client.cc

[EXPORTER] OTLP GRPC mTLS support

---

CHANGELOG.md
examples/otlp/grpc_metric_main.cc
examples/otlp/http_metric_main.cc
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/include/opentelemetry/sdk/metrics/meter_provider_factory.h
sdk/src/metrics/meter_provider.cc
sdk/src/metrics/meter_provider_factory.cc

Fixes #2204
Fixed the `MeterProvider` constructor to use a `unique_ptr<MeterContext>`, assuming ownership.

[SDK] MeterProvider should own MeterContext, not share it

---

api/include/opentelemetry/logs/severity.h

`nostd::string_view` is used in severity.h, but the header file is not included which then require the user to include it. This PR add "nostd/string_view.h" to include explicitly.

[BUILD] Include nostd/string_view which is used severity.h

---

CHANGELOG.md
examples/grpc/tracer_common.h
examples/http/tracer_common.h
ext/test/w3c_tracecontext_test/main.cc
sdk/include/opentelemetry/sdk/logs/logger_context.h
sdk/include/opentelemetry/sdk/logs/logger_provider.h
sdk/include/opentelemetry/sdk/logs/logger_provider_factory.h
sdk/include/opentelemetry/sdk/trace/tracer_provider.h
sdk/include/opentelemetry/sdk/trace/tracer_provider_factory.h
sdk/src/logs/logger_provider.cc
sdk/src/logs/logger_provider_factory.cc
sdk/src/trace/tracer_provider.cc
sdk/src/trace/tracer_provider_factory.cc
sdk/test/logs/logger_provider_sdk_test.cc
sdk/test/trace/tracer_provider_test.cc

Fixes #2203
Fixed the `TracerProvider` constructor to use a `unique_ptr<TracerContext>`, assuming ownership.
Fixed the `LoggerProvider` constructor to use a `unique_ptr<LoggerContext>`, assuming ownership.

[SDK] TracerProvider should own TracerContext, not share it

---

sdk/include/opentelemetry/sdk/metrics/data/circular_buffer.h

We have a build that uses `opentelemetry-cpp` with C++20. It failed to compile the latest release (v1.10.0). 
[full log](https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/12072/8c960f3f9cd862f20888a610f4c07920bb57d4c5/fedora-37-cxx20-cxx20/log-4986db93-b140-49f6-9c21-2eecdb8166f5.txt).
```
[11/66] Building CXX object sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/data/circular_buffer.cc.o
FAILED: sdk/src/metrics/CMakeFiles/opentelemetry_metrics.dir/data/circular_buffer.cc.o 
/usr/bin/c++ -DHAVE_ABSEIL -Dopentelemetry_metrics_EXPORTS -I/var/tmp/build/api/include -I/var/tmp/build/sdk/include -I/var/tmp/build/sdk -I/var/tmp/build/ext/include -O3 -DNDEBUG -std=gnu++20 -fPIC -Wno-error=deprecated-declarations -MD -MT …
```

fix: include <cstdint>

---

CMakeLists.txt
ci/setup_cmake.sh

Misc cleanup in build scripts:
* Reworded comments for clarity
* Do not silence warning `/wd4996` on windows.

[CI] Misc build scripts cleanup

---

exporters/ostream/BUILD
exporters/ostream/CMakeLists.txt
exporters/ostream/include/opentelemetry/exporters/ostream/log_record_exporter_factory.h
exporters/ostream/src/log_record_exporter_factory.cc
exporters/ostream/test/ostream_log_test.cc

Fixes #2239 
+ Add `OStreamLogRecordExporterFactory`

Add OStreamLogRecordExporterFactory

---

sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h
sdk/src/logs/simple_log_record_processor.cc
sdk/src/metrics/data/circular_buffer.cc

Fixes #2241 
+ Move destructor of `SimpleLogRecordProcessor` into `.cc` .
+ Use `std::vector::assign` to replace `std::fill` .

Fix compile with clang 16 and libc++

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
exporters/otlp/src/otlp_http_client.cc
ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h
ext/include/opentelemetry/ext/zpages/tracez_data_aggregator.h
ext/test/http/curl_http_test.cc
sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h
sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/src/logs/batch_log_record_processor.cc
sdk/src/trace/batch_span_processor.cc

Fixes #2243 
Using only the default constructor to initialize `std::atomic` objects is incorrect.
This is a particularity of `std::atomic` itself, that does not follow the same rules as C++ in general.
See: https://en.cppreference.com/w/cpp/atomic/atomic/atomic
In the entire code base, reviewed every use of `std::atomic`,
and changed initialization to use the _direct list initialization syntax_.
see: https://en.cppreference.com/w/cpp/language/list_initialization
This form is the most robust and maintainable:
* auditing the source code for correctness is easier
* this form guarantees a proper initialization will be done, in all cases
This fixed the bug reported on the periodic metric reader, tested under valgrind.
This fixed a missing initialization in one of the `BatchLogRecordProcessor` …

Valgrind errors on std::atomic variables

---

.gitignore
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
examples/grpc/client.cc
examples/http/client.cc
examples/http/server.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #2138
Upgrade:
* Semantic conventions to 1.21.0
* Build tools to 0.19.0
Adjust code per the following semantic convention changes:
* https://github.com/open-telemetry/opentelemetry-specification/pull/3402
* https://github.com/open-telemetry/opentelemetry-specification/pull/3355

[SEMANTIC CONVENTIONS] Upgrade to 1.21.0

---

exporters/ostream/test/ostream_log_test.cc

Remove extra includes in ostream exporter test

---

.github/workflows/stale.yml

Fixes #2276
Do not automatically close stale issues in CI.

[CI] Do not automatically close stale issues

---

.github/workflows/benchmark.yml
ci/do_ci.sh

Fixes #2083 
There are two benchmarks workflows defined in CI:
* per PR push benchmark (`ci.yml`)
* benchmark on the main branch (`benchmark.yml`)
The former uses local tests, while the later uses an opentelemetry collector in docker.
Currently, `ci.yml` builds properly, while `benchmark.yml` fails to build.
Fixed the build for `benchmark.yml`:
* aligned the workflow definition on `ci.yml`
* in `do_ci.sh`, aligned compiler flags for `bazel.benchmark` on flags used in `benchmark`

[CI] Benchmark workflow fails, C++14 required to build grpc

---

sdk/include/opentelemetry/sdk/metrics/meter.h
sdk/src/metrics/instrument_metadata_validator.cc
sdk/test/metrics/instrument_metadata_validator_test.cc

Fixes #2281
* Increased metric name max length to 255 (in regexp and non regexp code)
* Removed unused attribute `Meter::instrument_metadata_validator`

[SDK] Increase metric name maximum length from 63 to 255 characters

---

api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/templates/SemanticAttributes.h.j2
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #2275
When a semantic convention is flagged deprecated:
* Add a doxygen `@deprecated` comment
* Add `OPENTELEMETRY_DEPRECATED` in the generated C++ code.
Generated semantic conventions again.

[SEMANTIC CONVENTION] Deprecated semconv (in the spec) not deprecated (in C++)

---

CHANGELOG.md
CMakeLists.txt
DEPRECATED.md

Fixes #2217
* Deprecate WITH_ZPAGES

[DEPRECATION] Deprecate ZPAGES

---

sdk/src/metrics/instrument_metadata_validator.cc
sdk/test/metrics/instrument_metadata_validator_test.cc

Fixes #2303
Allow `/` in metric instrument names.

[SDK] Allow metric instrument names to contain / characters

---

sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h
sdk/test/metrics/async_metric_storage_test.cc

Fixes #2296
The default aggregation type was not handled properly for Observable Counter/UpDownCounter, and the issue was surfaced/evident out with non-zero initial measurement value. Have fixed the issue. Also we were missing the test for Observable UpDownCounter. Have added the test to catch this error.

Fix Observable Counters/UpDownCounters 

---

sdk/include/opentelemetry/sdk/metrics/state/async_metric_storage.h
sdk/src/metrics/meter.cc
sdk/test/metrics/async_metric_storage_test.cc

Add exemplar reservoir to async metric storage

---

exporters/prometheus/test/collector_test.cc
exporters/prometheus/test/exporter_utils_test.cc
exporters/prometheus/test/prometheus_test_helper.h

The MetricsData instance returned from these helpers outlived the  
Resource and InstrumentationScope instances that it pointed to.

Fix lifetime issues in test utils

---

CHANGELOG.md
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc

Fixes #2316
*   [x] `CHANGELOG.md` updated for non-trivial changes
*    [x]  Unit tests have been added
*   [x] Changes in public API reviewed

[exporters/prometheus] Remove explicit timestamps from metric points

---

CHANGELOG.md
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc

Fixes #2290
*   [x] `CHANGELOG.md` updated for non-trivial changes
*   [x] Unit tests have been added
*   [x] Changes in public API reviewed

[exporters/prometheus] Handle attribute key collisions from sanitation

---

sdk/src/metrics/meter.cc

Fix minor inconsistent log message in Meter::RegisterSyncMetricStorage

---

CHANGELOG.md
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc

Fixes #2289
*   [x] `CHANGELOG.md` updated for non-trivial changes
*   [x] Unit tests have been added
*   [x] Changes in public API reviewed

[exporters/prometheus] Sanitize labels according to Prometheus spec

---

ext/src/http/client/curl/http_client_curl.cc

Fixes #2336 
+ Reduce critical section of `session_ids_m_` in http client.

Fix deadlock when shuting down http client.

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_recordable.h
exporters/otlp/src/otlp_recordable.cc
exporters/otlp/src/otlp_recordable_utils.cc
exporters/otlp/test/otlp_recordable_test.cc

This PR changes the implementation of `OtlpRecordableUtils::PopulateRequest` to group spans by their resource and instrumentation scope.
Instead of duplicating the resource and instrumentation scope for every span this now collects spans with the same resources and instrumentation scopes, reducing the size of the resulting `proto::collector::trace::v1::ExportTraceServiceRequest`.

[Exporter] Group spans by resource and instrumentation scope in OTLP export requests

---

.github/workflows/ci.yml
CHANGELOG.md
DEPRECATED.md
INSTALL.md
README.md
docs/building-with-stdlib.md
docs/dependencies.md
docs/google-test.md
docs/public/api/Overview.rst

Fixes #2147
* Drop C++11 support from CI.
* Adjust documentation.
Note that building in C++11 may still work for a while, as the code and makefiles have not changed.
Opentelemetry-cpp makes however no commitments to maintain the C++11 build.
Bug fixes, new features, or third party dependencies may require C++14 from this point, without notice.

[REMOVAL] Drop C++11 support

---

CHANGELOG.md
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc
sdk/include/opentelemetry/sdk/metrics/export/metric_producer.h

Part of https://github.com/open-telemetry/opentelemetry-cpp/issues/1841
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#instrumentation-scope-1:
> Prometheus exporters MUST add the scope name as the otel_scope_name label and the scope version as the otel_scope_version label on all metric points by default, based on the scope the original data point was nested in.
This adds the otel_scope_name and otel_scope_version labels to all metrics, if they are non-empty.

prometheus exporter: Add otel_scope_name and otel_scope_version labels

---

CHANGELOG.md
exporters/prometheus/include/opentelemetry/exporters/prometheus/collector.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/collector.cc
exporters/prometheus/src/exporter.cc
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/collector_test.cc
exporters/prometheus/test/exporter_utils_test.cc
exporters/prometheus/test/prometheus_test_helper.h
sdk/include/opentelemetry/sdk/metrics/export/metric_producer.h

Fixes #1842 
+ Prometheus exporter emits resource attributes
+ Fix incorrect address point in unit test of prometheus utils.
Follow <https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes-1>

Export resource for prometheus

---

bazel/repository.bzl

Fixes #2357
* In the `bazel` build, upgrade to curl 8.4.0
* The `CMake` build is not affected

[BUILD] Upgrade libcurl to version 8.4.0

---

opentracing-shim/CMakeLists.txt

Fixes #2355
Change the opentracing-shim include paths to be relative to opentelemetry-cpp directory, rather than the root cmake project directory. Those two directories will be different if opentelemetry-cpp is added to a larger project.
I also switched `include_directories` to `target_include_directories` as my understanding is that the latter is current best-practice. This necessitated gating the includes with a BUILD_INTERFACE generator expression. However, I don't think this change is required for this fix. I just wanted to improve it a little bit.

Fix behavior of opentracing-shim when added as subdirectory of a larger project

---

CMakeLists.txt

Fixes #2360 
+ Fix protoc searching with non-imported protobuf::protoc target.

Fix protoc searching with non-imported protobuf::protoc target.

---

CHANGELOG.md
api/CMakeLists.txt
api/include/opentelemetry/metrics/meter_provider.h
api/include/opentelemetry/metrics/noop.h
ci/do_ci.sh
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/src/metrics/meter_provider.cc
sdk/test/metrics/meter_provider_sdk_test.cc

Fixes #2363
* Removed redundant option `WITH_REMOVE_METER_PREVIEW`, used `WITH_ABI_VERSION_2`

[BUILD] Remove WITH_REMOVE_METER_PREVIEW, use WITH_ABI_VERSION_2 instead

---

sdk/include/opentelemetry/sdk/metrics/async_instruments.h
sdk/include/opentelemetry/sdk/metrics/state/observable_registry.h
sdk/src/metrics/async_instruments.cc
sdk/src/metrics/state/observable_registry.cc

Fixes #2373, #2081 
Added a function called CleanupCallbacks to ObservableRegistry that is called from the destructor of ObservableInstrument to remove back pointers from the registry. 

[SDK] Metrics ObservableRegistry Cleanup

---

CHANGELOG.md
CMakeLists.txt

Fixes #2365
* Promote option `WITH_OTLP_HTTP_SSL_PREVIEW` from experimental to stable
* Promote option `WITH_OTLP_HTTP_SSL_TLS_PREVIEW` from experimental to stable
* Change default for both to `ON`
After this change, SSL and TLS options will be included by default in the build.
It will still be possible to exclude the feature from the build, by setting options to `OFF`, only in release 1.13.0.
Once this change is shipped as part of the next release (v1.13.0), a subsequent PR will remove the options entirely for release 1.14.0.

[BUILD] Make WITH_OTLP_HTTP_SSL_PREVIEW mainstream

---

sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h
sdk/test/metrics/sum_aggregation_test.cc

Fixes #2377
In case of a matching view, the SDK picks the Aggregation with correct monotonic for DoubleUpDownCounter as [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/231ca4ade18c8cf691c9520d174b518feae78f35/sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h#L106). The problem was in the logic when there is no matching view, which is fixed now. Also added test for this scenario.

[SDK] Creating DoubleUpDownCounter with no matching view

---

CHANGELOG.md
api/include/opentelemetry/trace/noop.h
api/include/opentelemetry/trace/tracer_provider.h
api/test/singleton/singleton_test.cc
api/test/trace/provider_test.cc
sdk/include/opentelemetry/sdk/trace/tracer_provider.h
sdk/src/trace/tracer_provider.cc
sdk/test/trace/tracer_provider_test.cc

Fixes #2032
API:
* Implemented a new `GetTracer()` api with 4 parameters, only available in `ABI VERSION 2`
* Renamed parameters to be consistent with the spec.

[API] Add InstrumentationScope attributes in TracerProvider::GetTracer()

---

cmake/package.cmake

At the moment, when I follow the instructions for generating binary packages ([link](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/INSTALL.md#generating-binary-packages)), I can create a rpm with the correct name, but it has the wrong version configured (e.g. `0.1.1` instead of `1.12.0`):
```bash
$ rpm -qip opentelemetry-cpp-1.12.0-centos-7-x86_64.rpm
Name        : opentelemetry-cpp
----> Version     : 0.1.1
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : unknown
Size        : 55377670
License     : Apache-2.0
Signature   : (none)
Source RPM  : opentelemetry-cpp-0.1.1-1.src.rpm
Build Date  : Wed Oct 25 17:31:13 2023
Build Host  : [removed]
Relocations : /usr
Vendor      : OpenTelemetry
URL         : https://opentelemetry.io/
Summary     : …
```

[BUILD] Fix cpack broken package version

---

opentracing-shim/src/tracer_shim.cc
opentracing-shim/test/tracer_shim_test.cc

Adhere to change in opentelemetry-specification commit [Allow invalid but sampled SpanContext to be returned](https://github.com/open-telemetry/opentelemetry-specification/commit/b9c8a02f64ba86501b995649e957bba44e6712f5)

[opentracing-shim] Add check for sampled context

---

api/test/context/runtime_context_test.cc

Fixes a build error when building opentelemetry-cpp with the following config:
```
cmake .. -DWITH_STL=ON -DCMAKE_CXX_STANDARD=20
```
Building ``WITH_STL=ON`` in Windows x64 with Visual Studio 2022 causes the following errors:
```
D:\repos\test\opentelemetry-cpp\api\test\context\runtime_context_test.cc(134,17): error C2039: 'next_permutation': is not a member of 'std' [D:\repos\test\opentelemetry-cpp\build\api\test\context\runtime_cont
ext_test.vcxproj]
D:\vcpkg\installed\x64-windows\include\gtest/internal/gtest-internal.h(1324,11): message : see declaration of 'std' [D:\repos\test\opentelemetry-cpp\build\api\test\context\runtime_context_test.vcxproj]
D:\repos\test\opentelemetry-cpp\api\test\context\runtime_context_test.cc(134,33): error C3861: 'next_permutation': identifier not found …
```

[BUILD] Add missing includes to runtime_context_test

---

.github/repository-settings.md

Add file `.github/repository-settings.md`, to comply with community processes.
See the file content for details.

[ADMIN] Add file .github/repository-settings.md

---

CHANGELOG.md
sdk/src/logs/logger_provider.cc
sdk/test/logs/logger_provider_sdk_test.cc

[SDK] Fix GetLogger with empty library name

---

api/include/opentelemetry/metrics/noop.h
api/include/opentelemetry/metrics/sync_instruments.h
sdk/include/opentelemetry/sdk/metrics/sync_instruments.h
sdk/src/metrics/meter.cc
sdk/src/metrics/sync_instruments.cc
sdk/test/metrics/sync_instruments_test.cc

Fixes #2155 
This PR extracts the context related change in #2341, also the change of making `LongCounter` and `LongHistogram` as unsigned type is picked up.

[Metrics] Make context optional for histogram instruments in Metrics SDK

---

sdk/include/opentelemetry/sdk/metrics/data/exemplar_data.h
sdk/include/opentelemetry/sdk/metrics/exemplar/reservoir_cell.h

Fix references to trace namespace to be fully qualified

---

api/CMakeLists.txt
api/include/opentelemetry/common/spin_lock_mutex.h
api/include/opentelemetry/common/timestamp.h
api/include/opentelemetry/plugin/detail/dynamic_load_windows.h
exporters/ostream/include/opentelemetry/exporters/ostream/log_record_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
sdk/include/opentelemetry/sdk/logs/exporter.h
sdk/include/opentelemetry/sdk/logs/logger_context.h
sdk/include/opentelemetry/sdk/logs/processor.h
sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h
sdk/include/opentelemetry/sdk/metrics/aggregation/histogram_aggregation.h
sdk/include/opentelemetry/sdk/metrics/metric_reader.h
sdk/include/opentelemetry/sdk/metrics/state/metric_collector.h
sdk/include/opentelemetry/sdk/trace/exporter.h
sdk/src/logs/batch_log_record_processor.cc
sdk/src/metrics/aggregation/histogram_aggregation.cc
sdk/src/metrics/export/periodic_exporting_metric_reader.cc
sdk/src/metrics/meter_context.cc
sdk/src/trace/batch_span_processor.cc

Currently, including OpenTelemetry API requires NOMINMAX to be defined for Windows user which excludes the min/max macro from the Windows header files. There are cases when both macros are used by the customer code so requiring NOMINMAX will cause incompatibility. This PR wraps the usage of min/max from C++ standard library with parenthesis. This can avoid the naming conflict with the macro names min/max.

[BUILD] Remove defining NOMINMAX from api

---

api/include/opentelemetry/trace/propagation/detail/hex.h

Added missing header file in `hex.h`, required to declare `uint8_t`

[BUILD] 'uint8_t' not declared in this scope with gcc 13.2.1

---

api/include/opentelemetry/trace/trace_state.h
sdk/include/opentelemetry/sdk/metrics/view/predicate.h
sdk/src/metrics/instrument_metadata_validator.cc
sdk/test/metrics/histogram_test.cc
sdk/test/metrics/view_registry_test.cc

It used to be some places were checking for
defined(OPENTELEMETRY_HAVE_WORKING_REGEX), but it is always being set (to either 0 or 1) in api/include/opentelemetry/common/macros.h.
Thus move to just checking its value everywhere.
Additionally, even if we did have the feature off - compilation would fail, since not all the functions were ifdef'd. I assume this fails since there are not tests that have OPENTELEMETRY_HAVE_WORKING_REGEX as off.
My initial motivation for this was to reduce compile times, since specificing the definition with an std::regex adds a significant penalty to each translation unit (~700ms on my 5-year old laptop). In a separate patch, I think this should be moved to a .cc file - happy to receive advice on how (since api/ seems not to have .cc's).

[BUILD] Improve the handling of OPENTELEMETRY_HAVE_WORKING_REGEX.

---

CHANGELOG.md
api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #2419
Upgrade to:
* semantic conventions 1.23.1
* build-tools 0.23.0

[SEMANTIC CONVENTIONS] Upgrade to semconv version 1.23.1

---

api/include/opentelemetry/trace/span_context_kv_iterable_view.h
exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_recordable.h
exporters/zipkin/include/opentelemetry/exporters/zipkin/recordable.h
sdk/include/opentelemetry/sdk/common/global_log_handler.h
sdk/include/opentelemetry/sdk/instrumentationscope/instrumentation_scope.h
sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
sdk/include/opentelemetry/sdk/metrics/exemplar/fixed_size_exemplar_reservoir.h
sdk/include/opentelemetry/sdk/metrics/exemplar/histogram_exemplar_reservoir.h
sdk/include/opentelemetry/sdk/metrics/exemplar/reservoir.h
sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/include/opentelemetry/sdk/trace/span_data.h
sdk/src/trace/span.h

[BUILD] Use fully qualified references to trace/common namespace

---

cmake/opentelemetry-build-external-component.cmake

Extend `OPENTELEMETRY_EXTERNAL_COMPONENT_PATH` to support path list will help integration with multiple external exporters.

[BUILD] Accept path list in OPENTELEMETRY_EXTERNAL_COMPONENT_PATH

---

CHANGELOG.md
api/include/opentelemetry/std/span.h

NOMINMAX was removed in our API in below PR, but one more fix needed for a call of `::max` in the API. It was missed because this line is only hit when building for C++ 17 and above.
https://github.com/open-telemetry/opentelemetry-cpp/pull/2420

[BUILD] Fix removing of NOMINMAX on Windows

---

CHANGELOG.md
CMakeLists.txt
api/CMakeLists.txt
ci/do_ci.sh
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_metric_exporter_options.h
exporters/otlp/src/otlp_environment.cc
exporters/otlp/src/otlp_http_client.cc
exporters/otlp/src/otlp_http_exporter.cc
exporters/otlp/src/otlp_http_exporter_options.cc
exporters/otlp/src/otlp_http_log_record_exporter.cc
exporters/otlp/src/otlp_http_log_record_exporter_options.cc
exporters/otlp/src/otlp_http_metric_exporter.cc
exporters/otlp/src/otlp_http_metric_exporter_options.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc
exporters/zipkin/test/zipkin_exporter_test.cc
ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h
ext/include/opentelemetry/ext/http/client/http_client.h
ext/src/http/client/curl/http_client_curl.cc
ext/src/http/client/curl/http_operation_curl.cc
ext/test/http/curl_http_test.cc
functional/otlp/func_http_main.cc
test_common/include/opentelemetry/test_common/ext/http/client/nosend/http_client_nosend.h

Fixes #2383
CMake options `WITH_OTLP_HTTP_SSL_PREVIEW`
and `WITH_OTLP_HTTP_SSL_TLS_PREVIEW` are removed.
Building opentelemetry-cpp without SSL support is no longer possible.

[REMOVAL] Remove option WITH_OTLP_HTTP_SSL_PREVIEW

---

.github/workflows/ci.yml
CHANGELOG.md
api/include/opentelemetry/std/span.h
api/test/nostd/string_view_test.cc
api/test/nostd/variant_test.cc
ci/do_ci.ps1

[BUILD] Introduce CXX 20 CI pipeline for MSVC/Windows

---

buildscripts/semantic-convention/generate.sh

Fixes #2454
In SELINUX, mount docker volumes with the `:z` option, to share files with the parent.
Tested with `podman`, with SELINUX `Enforcing`

[SEMANTIC CONVENTIONS] Code generation script fails on SELINUX

---

exporters/prometheus/include/opentelemetry/exporters/prometheus/collector.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/collector.cc
exporters/prometheus/src/exporter.cc
exporters/prometheus/src/exporter_options.cc
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/collector_test.cc

Fixes #2442 (plus one bonus fix)
- Adds a new `populate_otel_scope` option to the `PrometheusExporterOptions` object defaulting to enabled, including an environment variable to control it
- Uses the option to enable/disable the `otel_scope_name` and `otel_scope_version` attributes added to instruments in Prometheus output
- Adds a new environment variable for controlling the `populate_target_info` option of `PrometheusExporterOptions`
I opted to use (abuse) the side effect of the scope variable being null for the actual disabling of the attributes here, instead of passing the option down through the method chain to where it's used. If that's undesirable, I can switch to passing it.

[EXPORTER] Add option to disable Prometheus otel_scope_name and otel_scope_version attributes

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_metric_utils.h
exporters/otlp/src/otlp_metric_utils.cc

Fixes #2466 
The Aggregation type should be detected by checking the variant type, and not the instrument type. As it is possible to change the Aggregation type for an instrument through View configuration.

Fix Aggregation type detection in OTLP Exporter

---

exporters/prometheus/src/exporter_utils.cc

Fixes #2463 
+ Remove the usage of regex in `PrometheusExporterUtils::CleanUpString`
+ I didn't tested but it should have better performance than using `std::regex_replace`, because it allocate less `std::string` objects.
+ Use explicit `std::string` constructor in `std::regex_replace` because some versions of gcc can not detect the types correctly.

Do not use regex in `CleanUpString` because some implementations of STL may crash.

---

docs/cpp-ostream-exporter-design.md
exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
exporters/elasticsearch/src/es_log_record_exporter.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter.h
exporters/otlp/src/otlp_http_client.cc
sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
sdk/include/opentelemetry/sdk/logs/multi_log_record_processor.h
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h

Fixes build failures after removal of NOMINMAX - previous commits from @ThomsonTan didn't have full coverage.

[EXPORTER and SDK] Additional fixes after NOMINMAX removal on Windows

---

CHANGELOG.md
exporters/otlp/src/otlp_metric_utils.cc
exporters/otlp/test/otlp_metrics_serialization_test.cc

Fixes #2469 
The `is_monotonic` flag is now set to `true` for both synchronous and asynchronous/observable counters. 

Set is_monotonic flag for Observable Counters

---

exporters/prometheus/include/opentelemetry/exporters/prometheus/collector.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/collector.cc
exporters/prometheus/src/exporter.cc
exporters/prometheus/src/exporter_options.cc
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/collector_test.cc

Fixes #2442
This renames the recently-new `populate_otel_scope` option to `without_otel_scope` to match the related docs changes.

[EXPORTER] Rename populate_otel_scope to without_otel_scope

---

examples/common/logs_foo_library/foo_library.cc
examples/logs_simple/README.md

[EXAMPLES] Use logs API instead of logs bridge API in the example

---

api/include/opentelemetry/nostd/internal/absl/base/policy_checks.h
api/include/opentelemetry/nostd/internal/absl/meta/type_traits.h
exporters/ostream/include/opentelemetry/exporters/ostream/common_utils.h

- https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus
- The change to `.../absl/base/policy_checks.h` is a back port from the same lines in the current Abseil `HEAD`
- I _think_ the rest of the uses of `__cplusplus` are correct under MSVC, but I'm not totally sure on that.

[BUILD] Fix checks on __cplusplus under MSVC, do not assume /Zc

---

api/include/opentelemetry/nostd/function_ref.h

Fixes #2495
+ Fix variable shadow in some old compilers.

[BUILD] Fix variable shadow

---

.github/workflows/ci.yml
ci/do_ci.sh

Part of #2470
The existing `cmake.c++20*.test` cases don't actually pin C++2020 but either don't use `WITH_STL=` at all or set it to `ON`. This results in a strange mix of "version" between the name of the test, the version the library _thinks_ is being used and what is actually being used by the build
Also, there was no explicit C++2023 tests.

[CI] Make cmake.c++20*.test actualy use C++20 and add cmake.c++23*.test

---

api/include/opentelemetry/common/spin_lock_mutex.h

Fixes #2500 
The multiple assignment operators for SpinLockMutex throws warnings in consumer build for these headers. This would require them to explicitly add #Pragma to ignore C4522.
This PR removes the redundant assignment to let the build pass without these warnings. Tested locally as I was able to repro this issue before this change.

[BUILD] Fix multiple assignment operators for SpinLockMutex

---

.github/workflows/ci.yml
api/include/opentelemetry/nostd/internal/absl/base/config.h
api/include/opentelemetry/nostd/internal/absl/meta/type_traits.h
api/test/common/spinlock_benchmark.cc

Fixes #2321
* Upgrade gcc from 12 to 13 in CI maintainer mode builds
* Upgrade clang from 14 to 15 in CI maintainer mode builds
* Fixed a new warning `[-Werror,-Wunused-but-set-variable]` in `spinlock_benchmark.cc`
* Backported the following fixes from abseil-cpp, to resolve clang-15 warnings.
1)
```
commit cfe27e79cfcbefb2b4479e04f80cbb299bc46965
Author: Abseil Team <absl-team@google.com>
Date:   Fri Aug 5 06:56:05 2022 -0700
Map the absl::is_trivially_* functions to their std impl
There's no point redefining these functions if they are supported by the compiler and the version of libstdc++. Also, some of the builtins used by the absl implementation of these functions (e.g. __has_trivial_destructor) have been deprecated in Clang 15. …
```

[BUILD] Clang-15 warning about `__has_trivial_destructor`

---

examples/metrics_simple/README.md

Move the installation pointer to the beginning to help user to find it.
Add the definition of counter name in the example code.

[EXAMPLES] Improve readme of Metrics example

---

CHANGELOG.md
api/include/opentelemetry/trace/propagation/b3_propagator.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/propagation/jaeger.h
api/test/context/propagation/composite_propagator_test.cc
api/test/trace/propagation/b3_propagation_test.cc
api/test/trace/propagation/http_text_format_test.cc
api/test/trace/propagation/jaeger_propagation_test.cc

[API] Fix b3, w3c and jaeger propagators: they will not overwrite the active span with a default invalid span
This is especially useful when used with CompositePropagator (#2504)
[TEST] Change wrong string "current-span" in unit tests to proper trace:kSpan which is "active_span"
Fixes #2504
This changes how Extract returns when invalid or missing headers are provided: it now returns the original context with potentially no active_span (or not overwritten if one was present).  
But this should not have side effects on client code which calls GetSpan(context), which answers a default invalid span when it does not find an active_span

[API] Propagators: do not overwrite the active span with a default invalid span

---

docs/building-with-stdlib.md

Fixes build break in CI related to table formats with pipe.

[DOC] Fixes CI markdown error MD055 - Table pipe style

---

api/BUILD

Fixes #2470 for Bazel.
Make Bazel build, by default, use the "current" actual C++ version as `OPENTELEMETRY_STL_VERSION`.
Note that some compilers use some "interesting" values for `__cplusplus` when asked to compiler for the most recent version they support. This can result in slightly unexpected results, but might actually be a good thing if those values indicate less than perfect support for the version in question and cause a downgrade to a better supported library.

[BUILD] Better handling of OPENTELEMETRY_STL_VERSION under Bazel.

---

exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h

There is a using of namespace `opentelemetry::exporter::etw` at the global scope in [etw_provider.h](https://github.com/open-telemetry/opentelemetry-cpp/blob/4700e483e09eb243251cd0bb9f0559f89237b41f/exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h#L53). It causes naming clash for any one who includes `etw_provider.h` which define the class name like `Logger` class.
This PR defines an alias on the namespace `opentelemetry::exporter::etw` instead of `using` it in global scope.

Remove namespace using in ETW exporter which affects global namespace

---

api/include/opentelemetry/trace/propagation/detail/hex.h
api/test/trace/propagation/CMakeLists.txt
api/test/trace/propagation/detail/BUILD
api/test/trace/propagation/detail/CMakeLists.txt
api/test/trace/propagation/detail/hex_test.cc

The conversion of hex to binary did not handle odd-length inputs correctly.
The output was zero-padded on the right rather than the left. On little endian machines, the second to last entry received the 0.
For example, "78cfcfec62ae9e9" would result in:
`0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00  0x78    0xcf    0xcf    0xec    0x62    0xae    0x9e    0x09`
The desired output is:
`0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00   0x07    0x8c    0xfc    0xfe    0xc6    0x2a    0xe9    0xe9`
I have attached a toy program to reproduce the problem:
[test_program.txt](https://github.com/open-telemetry/opentelemetry-cpp/files/14273830/test_program.txt)
Corrected conversion of hex to binary for propagation …

[API] Propagation: fix for hex conversion to binary for odd hex strings

---

exporters/otlp/src/otlp_grpc_client.cc

It seems like there is nothing checking whether the grpc exporter is actually empty, in which case it doesn't make sense to create a gRPC channel. This causes a problem in my application where we accidentally create a GrpcExporter with empty endpoint, which we never use because of a NOOP sampler. 
I believe it could be useful to log an error here, similar to when the endpoint is no valid URI.

[EXPORTER] Error when grpc endpoint is empty

---

CHANGELOG.md

#2488 caused a breaking change, that was not documented.
Add the missing changelog for release 1.14.0

[DOC] Add missing 1.14.0 CHANGELOG

---

sdk/include/opentelemetry/sdk/trace/recordable.h

Issue:
`Recordable::SetTraceFlags(...)` was added in v1.14.0. This was a breaking change. Consumers of this library would have to define an override for this method. Also, the latest version of opentelemetry-cpp would not be API compatible with older versions of consumers (which could not know about this new, pure virtual method).
https://github.com/open-telemetry/opentelemetry-cpp/pull/2488#discussion_r1493959370
Solution:
Provides a default implementation for `Recordable::SetTraceFlags(...)`.
The default implementation is sufficient for W3C Trace Context version 1, which is actually used.
To later support W3C Trace Context version 2, exporters are encouraged to capture trace flags, by providing an implementation in Recordable sub classes.
Limitation:
Note that this PR does not restore …

[SDK] Restore Recordable API compatibility with versions < 1.14.0

---

CHANGELOG.md
exporters/otlp/BUILD
exporters/otlp/CMakeLists.txt
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/src/otlp_environment.cc
exporters/otlp/src/otlp_http.cc
exporters/otlp/src/otlp_http_exporter_options.cc
exporters/otlp/src/otlp_http_log_record_exporter_options.cc
exporters/otlp/src/otlp_http_metric_exporter_options.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc

Fixes #2485 
+ Change OTLP HTTP content_type default to binary

Change OTLP HTTP content_type default to binary

---

CHANGELOG.md
exporters/otlp/BUILD
exporters/otlp/CMakeLists.txt
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_environment.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/src/otlp_environment.cc
exporters/otlp/src/otlp_http.cc
exporters/otlp/src/otlp_http_exporter_options.cc
exporters/otlp/src/otlp_http_log_record_exporter_options.cc
exporters/otlp/src/otlp_http_metric_exporter_options.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc

This reverts commit 719c60fd8ed5318baf93af4cd4b56e05c82b3488.

Reapply "Change OTLP HTTP content_type default to binary (#2558)"

---

sdk/src/resource/resource_detector.cc
sdk/test/resource/resource_test.cc

OTEL_SERVICE_NAME overrides OTEL_RESOURCE_ATTRIBUTES when it is defined.
Fixes #2559
Adds support for `OTEL_SERVICE_NAME` environmental variable to set "service.name".

[SDK] Support for OTEL_SERVICE_NAME

---

CMakeLists.txt

Fixes #1399
Also resolves the following deprecation warnings:
Starting with CMake 3.27, support for CMake < 3.5 is deprecated.
```
Changed in version 3.27: Compatibility with versions of CMake older than 3.5 is deprecated.
```
For some platforms, `CI` logs for opentelemetry-cpp now shows:
```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
```
* Bump cmake_minimum_required to 3.9
* at least 3.5 is required to clear the deprecation warning
* at least 3.9 is required because gtest is used, the previous requirement of 3.1 was incorrect.

[BUILD] Bump CMake minimum required version to 3.9

---

api/include/opentelemetry/common/macros.h
api/include/opentelemetry/logs/logger.h
exporters/otlp/src/otlp_log_recordable.cc
sdk/src/logs/read_write_log_record.cc
sdk/src/metrics/data/circular_buffer.cc

Contributes to #2572
* Remove the `OPENTELEMETRY_LIKELY_IF` macro
* This macro does not make sense because it includes the `if` itself, making it unusable for other constructs (for loops, while loops)
* Provide a `OPENTELEMETRY_LIKELY_CONDITION` macro
* To be used instead of `OPENTELEMETRY_LIKELY_IF`.
* Only one argument is supported instead of a `__VA_ARGS__`, to discourage `if OPENTELEMETRY_LIKELY_CONDITION (a = foo(), b = bar(), a > b)`
* This macro supports both compiler builtins for gcc and clang, and C++20.
* Provide a `OPENTELEMETRY_UNLIKELY_CONDITION` macro
* Provide a `OPENTELEMETRY_LIKELY` macro
* Provide a `OPENTELEMETRY_UNLIKELY` macro
With this change, likely / unlikely hints can be placed anywhere (for loops, while …

[BUILD] Provide LIKELY / UNLIKELY macros

---

exporters/otlp/src/otlp_metric_utils.cc

[EXPORTER] OTLP: Fix missing ResourceMetrics SchemaURL

---

bazel/repository.bzl
ci/setup_cmake.sh
third_party_release

Upgrade to googletest 1.14.0

---

.bazelrc
ci/do_ci.sh

This way it applies to local builds as well as CI builds
Related: https://github.com/open-telemetry/opentelemetry-cpp/pull/2599#issuecomment-2013188043

[bazel] Move -std=c++14 to .bazelrc

---

.bazelrc

https://github.com/open-telemetry/opentelemetry-cpp/pull/2600#issuecomment-2014023624

[bazel] Fix -std=c++14 warning on Windows

---

exporters/prometheus/CMakeLists.txt

Fixes #2605 
+ Do not link `prometheus-cpp::util` when it doesn't exist

Do not link `prometheus-cpp::util` when it doesn't exist

---

buildscripts/pre_release.sh
buildscripts/semantic-convention/generate.sh
ci/do_ci.sh
ci/install_abseil.sh
ci/install_protobuf.sh
ci/setup_grpc.sh
examples/prometheus/run.sh
functional/otlp/run_test.sh
functional/otlp/run_test_mode.sh
tools/build-benchmark.sh
tools/build-gtest.sh
tools/build-vcpkg.sh
tools/build.sh
tools/git-cl.sh
tools/install.sh
tools/setup-buildtools-mac.sh
tools/setup-buildtools.sh
tools/setup-cmake.sh
tools/setup-devenv.sh
tools/setup-ninja.sh

Numerous shell scripts were not using `set -e` or equivalent.  Additionally, make all scripts pass at least `shellcheck --severity=error` (basically just argument array quoting and exit values).  I can add an additional PR for using `shellcheck` in CI.

[MISC] Use set -e on all shell scripts and pass shellcheck --severity=error

---

.github/workflows/ci.yml

Pass all `.sh` files through `shellcheck --severity=error`.

[CI] Add shellcheck --severity=error as a CI step

---

examples/otlp/BUILD
examples/otlp/CMakeLists.txt
examples/otlp/file_log_main.cc
examples/otlp/file_main.cc
examples/otlp/file_metric_main.cc
exporters/otlp/README.md

Fixes #2626 
+ Add documents and examples for OTLP FILE exporters.

[DOC] Add readme and examples for OTLP FILE exporters.

---

buildscripts/semantic-convention/generate.sh
examples/grpc/client.cc
examples/grpc/server.cc
examples/http/client.cc
examples/http/server.cc
exporters/zipkin/src/recordable.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h
sdk/src/resource/resource.cc
sdk/src/resource/resource_detector.cc
sdk/test/resource/resource_test.cc

This fix is a follow up on #2633.
Context:
* https://github.com/open-telemetry/semantic-conventions/pull/758
* Service attributes such as `service.name` are no longer defined in resources.
* Instead, these attributes are defined in the `registry` as attribute_groups.
* The resource model contains a reference to `service.name` defined in the registry
When generating resource semantic conventions,
the code generation does not fail when a unknown reference to `service.name` is found,
which seems a bug for build tools, and the semantic convention `opentelemetry::sdk::resource::SemanticConventions::kServiceName` is not generated.
This causes a breaking change for instrumented applications.
Changes:
This fix changes the …

[SEMANTIC CONVENTIONS] Rework on semantic conventions 1.25.0

---

exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
sdk/include/opentelemetry/sdk/instrumentationscope/instrumentation_scope.h

Fixes #2647 
+ Use `nostd::enable_if_t` instead of `std::enable_if_t`

Use `nostd::enable_if_t` instead of `std::enable_if_t`

---

api/CMakeLists.txt

Fixes #2649 
+ Link CoreFoundation on apple systems

[BUILD] Link CoreFoundation on apple systems because some dependency packages require it

---

exporters/otlp/CMakeLists.txt

Fixes #2658
* Add an explicit dependency to `nlohmann_json` in test `otlp_file_client_test`.
* This is required to build with non standard install locations.

[BUILD] Build break in OLTP_FILE tests

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
exporters/elasticsearch/src/es_log_record_exporter.cc
exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/log_record_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/metric_exporter.h
exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
exporters/ostream/src/log_record_exporter.cc
exporters/ostream/src/metric_exporter.cc
exporters/ostream/src/span_exporter.cc
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
exporters/otlp/src/otlp_grpc_exporter.cc
exporters/otlp/src/otlp_grpc_log_record_exporter.cc
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter.h
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
exporters/zipkin/src/zipkin_exporter.cc

This is a follow up on PR #2553, to simplify `bool is_shutdown_` in general.
* Replace every use of a spin lock + boolean by an `std::atomic<bool>`
* Replace a spin lock by a mutex, when serializing to a file in the ostream metric exporter
* Implemented the missing call to `sout_.flush()` in `OStreamMetricExporter::ForceFlush()`

[EXPORTER] General cleanup for is_shutdown_ flags in exporters.

---

.github/workflows/ci.yml
ci/do_ci.sh

* Upgraded maintainer CI from gcc-13 on ubuntu 22-04 to gcc-14 on ubuntu 24-04
* This is required as gcc-13 was removed, see https://github.com/actions/runner-images/issues/9866
* Upgraded maintainer CI from clang-15 on ubuntu 22-04 to clang-18 on ubuntu 24-04
* Disabled include-what-you-use (IWYU)
* iwyu crashes on ubuntu 24-04, and testing under clang-18 is deemed more important
* The CI integration for iwyu was incomplete, producing logs that are never inspected and fixed
* More work is needed to integrate iwyu to produce a clean pass or fail (with logs) result, that can be enforced.

[CI] Upgrade Maintainers CI to ubuntu-24.04

---

bazel/repository.bzl
cmake/opentelemetry-proto.cmake

[BUILD] Upgrade to opentelemetry-proto 1.3.1

---

api/include/opentelemetry/logs/event_logger.h
api/include/opentelemetry/logs/logger.h
api/include/opentelemetry/logs/noop.h
api/test/logs/logger_test.cc
sdk/src/logs/logger.cc

Fixes #2656
Based on PR contribution #2662 from @yurishkuro
NoopLogger was incorrectly returning nullptr, causing segfaults in client code. After this change it returns a dummy no-op log record.

[API] Return NoopLogRecord from NoopLogger

---

api/include/opentelemetry/trace/trace_state.h

[BUILD] Remove the hard-coded separator in tracestate

---

api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
buildscripts/semantic-convention/templates/SemanticAttributes.h.j2
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

* Upgraded to semantic conventions release v1.26.0
* Implemented a workaround for a C++ name collision:
* deprecated semconv `messaging.client_id` is generated as `kMessagingClientId`
* semconv `messaging.client.id` is generated as `kMessagingClientId`
* removed code generation for `messaging.client_id`
See related:
* https://github.com/open-telemetry/semantic-conventions/issues/1031

[SEMANTIC CONVENTIONS] Upgrade to version 1.26.0

---

exporters/etw/include/opentelemetry/exporters/etw/etw_config.h
exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
exporters/etw/test/etw_logger_test.cc

Fixes #2680, this is the option 1 in the proposal with minor extension on defining a mapping for the table names. This makes it more flexible for the SDK users for configure the table name in the ETW exporter, without changing the API call in the instrumented libraries.

[ETW] Add table name mapping for Logs other than the default Log table

---

api/BUILD

A follow up to #2679.
This `bool_flag` was a part of the public API. If we remove it, anyone using it in downstream code have broken build commands.
So instead of removing it, I think we should mark it as deprecated.
```sh
$ bazelist build --//api:with_abseil //api:api
WARNING: opentelemetry-cpp/api/BUILD:8:10: target '//api:with_abseil' is deprecated: The value of this flag is ignored. Bazel builds always use Abseil's pre-adopted `std::` types. You should remove this flag from your build command.
INFO: Analyzed target //api:api (0 packages loaded, 545 targets configured).
INFO: Found 1 target...
Target //api:api up-to-date (nothing to build)
INFO: Elapsed time: 0.574s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
---
On removing …

[BUILD] Restore Bazel flag removed from public API

---

api/include/opentelemetry/baggage/baggage.h
api/include/opentelemetry/context/context.h
api/include/opentelemetry/context/runtime_context.h
ext/test/http/url_parser_test.cc
opentracing-shim/src/span_shim.cc
sdk/test/metrics/instrument_metadata_validator_test.cc

Fixes #2706 
Removed Unicode characters from API headers and `opentracing-shim/src/span_shim.cc`.
Escaped UTF-8 characters from test file data:
```
./ext/test/http/url_parser_test.cc: c program text, Unicode text, UTF-8 text
./sdk/test/metrics/instrument_metadata_validator_test.cc: c program text, Unicode text, UTF-8 text
```

[Code health] Remove Unicode Text from Source files

---

CMakeLists.txt

Fixes #2700 
+ Make `WITH_OTLP_GRPC_SSL_MTLS_PREVIEW` cached

[BUILD] Add option `WITH_OTLP_GRPC_SSL_MTLS_PREVIEW`

---

exporters/elasticsearch/src/es_log_record_exporter.cc
exporters/otlp/src/otlp_http_client.cc
exporters/zipkin/src/zipkin_exporter.cc

Fixes #2632 
According to https://datatracker.ietf.org/doc/html/rfc7231#page-47 . All 2xx return codes should be considered successful.

[EXPORTER] All 2xx return codes should be considered successful.

---

examples/etw_threads/BUILD

- None
* `etw_threads` example doesn't have `BUILD` file, we cannot run the example using Bazel as described here https://github.com/open-telemetry/opentelemetry-cpp/blob/main/CONTRIBUTING.md#build-and-run-code-examples
* This change adds the `BUILD` file for that example.

[Bazel] Add missing BUILD file

---

sdk/src/logs/batch_log_record_processor.cc
sdk/src/trace/batch_span_processor.cc

Added `.reserve` for `spans_arr` in BatchSpanProcessor (Small Optimization)
Helps to allocate the amount of memory needed for number of records so that dynamic memory allocation doesn't happen in the consume method.
`.push_back()` reallocates memory each time the method is called.
Using `.reserve()` would avoid memory reallocation as already the memory is allocated.
References:
[C++ Vector push_back](https://cplusplus.com/reference/vector/vector/push_back/)
[C++ Vector reserve](https://cplusplus.com/reference/vector/vector/reserve/)

 [SDK] Added reserve for spans array in BatchSpanProcessor.

---

docs/building-with-vcpkg.md

Fixes #2725
* Update existing links pointing to Vcpkg Triplets documentation.
* Replace the term "Custom triplets" by "Overlay triplets"

[DOC] Update "Using triplets" section in building-with-vcpkg documentation.

---

sdk/include/opentelemetry/sdk/logs/logger_provider.h

Removes `@param` comments  for `id_generator` and `sampler` in the `LoggerProvider` constructor, which are not present in the constructor.

[DOC] Remove comment for unused LoggerProvider initialization params

---

functional/otlp/otel-config-http.yaml
functional/otlp/otel-config-https.yaml
functional/otlp/otel-docker-config-http.yaml
functional/otlp/otel-docker-config-https.yaml

The opentelemetry-collector release v1.11.0/v0.104.0 contains a breaking change:
* https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.104.0
> The otlpreceiver now uses localhost by default instead of 0.0.0.0. This may break the receiver in containerized environments like Kubernetes. If you depend on 0.0.0.0 disable the component.UseLocalHostAsDefaultHost feature gate or explicitly set the endpoint to 0.0.0.0.
This broke the functional tests in CI.
Adjust the opentelemetry-collector configuration files used in functional tests to set explicitly an endpoint.

[TEST] Fix opentelemetry-collector bind address

---

exporters/ostream/include/opentelemetry/exporters/ostream/common_utils.h

Just a small fix - I think the correct fix is `void operator()(nostd::string_view &&arg)` (i.e. without const), at least if it was intended to overload the forwarding reference function above . Might also need `void operator()(const nostd::string_view &arg)` if both variants should be covered.

[EXPORTER] Fix references in AttributeValueVisitor

---

ci/fix-abseil-cpp-issue-1536.patch
ci/install_abseil.sh
tools/format.sh

Fixes #2998
* Backported a fix for abseil issue 1536, applied to abseil-cpp 20240116
* Fixed the CI format to ignore `*.patch` files

[CI] Build failures with ABSEIL 20240116 and CMAKE 3.30

---

exporters/otlp/src/otlp_file_client.cc

Fixes #3011 
+ Ignore exception when create thread failed.

[EXPORTER] Ignore exception when create thread in OTLP file exporter.

---

MODULE.bazel

Keep the version in `MODULE.bazel` consistent with other places (for example https://github.com/open-telemetry/opentelemetry-cpp/commit/baecbb95bd63df53e0af16e87bc683967962c5f8).

[BUILD] Update the version in MODULE.bazel

---

CMakeLists.txt

Currently, if support for gRPC is disabled by configuring the build with `-DWITH_OTLP_GRPC=OFF`, you are on Windows and do not use a toolchain file then the build will always use all third-party dependencies from vcpkg, regardless of whether nlohmann-json, abseil and protobuf were found or not.
The root cause for this behavior is a bug in the condition meant to check that all dependencies have been found, which unconditionally checks for `NOT gRPC_FOUND`, but the corresponding `find_package` call is only performed if `WITH_OTLP_GRPC` is true, and thus causing that condition to always evaluate to `true` if `WITH_OTLP_GRPC` is false.

[BUILD] Fix build without vcpkg on Windows when gRPC is disabled

---

api/BUILD

Fixes #3019
This change allows Bazel users to change the `OPENTELEMETRY_ABI_VERSION_NO`.
To specify the `OPENTELEMETRY_ABI_VERSION_NO` in a client project, simply add `build --@opentelemetry-cpp//api:abi_version_no=2` in the `.bazelrc`.

[BUILD] Add abi_version_no bazel flag.

---

.github/workflows/iwyu.yml

* Also cover unit tests code in the include-what-you-use build
This is needed to actually see reported issues in CI logs, to know what needs to be fixed.
It is a pre requisite to make more cleanup.

[Code health] Expand iwyu coverage to include unit tests.

---

exporters/otlp/test/otlp_file_exporter_test.cc
exporters/otlp/test/otlp_file_log_record_exporter_test.cc
exporters/otlp/test/otlp_file_metric_exporter_test.cc

[TEST] Fix sync problems in OTLP File exporter tests.

---

sdk/src/metrics/export/periodic_exporting_metric_reader.cc

[SDK] PeriodicExportingMetricReader: future is never set, blocks until timeout

---

sdk/src/metrics/export/periodic_exporting_metric_reader.cc
sdk/src/metrics/meter_context.cc

Also use steady clock consistently.
Prior to this change, the test would fail under ASAN:
```
$ bazel test --config=asan --test_output=errors //sdk/test/metrics:meter_provider_sdk_test
INFO: Analyzed target //sdk/test/metrics:meter_provider_sdk_test (0 packages loaded, 0 targets configured).
FAIL: //sdk/test/metrics:meter_provider_sdk_test (see /private/var/tmp/_bazel_punya/e3bd968ba61238cdeb1a5537fc3dbf7d/execroot/_main/bazel-out/darwin_arm64-fastbuild-asan/testlogs/sdk/test/metrics/meter_provider_sdk_test/test.log)
INFO: From Testing //sdk/test/metrics:meter_provider_sdk_test:
==================== Test output for //sdk/test/metrics:meter_provider_sdk_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up. …
```

Fix overflow in timeout logic

---

functional/otlp/otel-config-http.yaml

The logging exporter was renamed debug in 2023, the logging exporter will be removed in the near future, updating the example accordingly.

[TEST] update collector example with debug exporter

---

examples/otlp/opentelemetry-collector-config/config.dev.yaml

The logging exporter was renamed debug in 2023, the logging exporter will be removed in the near future, updating the example accordingly.

[EXAMPLE] update collector example with debug exporter

---

examples/otlp/opentelemetry-collector-config/config.dev.yaml
functional/otlp/otel-config-http.yaml
functional/otlp/otel-config-https.yaml
functional/otlp/otel-docker-config-http.yaml
functional/otlp/otel-docker-config-https.yaml

Missed some references in yesterday's PR and updated the verbosity to `detailed` where it was missed. This exporter has been replaced by the debug exporter and will be removed soon
Related to https://github.com/open-telemetry/opentelemetry-collector/pull/11037

[TEST] update references to logging exporter

---

examples/logs_simple/main.cc
examples/simple/main.cc

[EXAMPLE] Clean the tracer initialization in OStream example

---

exporters/etw/include/opentelemetry/exporters/etw/etw_fields.h
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h

[EXPORTER] Fix the format of SpanLink for ETW

---

CHANGELOG.md
exporters/memory/BUILD
exporters/memory/CMakeLists.txt
exporters/memory/include/opentelemetry/exporters/memory/in_memory_metric_data.h
exporters/memory/include/opentelemetry/exporters/memory/in_memory_metric_exporter_factory.h
exporters/memory/src/in_memory_metric_data.cc
exporters/memory/src/in_memory_metric_exporter_factory.cc
exporters/memory/test/in_memory_metric_data_test.cc
exporters/memory/test/in_memory_metric_exporter_test.cc

[EXPORTER] Implement in-memory metric exporter

---

CMakeLists.txt

about loongarch： https://docs.kernel.org/arch/loongarch/introduction.html
`
......
Start 413: exporter.OstreamLogExporter.DefaultLogRecordToCout
413/421 Test #413: exporter.OstreamLogExporter.DefaultLogRecordToCout ...................................................   Passed    0.00 sec
Start 414: exporter.OStreamLogRecordExporter.SimpleLogToCout
414/421 Test #414: exporter.OStreamLogRecordExporter.SimpleLogToCout ....................................................   Passed    0.00 sec
Start 415: exporter.OStreamLogRecordExporter.LogWithStringAttributesToCerr
415/421 Test #415: exporter.OStreamLogRecordExporter.LogWithStringAttributesToCerr ......................................   Passed    0.00 sec
Start 416: exporter.OStreamLogRecordExporter.LogWithVariantTypesToClog
416/421 Test #416: …

[BUILD] add loongarch info

---

ci/do_ci.sh
examples/otlp/README.md

Looks like otel-collector equal or higher than 0.86.0 has the "debug" exporter.

[CI] Update otel-collector version

---

exporters/prometheus/test/collector_test.cc
sdk/include/opentelemetry/sdk/metrics/export/metric_producer.h
sdk/include/opentelemetry/sdk/metrics/state/metric_collector.h
sdk/src/metrics/metric_reader.cc
sdk/src/metrics/state/metric_collector.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/periodic_exporting_metric_reader_test.cc

Following https://github.com/open-telemetry/opentelemetry-specification/blob/v1.36.0/specification/metrics/sdk.md#metricproducer.
Updates #1831
Updates `MetricProducer` to return a batch of metric points instead of receiving a callback.
* According to the spec, `Produce` SHOULD also take a Resource parameter, but I have chosen not to do that (because existing implementations pull the resource from the metric context). I'm not familiar with this area so I'd appreciate any advice.
* `MetricFilter` support isn't stable yet so I've kept it out of this initial PR.

[SDK] Update MetricProducer interface to match spec

---

exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
exporters/elasticsearch/src/es_log_record_exporter.cc

Fixes #3080 
When using the `ElasticsearchLogRecordExporter` we might need to add some http headers (auth or other required headers by our server). As of today there was no way of doing it for this exporter.
This PR aims to add this feature.
Like for the HttpLogRecordExporter, add the possibility to give custom http headers that will be added to each request. This is done by adding a `std::multimap` in which headers are added and then parsed when the request is being sent.

[EXPORTER] Add HttpHeaders in ElasticsearchLogRecordExporter

---

api/include/opentelemetry/trace/default_span.h

gcc <= 8, when building with -Wextra (and -Werror) wrongly raises this:
```
/data/mwrep/res/mdw/SIOTF/internal/opentelemetry_cpp/trace/18-0-0-7/include/opentelemetry/trace/default_span.h: In copy constructor 'opentelemetry::v1::trace::DefaultSpan::DefaultSpan(const opentelemetry::v1::trace::DefaultSpan&)':
/data/mwrep/res/mdw/SIOTF/internal/opentelemetry_cpp/trace/18-0-0-7/include/opentelemetry/trace/default_span.h:70:3: error: base class 'class opentelemetry::v1::trace::Span' should be explicitly initialized in the copy constructor [-Werror=extra]
DefaultSpan(const DefaultSpan &spn) noexcept : span_context_(spn.GetContext()) {}
^~~~~~~~~~~
```
See on Compiler Explorer here: https://godbolt.org/z/ed5rv74nT
I believe Jason Merrill fixed it in gcc for all gcc >= 9 with: …

[BUILD] Avoid buggy "should be explicitly initialized in the copy constructor" warning with gcc <= 8

---

exporters/memory/src/in_memory_metric_exporter_factory.cc
exporters/memory/test/in_memory_metric_data_test.cc

Fixes #3096 
+ Remove `std::make_unique`

[BUILD] Remove `std::make_unique`

---

exporters/memory/src/in_memory_metric_data.cc
exporters/memory/src/in_memory_metric_exporter_factory.cc

Fixes #3099
Fix remaining issues preventing a C++11 build with gcc 4.8.

[BUILD] Fix compiling problems for gcc 4.8

---

ext/test/http/CMakeLists.txt
test_common/src/http/client/nosend/CMakeLists.txt

Fixes #3102
+ Change the link order of gtest

[TEST] Fix linking order and gmock linking

---

exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
exporters/prometheus/src/exporter_options.cc
exporters/prometheus/src/exporter_utils.cc
exporters/prometheus/test/exporter_utils_test.cc

Fixes #2453 
Added the following optional configuration options (booleans) to the prometheus exporter:
- `without_units` : controls whether to add unit suffixes (e.g. `_seconds`) to the metric names.
- `without_type_suffix`: controls whether to add type suffixes (e.g. `_total`) to the metric names.

[EXPORTER] Add config options to prometheus exporter

---

api/include/opentelemetry/nostd/internal/absl/meta/type_traits.h

Fixes #3111
Removes `absl::aligned_storage`, which uses `std::aligned_storage`, which was deprecated in C++23.
Abseil removed its `aligned_storage` in https://github.com/abseil/abseil-cpp/commit/42133464db0ae5383fef723067835ef768b849f8

[BUILD] Remove aligned_storage from nostd

---

ext/src/http/client/curl/http_client_curl.cc

Currently, when building `-DWITH_OTLP_HTTP_COMPRESSION=OFF`, and not providing the libz dependency, we get this error:
```
...\opentelemetry-cpp\ext\src\http\client\curl\http_
client_curl.cc(6,10): error C1083: Cannot open include file: 'zconf.h': No such file or directory [...opentelemetry-cpp\build\ext\src\http\client\curl\opentelemetry_http_cli
ent_curl.vcxproj]
```
This fixes the issue by moving the `#include <zconf.h>` inside the corresponding #ifdef block, letting the build pass.
Do I need to do any of these? LMK, happy to :)
> * [ ] `CHANGELOG.md` updated for non-trivial changes
> * [ ] Unit tests have been added
> * [ ] Changes in public API reviewed

[BUILD] allow building with -DWITH_OTLP_HTTP_COMPRESSION=OFF without zlib

---

.github/workflows/ci.yml

Comment out CI for arm64, due to the lack of runners.

[CI] Comment the arm64 CI

---

.github/workflows/ci.yml
CHANGELOG.md
api/include/opentelemetry/common/string_util.h
api/include/opentelemetry/trace/propagation/detail/string.h
api/include/opentelemetry/trace/propagation/http_trace_context.h
api/include/opentelemetry/trace/trace_state.h
api/test/common/string_util_test.cc
api/test/trace/propagation/detail/BUILD
api/test/trace/propagation/detail/CMakeLists.txt
api/test/trace/propagation/detail/string_test.cc
ci/do_ci.sh
ext/include/opentelemetry/ext/http/server/http_server.h
ext/test/w3c_tracecontext_test/README.md
ext/test/w3c_tracecontext_test/main.cc

Fixes #74 
- Fixes the listed failures in w3c trace-context compliance test suite. 
- Adds a CI check which runs the w3c trace context tests for `SPEC_LEVEL=1`. 
- Test suites run are `TraceContextTest` & `AdvancedTest`.
*The following lists shows all the failing tests. Checked box indicates that the changes in this PR have fixed the test.*
**NOTE:** The tests above were part of test suites `TraceContextTest` & `AdvancedTest`. These test suites Trace Context Level 1 support.
All tests now passing. Test suites ran - `TraceContextTest` & `AdvancedTest`.

[API] Comply with W3C Trace Context

---

CHANGELOG.md
bazel/repository.bzl
docs/maintaining-dependencies.md
third_party_release

bumps prometheus from `1.2.4` to `v1.3.0`.

[EXPORTER] bump prometheus to v1.3.0

---

CMakeLists.txt
exporters/otlp/src/otlp_http_client.cc
ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h
ext/include/opentelemetry/ext/http/client/http_client.h
ext/src/http/client/curl/CMakeLists.txt
ext/src/http/client/curl/http_client_curl.cc
ext/src/http/client/curl/http_operation_curl.cc
test_common/include/opentelemetry/test_common/ext/http/client/nosend/http_client_nosend.h

Fixes #2250
Enable curl verbose output and add debug function callback to intercept the "interesting" logs.
This functionality is controlled by the compile-time flag/option `WITH_CURL_LOGGING=ON` but can also be enabled at runtime by setting `OtlpHttpExporterOptions::console_debug = true`.
By default, all the headers and other information are not available and protected by a compile-time flag since they could contain sensitive information.
An example of info logging related to TLS handshake, available by default:
```
[Info] File: /otel/ext/src/http/client/curl/http_operation_curl.cc:593 SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
```
An example of debug logging, enabled via `-DCURL_DEBUG`:
```
[Debug] File: …
```

[EXPORTER] Log SSL Connection Information

---

api/include/opentelemetry/common/spin_lock_mutex.h
api/test/common/spinlock_benchmark.cc

The yield instruction was introduced in ARM processors more recent than armel. So building in armel ends up in "Error: selected processor does not support `yield' in ARM mode". Also, the __yield() intrinsic instruction is not understood for armel by g++. So let's do nothing for armel.
This armel build CI job has the patch applied: https://salsa.debian.org/science-team/opentelemetry-cpp/-/jobs/6543996
Ref: https://developer.arm.com/documentation/ddi0406/b/Application-Level-Architecture/Application-Level-Programmers--Model/Exceptions--debug-events-and-checks/The-Yield-instruction?lang=en
Fixes #3128 
P.S. Example of other project handling similar instructions in different architectures: https://github.com/geidav/spinlocks-bench/blob/master/os.hpp#L31

[BUILD] Improve how to handle yield() in ARM.

---

api/include/opentelemetry/logs/event_logger.h
api/include/opentelemetry/logs/logger.h
api/include/opentelemetry/logs/logger_type_traits.h

Fixes #3124
Fix for `missing-template-arg-list-after-template-kw` warning.

[BUILD] Fix -Wmissing-template-arg-list-after-template-kw warning

---

.github/workflows/clang-tidy.yaml

This PR speeds up the `clang-tidy` workflow. Because `clang-tidy` only needs a compilation database generated by CMake, there's no need to waste time compiling the source code.
The only target we need to build is `opentelemetry_proto` because some other files depend on the files generated by the Protobuf compiler.
We can achieve further performance improvements by running `clang-tidy` jobs in parallel.
Before: 43:06 ([number of warnings](https://github.com/open-telemetry/opentelemetry-cpp/actions/runs/11842952186/job/33002781544#step:7:7): 114)
After: 14:30 ([number of warnings](https://github.com/sjinks/opentelemetry-cpp/actions/runs/11857382383/job/33045627282?pr=1#step:7:6): 114)

[CI] speed up `clang-tidy` workflow

---

.github/workflows/cppcheck.yml

Fixes #2297
- Added CI job for cppcheck. For now, it does not fail the build

[CI] Add cppcheck in the build

---

exporters/otlp/src/otlp_grpc_client.cc

Fix https://github.com/open-telemetry/opentelemetry-cpp/pull/3041#issuecomment-2486340845.

[BUILD] Fix error message

---

ext/include/opentelemetry/ext/http/common/url_parser.h
ext/test/http/url_parser_test.cc

This PR fixes issues found by `clang-tidy` in UrlParser.

[EXPORTER] fix clang-tidy warnings in UrlParser

---

exporters/prometheus/src/exporter_options.cc

Fixes #3170
Fixes the default behavior of emitting `otel_scope` attributes.

[PROMETHEUS_EXPORTER] Fix default for emitting otel_scope attributes

---

CMakeLists.txt

Fixes #3166
+ Upgrade the minimal requirement of cmake.

[BUILD] Upgrade cmake

---

opentracing-shim/include/opentelemetry/opentracingshim/propagation.h
opentracing-shim/include/opentelemetry/opentracingshim/shim_utils.h
opentracing-shim/src/span_context_shim.cc
opentracing-shim/src/span_shim.cc
opentracing-shim/src/tracer_shim.cc

Fixes #3180
All the conversions `opentracing::string_view` to `nostd::string_view` or backwards take the size as second argument.

[SHIM] Fix string_view mappings between OT and OTel

---

CMakeLists.txt

Change-Id: I931ff0ad1951473acd56ae3f5778ac11f7499caa
When cross-compiling, the `protoc` found through `find_package(Protobuf)` is not a binary that can be executed on the host and cannot be run. In the case of cross-compilation, it is necessary to specify the executable protoc program on the host.

[BUILD] Fix cross-compilation with protoc

---

exporters/memory/include/opentelemetry/exporters/memory/in_memory_span_exporter.h
sdk/include/opentelemetry/sdk/logs/exporter.h
sdk/include/opentelemetry/sdk/logs/logger_provider.h
sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/include/opentelemetry/sdk/metrics/push_metric_exporter.h
sdk/include/opentelemetry/sdk/trace/exporter.h
sdk/include/opentelemetry/sdk/trace/processor.h
sdk/include/opentelemetry/sdk/trace/tracer_provider.h
sdk/src/logs/logger_provider.cc
sdk/src/metrics/meter_context.cc
sdk/src/metrics/meter_provider.cc
sdk/src/trace/tracer_provider.cc

Fixes #3187
* Fixed several `::Shutdown()` methods, where the timeout parameter was missing
* Fixed implementation to forward the timeout parameter downstream, from providers to processors to exporters

[SDK] Tracer provider shutdown blocks in-definitively

---

ext/test/http/curl_http_test.cc

Fixes #3172
+ Change `is_called_` and `got_response_` to use atomic
Not sure if it can solve the problems, we can reopen it if it still exists.

[TEST] Change `is_called_` and `got_response_` to use atomic

---

api/include/opentelemetry/semconv/incubating/hw_metrics.h

Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.

update links to openmetrics to reference the v1.0.0 release

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/iwyu.yml

Fixes #3206
* Upgraded gcc version from 10 to 12 for some builds
* Set explicitly ubuntu-22.04 on some other builds, due to specific setup (gcov, libc++)
* Temporarily raise the acceptable include-what-you-use errors
* New iwyu errors are raised because the tool version was upgraded.
* New iwyu reports to be fixed independently

Fix CI on ubuntu-latest

---

exporters/otlp/test/otlp_recordable_test.cc

Fixes #3209
* Fixed a build break in unit tests, when using protoc 3.14

[BUILD] Build break using protoc 3.14

---

CHANGELOG.md

Fixes the CHANGELOG entry which was made under the earlier release by mistake

[EDITORIAL] fix changelog entry for PR 3185

---

.github/workflows/ci.yml
exporters/otlp/src/otlp_grpc_exporter.cc
functional/otlp/CMakeLists.txt
functional/otlp/Dockerfile
functional/otlp/func_grpc_main.cc
functional/otlp/otel-config-https-mtls.yaml
functional/otlp/otel-docker-config-https-mtls.yaml
functional/otlp/run_test.sh
functional/otlp/run_test_mode.sh

Fixes #2208 
- There was only a main for http functional tests so a _func_grpc_main_ was added following a similar pattern
- Add debug log line in OTLP grpc exporter to capture result in tests
- Reuse existing CI step "cmake_otprotocol_test" since it is the only one enabling WITH_OTLP_GRPC_SSL_MTLS_PREVIEW
- Minor tweaks to scripts to accommodate using both test binaries

[TEST] Functional tests for OTLP/gRPC with mutual TLS 

---

api/include/opentelemetry/semconv/http_metrics.h
api/include/opentelemetry/semconv/incubating/container_metrics.h
api/include/opentelemetry/semconv/incubating/db_metrics.h
api/include/opentelemetry/semconv/incubating/dns_metrics.h
api/include/opentelemetry/semconv/incubating/faas_metrics.h
api/include/opentelemetry/semconv/incubating/gen_ai_metrics.h
api/include/opentelemetry/semconv/incubating/http_metrics.h
api/include/opentelemetry/semconv/incubating/hw_metrics.h
api/include/opentelemetry/semconv/incubating/k8s_metrics.h
api/include/opentelemetry/semconv/incubating/messaging_metrics.h
api/include/opentelemetry/semconv/incubating/process_metrics.h
api/include/opentelemetry/semconv/incubating/rpc_metrics.h
api/include/opentelemetry/semconv/incubating/system_metrics.h
api/include/opentelemetry/semconv/incubating/vcs_metrics.h
buildscripts/semantic-convention/templates/registry/semantic_metrics-h.j2

Fixes #3226
* Fixed the semconv code generation for metrics, to emit the proper metric name

[SEMCONV] Metrics are incorrectly prefixed with `metric.`

---

examples/CMakeLists.txt
ext/src/dll/CMakeLists.txt

Fixes #3225
+ Add otlp for examples when include OTLP/file exporters only
+ Link OTLP/file exporters into standardalone dll.

[BUILD] Add OTLP/file exporter for dll and examples

---

api/include/opentelemetry/logs/severity.h

Fixes #3239
Added missing `cstdint` header for `uint8_t` type in `api/include/opentelemetry/logs/severity.h`.

[BUILD] Fix error ‘uint8_t’ does not name a type with gcc-15

---

CHANGELOG.md
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/otlp/test/otlp_grpc_metric_exporter_test.cc

Fixes #3242
OtlpGrpcMetricExporter throws on export when constructed with a shared grpc client. 
- Sets the `OtlpGrpcMetricExporter::aggregation_temporality_selector_` in the constructors that accept a shared grpc client 
- Adds test cases to cover `OtlpGrpcMetricExporter::GetAggregationTemporality`

[EXPORTER] fix throw in OtlpGrpcMetricExporter with shared grpc client

---

.github/workflows/ci.yml
ci/do_ci.sh
exporters/otlp/src/otlp_grpc_metric_exporter.cc
exporters/otlp/test/otlp_grpc_exporter_test.cc
exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
sdk/include/opentelemetry/sdk/common/global_log_handler.h
sdk/include/opentelemetry/sdk/resource/resource_detector.h
sdk/test/common/global_log_handle_singleton_lifetime_test.cc
sdk/test/resource/resource_test.cc

* Use grpc in maintainer CI : `WITH_OTLP_GRPC=ON`
* Fixed build warnings in grpc exporter
* Fixed remaining include-what-you-use warnings

[CI] Add GRPC in maintainer CI

---

.iwyu.imp
ext/src/http/client/curl/http_operation_curl.cc

Fixes #3252
* Indicate to include-what-you-use to not include header curl/system.h
* This fixes the build with CURL 7.29.0, where this header does not exist.

[BUILD] Build break with CURL 7.29.0

---

docs/cpp-sdk-factory-design.md
examples/otlp/grpc_log_main.cc

+ Add documents and samples for #3041 and #3010

[DOC] Add document and example for sharing gRPC Client

---

sdk/src/logs/batch_log_record_processor.cc

Fixes #3261
* In BatchLogRecordProcessor, used the same coding pattern in BatchSpanProcessor, so that proper OnEnd() instrumentation is called on shutdown.

[SDK] Fix BatchLogRecordProcessor to instrument shutdown

---

ci/do_ci.ps1
ci/setup_windows_ci_environment.ps1
exporters/otlp/test/otlp_grpc_exporter_test.cc
exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
exporters/otlp/test/otlp_grpc_metric_exporter_test.cc
exporters/otlp/test/otlp_http_exporter_test.cc
exporters/otlp/test/otlp_http_log_record_exporter_test.cc
exporters/otlp/test/otlp_http_metric_exporter_test.cc
ext/src/http/client/curl/http_client_curl.cc
ext/src/http/client/curl/http_operation_curl.cc

[TEST] OTLP in Windows builds

---

api/include/opentelemetry/nostd/type_traits.h
api/include/opentelemetry/std/type_traits.h
exporters/elasticsearch/src/es_log_recordable.cc
ext/src/http/client/curl/http_client_curl.cc

Fixes #3273 
+ Make type traits the same when `OPENTELEMETRY_STL_VERSION>=2011` or not
+ Do not use auto as parameter of lambda to support legacy toolchain.

[BUILD] Fixes compatibility of type_traits

---

sdk/src/metrics/instrument_metadata_validator.cc

Fix compilation with Regex disabled:
* It was missing an include for std::any_of
* Avoid declaring unused constants (at least my LLVM errors out)
I compiled it locally, and it works - but I assume either not-regex isn't covered by testing, our my use of LLVM 19 in my own code base means it was being more strict.

Fix compilation with Regex being disabled

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_log_recordable.h
exporters/otlp/src/otlp_log_recordable.cc
exporters/otlp/test/otlp_log_recordable_test.cc

Fixes #3201 
OtlpLogRecordable now supports exporting EventId::name

[EXPORTER] Support exporting event_name using OTLP Exporter

---

exporters/etw/include/opentelemetry/exporters/etw/TraceLoggingDynamic.h

Fixes #3237
Adding typecast without whom `c++latest` build fails. More details in #3237.

Adding typecast without whom c++latest build fails

---

CMakeLists.txt

Based on below doc, CMake 3.15 introduced policy CMP0092 which removes `/W3` option by default for MSVC. This change restores the old behavior of CMP0092 to keep `/W3` for MSVC, before we set the warning level explicitly for the project.
[CMakeLists](https://cmake.org/cmake/help/latest/policy/CMP0092.html#policy:CMP0092)

[BUILD] Enable old behavior of CMP0092

---

exporters/etw/include/opentelemetry/exporters/etw/etw_config.h
exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
exporters/etw/test/etw_logger_test.cc

Add macro `OPENTELEMETRY_ATTRIBUTE_TIMESTAMP_PREVIEW` to ETW exporter to support exporting a given 64-bit integer as timestamp type, because timestamp is not supported in the attribute type.

[ETW] Add configuration to export 64-bit integer as timestamp

---

api/include/opentelemetry/logs/logger.h

The parameter pack sent to `EmitLogRecord` is unpacked from right to left, which are caused by passing them as function parameters to template function `IgnoreTraitResult`. This will send the rightmost `attributes` parameter to the processor and then pass it to the `Recordable`. It makes it a little hard to do serialization in the `Recordable` interface, because the serialization usually needs to encode the data like event name or severity before encoding the attributes.
This PR changes the unpack order to help do serialization in the `Recordable` interface in a straightforward way, without caching any attributes.

[API] Change the param-pack unpacking order to start from left to right

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/metrics/export/metric_filter.h
sdk/include/opentelemetry/sdk/metrics/export/metric_producer.h
sdk/include/opentelemetry/sdk/metrics/meter_context.h
sdk/include/opentelemetry/sdk/metrics/meter_provider.h
sdk/include/opentelemetry/sdk/metrics/state/metric_collector.h
sdk/src/metrics/meter_context.cc
sdk/src/metrics/meter_provider.cc
sdk/src/metrics/state/metric_collector.cc
sdk/test/metrics/CMakeLists.txt
sdk/test/metrics/async_metric_storage_test.cc
sdk/test/metrics/common.cc
sdk/test/metrics/histogram_aggregation_benchmark.cc
sdk/test/metrics/histogram_aggregation_test.cc
sdk/test/metrics/histogram_test.cc
sdk/test/metrics/metric_collector_test.cc
sdk/test/metrics/metric_reader_test.cc
sdk/test/metrics/periodic_exporting_metric_reader_test.cc
sdk/test/metrics/sum_aggregation_benchmark.cc
sdk/test/metrics/sum_aggregation_test.cc

Fixes #2447
This PR implements the MetricFilter [spec](https://github.com/open-telemetry/opentelemetry-specification/pull/3566) in `opentelemetry-cpp`.

[SDK] Implement spec: MetricFilter

---

examples/grpc/tracer_common.h

Building the sample on Windows, the gRPC sample server/client app fails to function correctly. The propagated trace context is corrupted, containing garbage characters after the trace parent string.
The string buffer from gRPC cannot be safely treated as a null-terminated C-string. To ensure safe copying, we must use its length property instead.

fix: buffer overrun in the gRPC sample project

---

api/test/singleton/singleton_test.cc

Fixes #3315 
- add conditional to load the .dylib shared library files on macos in the singleton test

[TEST] fix segfault in singleton test with cmake on macos-latest

---

exporters/elasticsearch/src/es_log_recordable.cc

Fixes #3278
Removes the conditional that switches to std::format on cxx20 in es_log_recordable.cc. 

[TEST] fix test failure with elasticsearch exporter on cxx20

---

.github/workflows/ci.yml
exporters/elasticsearch/src/es_log_recordable.cc

Fixes #3312
The system package of nlohmann_json is version 3.10.5 on Ubuntu 22.04. 
- Add a template specialization of the `json_assign_visitor` to handle `nostd::span` attribute values. 
- Switch one runner that builds the elastic search exporter (runs ./ci/do_ci.sh cmake.test) to Ubuntu 22.04 and CXX_STANDARD=17

[BUILD] Fix elasticsearch exporter json compatibility

---

CHANGELOG.md
ext/src/dll/input.src

Add the missing exported definition for DLL build.

[BUILD] Fix misssing exported definition for OTLP file exporter and forceflush

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_client_factory.h
exporters/otlp/test/otlp_grpc_exporter_factory_test.cc
exporters/otlp/test/otlp_grpc_log_record_exporter_factory_test.cc
exporters/otlp/test/otlp_grpc_metric_exporter_factory_test.cc

Fixes #3320 
+ Remove the gRPC header dependency of `OtlpGrpcClientFactory`

[BUILD] Remove gRPC header including in `OtlpGrpcClientFactory`.

---

README.md

Add Pranav Sharma in cpp-approvers.
Accepting the invite in https://github.com/open-telemetry/opentelemetry-cpp/pull/3314#issuecomment-2749383669.

Add Pranav Sharma in cpp-approvers

---

.github/workflows/ci.yml

Fixes #3329
* Upgrade CI from ubuntu 20.04 to ubuntu 22.04
* Disable CI tests using abseil, to be revisited after PR #3318

[CI] Upgrade CI to ubuntu 22.04

---

.github/workflows/ci.yml
.github/workflows/iwyu.yml
ci/setup_cmake.ps1
ci/setup_cmake.sh

Pin cmake to version 3.31.6 in ci
- changes the `setup_cmake.sh` script to remove the system installed cmake and install a specific version from env var CMAKE_VERSION that defaults to 3.31.6
- adds a `setup_cmake.ps1` script for windows that does the same
- call the scripts in the ci workflow where needed

pin cmake in ci and devcontainer

---

install/conan/conanfile_latest.txt
install/conan/conanfile_stable.txt

the cmake install tests based on conan are failing due to the bzip2 server being down. Remove bzip2 from the build it is not needed. 
- remove bzip2 from the install/conan/conanfile* files

[CI] disable bzip2 in conan builds

---

api/include/opentelemetry/logs/logger.h

This PR one of a set PRs that used to address #3370 .
Fix the documentation comments of `logger.h` under API

[DOC] Fix documentation tags in logger API

---

api/include/opentelemetry/nostd/internal/absl/base/options.h

Fixes #3359 
There will be warning when using `-std=c++17` in the trunk version of GCC.
The issues were first reported in <https://github.com/open-telemetry/opentelemetry-cpp/issues/3121#issuecomment-2790880867> .
+ Using `<version>`to import feature checking macros in C++20
+ Using `<iso646.h>` to avoid warnings in C++17

Fixes warnings of ciso646 in C++17

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
sdk/test/metrics/attributes_hashmap_benchmark.cc

Use nostd::function_ref in AttributesHashMap for `aggregation_callback`.
A benchmark at https://github.com/grpc/grpc/blob/507a5de9483c9b8675e626977a51d9286f4104f0/test/cpp/microbenchmarks/bm_stats_plugin.cc#L81. shows time go down from 200+ns to ~20ns.
Additionally, with the benchmarks run by @psx95 on BM_AttributseHashMap -
Current HEAD ([merged PR#3383](https://github.com/open-telemetry/opentelemetry-cpp/actions/runs/14851261737/job/41708957121?pr=3383)):
```
"benchmarks": [
{
"name": "BM_AttributseHashMap",
"family_index": 0,
"per_family_instance_index": 0,
"run_name": "BM_AttributseHashMap",
"run_type": "iteration",
"repetitions": 1,
"repetition_index": 0,
"threads": 1,
"iterations": 7,
"real_time": 3.8004398345947266e+07,
"cpu_time": 2.0847316142857142e+07,
"time_unit": "ns"
}
]
``` …

[Metrics SDK] Use nostd::function_ref in AttributesHashMap

---

examples/otlp/http_instrumented_main.cc

Fixes unused var

---

INSTALL.md

Fixes #3408
- reference the `opentelemetry-cpp::trace` target instead of the interface only `opentelemetry-cpp::sdk` target
- add a note about the etw and elasticsearch components potential to be moved out of the core package

[DOCS] update the INSTALL guide on cmake components

---

examples/CMakeLists.txt
examples/batch/CMakeLists.txt
examples/common/CMakeLists.txt
examples/common/foo_library/CMakeLists.txt
examples/common/logs_foo_library/CMakeLists.txt
examples/common/metrics_foo_library/CMakeLists.txt
examples/etw_threads/CMakeLists.txt
examples/grpc/CMakeLists.txt
examples/http/CMakeLists.txt
examples/logs_simple/CMakeLists.txt
examples/metrics_simple/CMakeLists.txt
examples/multi_processor/CMakeLists.txt
examples/multithreaded/CMakeLists.txt
examples/otlp/CMakeLists.txt
examples/plugin/load/CMakeLists.txt
examples/plugin/plugin/CMakeLists.txt
examples/prometheus/CMakeLists.txt
examples/simple/CMakeLists.txt
examples/zipkin/CMakeLists.txt
ext/src/dll/CMakeLists.txt
install/test/cmake/component_tests/ext_dll/CMakeLists.txt

Fixes #3399
Updates the examples' cmake files to use the read-only ALIAS targets of `opentelemetry-cpp` added by https://github.com/open-telemetry/opentelemetry-cpp/pull/3368 and to use explicitly scoped target properties. 
- Use public read-only `opentelemetry-cpp` ALIAS targets (ie: `opentelemetry-cpp::api` in place of `opentelemetry_api`)
- Use `target_compile_definitions` in place of `add_definitions` 
- Use `target_include_directories` in place of `include_directories`
- Add explicit scope keywords (ie: `PRIVATE`, `PUBLIC`) to `target_link_libraries`
- Remove some redundant target linking and includes
- Rely on the transitive `PUBLIC` target properties (definitions, linked libraries, include directories) 
-  Replace `CMAKE_THREAD_LIBS_INIT` with the `Threads::Threads` target where …

[CMAKE] update cmake files in examples directory

---

sdk/src/metrics/aggregation/base2_exponential_histogram_aggregation.cc
sdk/test/metrics/aggregation_test.cc

Fixes #3424 
- Add a test to cover merging two Base2ExponentialHistogramAggregation instances where one has empty buckets
- Update Base2ExponentialHistogramAggregation::Merge to shortcut if merging a histogram with no counts
- Check if buckets are empty before down scaling

[SDK] Fix Base2ExponentialHistogramAggregation Merge with empty buckets

---

CHANGELOG.md
CMakeLists.txt
examples/common/foo_library/foo_library.cc
examples/common/logs_foo_library/foo_library.cc
exporters/prometheus/CMakeLists.txt
exporters/zipkin/CMakeLists.txt
ext/test/http/CMakeLists.txt
ext/test/w3c_tracecontext_http_test_server/CMakeLists.txt
functional/otlp/CMakeLists.txt
sdk/CMakeLists.txt
sdk/src/common/CMakeLists.txt
sdk/src/resource/CMakeLists.txt
sdk/test/common/CMakeLists.txt
sdk/test/instrumentationscope/CMakeLists.txt

More cmake cleanup. 
- Remove more global `include_directories` calls in favor of `target_include_directories`. Make sure the targets relying on these global includes link/include what they need. 
- Make the api target an interface link to the sdk target
- Remove usage of the sdk headers in the `foo_*` example libraries (These example libraries should link to the api only)

[CMAKE] remove global include_directories usage and rely on target properties

---

examples/http/BUILD
ext/src/http/client/curl/BUILD
ext/test/http/CMakeLists.txt

Removed the `WITH_CURL` build flag from the code base, it is set but never used.

[BUILD] remove unused WITH_CURL build flag

---

examples/otlp/CMakeLists.txt

Since the same target was linked with `PRIVATE` keyboard (see below), it should have explicit keyword for all the dependencies. Or there will be CMake error like the following.
```cmake
target_link_libraries(
example_otlp_instrumented_http PRIVATE common_metrics_foo_library
```
> CMake Error at examples/otlp/CMakeLists.txt:117 (target_link_libraries):
> The keyword signature for target_link_libraries has already been used with
> the target "example_otlp_instrumented_http".  All uses of
> target_link_libraries with a target must be either all-keyword or
> all-plain.

[BUILD] Add missing CMake keyword for target_link_libraries

---

.devcontainer/Dockerfile.dev
.github/workflows/clang-tidy.yaml
.github/workflows/iwyu.yml
ci/install_iwyu.sh
ci/setup_ci_environment.sh

Fixes #3453
Build iwyu to upgrade to version 0.22 and fix the segfault.
- adds an iwyu install script and uses it in the ci workflow and devcontainer
- install grpc with apt on the iwyu ci runner
- remove installing iwyu apt package elsewhere

[CI] build iwyu

---

.github/workflows/cmake_install.yml
CHANGELOG.md
ci/do_ci.ps1
examples/batch/CMakeLists.txt
examples/common/foo_library/CMakeLists.txt
examples/common/logs_foo_library/CMakeLists.txt
examples/common/metrics_foo_library/CMakeLists.txt
examples/etw_threads/CMakeLists.txt
examples/grpc/CMakeLists.txt
examples/grpc/client.cc
examples/grpc/server.cc
examples/logs_simple/CMakeLists.txt
examples/metrics_simple/CMakeLists.txt
examples/multi_processor/CMakeLists.txt
examples/multithreaded/CMakeLists.txt
examples/otlp/grpc_metric_main.cc
examples/plugin/CMakeLists.txt
examples/simple/CMakeLists.txt
ext/src/dll/CMakeLists.txt
install/test/cmake/CMakeLists.txt
install/test/cmake/examples_test/CMakeLists.txt

Contributes to #454
Adds initial CI testing of examples to address #454
Part 1 focuses on adding a basic tests to: 
1. Build all examples against the installed opentelemetry-cpp package to verify
- only imported/alias targets are used
- examples don't rely on internal cmake functions or global includes/declarations
2. Run a simple test of the single process examples to ensure they run and exit cleanly. These tests are added when `WITH_EXAMPLES` and `BUILD_TESTING` CMake options are ON.
- examples/batch
- examples/simple
- examples/logs_simple
- examples/metrics_simple
- examples/multithreaded
- examples/multi_processor
- examples/etw_threads
- examples/plugin
The multi-process examples are not run and can be addressed in a future PR. 
- Remove internal cmake functions from the grpc …

[TEST] test examples in CI with CMake Part 1

---

api/CMakeLists.txt

A trivial patch which allows opentelemetry to be built with CXX26.
I successfully compiled it locally with gcc (GCC) 15.1.1

[BUILD] Allow compilation with CXX26

---

.github/workflows/ci.yml
.github/workflows/cmake_install.yml

Fixes #3461
* Upgraded windows-2019 CI to windows-2022 / windows-2025

[CI] Remove windows 2019

---

exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_client.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_client_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_client_runtime_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_exporter_runtime_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_log_record_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_log_record_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_log_record_exporter_runtime_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_metric_exporter.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_metric_exporter_options.h
exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_metric_exporter_runtime_options.h
exporters/otlp/src/otlp_file_exporter_options.cc
exporters/otlp/src/otlp_file_log_record_exporter_options.cc
exporters/otlp/src/otlp_file_metric_exporter.cc
exporters/otlp/src/otlp_file_metric_exporter_options.cc

Contributes to https://github.com/open-telemetry/opentelemetry-cpp/issues/2053
Fixes clang-tidy warnings with the OTLP File component
- cppcoreguidelines-slicing
- cppcoreguidelines-avoid-const-or-ref-data-members
- cppcoreguidelines-special-member-functions

[CodeHealth] Fix clang-tidy warnings part 5

---

sdk/include/opentelemetry/sdk/configuration/extension_log_record_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_log_record_processor_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_pull_metric_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_push_metric_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_sampler_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_span_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/extension_span_processor_configuration.h

This is a partial fix, that implements supporting declarations.
* Implement the extension model for file configuration.

[CONFIGURATION] File configuration - extension model

---

sdk/include/opentelemetry/sdk/configuration/attribute_limits_configuration.h
sdk/include/opentelemetry/sdk/configuration/attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/attribute_value_configuration_visitor.h
sdk/include/opentelemetry/sdk/configuration/attributes_configuration.h
sdk/include/opentelemetry/sdk/configuration/boolean_array_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/boolean_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/detectors_configuration.h
sdk/include/opentelemetry/sdk/configuration/double_array_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/double_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/headers_configuration.h
sdk/include/opentelemetry/sdk/configuration/include_exclude_configuration.h
sdk/include/opentelemetry/sdk/configuration/integer_array_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/integer_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/otlp_http_encoding.h
sdk/include/opentelemetry/sdk/configuration/otlp_http_log_record_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/otlp_http_span_exporter_configuration.h
sdk/include/opentelemetry/sdk/configuration/propagator_configuration.h
sdk/include/opentelemetry/sdk/configuration/resource_configuration.h
sdk/include/opentelemetry/sdk/configuration/string_array_attribute_value_configuration.h
sdk/include/opentelemetry/sdk/configuration/string_array_configuration.h
sdk/include/opentelemetry/sdk/configuration/string_attribute_value_configuration.h

This is a partial fix, that implements supporting declarations.
* Implement the miscellaneous model for file configuration.

[CONFIGURATION] File configuration - misc model

---

CMakeLists.txt
cmake/opentelemetry-proto.cmake

- Switch opentelemetry-proto to use the FetchContent module instead of the ExternalProject module. 
- Set and log the opentelemetry-proto_VERSION and opentelemetry-proto_PROVIDER variables.

[CMAKE] Switch opentelemetry-proto to use FetchContent

---

.github/workflows/cmake_install.yml
CHANGELOG.md

Follow up to https://github.com/open-telemetry/opentelemetry-cpp/pull/3435
- add test step to the CMake install ci workflow that builds shared otel-cpp libs linked to the latest static protobuf and grpc libs.

[TEST] Shared otel-cpp libs linked to latest static protobuf and grpc

---

CHANGELOG.md
ext/src/dll/input.src
sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader_options.h
sdk/src/metrics/CMakeLists.txt
sdk/src/metrics/export/periodic_exporting_metric_reader_options.cc
sdk/test/metrics/periodic_exporting_metric_reader_test.cc

Fixes #3515 
Implements the configuration of `PeriodicExportingMetricReader` via environment variables with default values.
It introduces support for:
*   `OTEL_METRIC_EXPORT_INTERVAL` (Duration)
*   `OTEL_METRIC_EXPORT_TIMEOUT` (Timeout)
**Known Limitation / Discussion Point:**
During implementation, I identified that the existing utility function `common::GetDurationEnvironmentVariable` is not fully compliant with the specification for `Timeout` types.
*   **Specification:** A `Timeout` value of `0` SHOULD be interpreted as "infinite".
*   **Current Implementation:** The underlying parser (`GetTimeoutFromString`) explicitly rejects a value of `0` as invalid.
To keep the scope of this PR focused on the `PeriodicExportingMetricReaderOptions`, I have used the existing utility for both …

[SDK] Implement env var configuration for PeriodicExportingMetricReader

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/metrics/exemplar/reservoir_utils.h

Set _SimpleFixedSizeExemplarReservoir_ default size for exponential histograms based on configured maximum bucket count as recommended in the spec:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.46.0/specification/metrics/sdk.md#exemplar-defaults
> Base2 Exponential Histogram Aggregation SHOULD use a SimpleFixedSizeExemplarReservoir with a reservoir equal to the smaller of the maximum number of buckets configured on the aggregation or twenty (e.g. min(20, max_buckets)).
Note that I didn't update any tests (yet) - I couldn't find any existing tests for the fixed size reservoir? Thus wasn't sure if explicit tests are needed or if this is considered small / covered by other tests?

[SDK] Update default exemplar reservoir size for exponential histograms

---

sdk/include/opentelemetry/sdk/configuration/configured_sdk.h
sdk/include/opentelemetry/sdk/configuration/sdk_builder.h
sdk/include/opentelemetry/sdk/configuration/unsupported_exception.h
sdk/include/opentelemetry/sdk/configuration/view_selector_configuration.h
sdk/src/configuration/configured_sdk.cc
sdk/src/configuration/sdk_builder.cc

This is a partial fix, that implements the sdk builder.
* Implement the sdk builder:
* Create opentelemetry-cpp SDK objects from the configuration model.

[CONFIGURATION] File configuration - sdk builder

---

sdk/include/opentelemetry/sdk/configuration/extension_metric_producer_configuration.h
sdk/include/opentelemetry/sdk/configuration/metric_producer_configuration_visitor.h
sdk/include/opentelemetry/sdk/configuration/open_census_metric_producer_configuration.h
sdk/include/opentelemetry/sdk/configuration/propagator_configuration.h
sdk/src/configuration/configuration_parser.cc
sdk/src/configuration/sdk_builder.cc
sdk/test/configuration/yaml_metrics_test.cc
sdk/test/configuration/yaml_propagator_test.cc

This is a partial fix, to align on the declarative configuration specs version 1.0.0-rc1
Adjusted the implementation to recent spec changes:
* https://github.com/open-telemetry/opentelemetry-configuration/pull/187
* Changed the composite propagator from an array of strings to an array of objects
* Added composite_list
* Adjusted the yaml parser accordingly
* Added unit tests
* Adjusted the SDK builder accordingly
* https://github.com/open-telemetry/opentelemetry-configuration/pull/180
* Adjusted the yaml parser accordingly
* Adjusted unit tests
* https://github.com/open-telemetry/opentelemetry-configuration/pull/90
* The support for MetricProducer was incomplete
* Added supporting configuration classes
* Adjusted …

[CONFIGURATION] File configuration - spec version 1.0.0-rc1

---

sdk/include/opentelemetry/sdk/logs/batch_log_record_processor_options.h
sdk/include/opentelemetry/sdk/resource/resource.h
sdk/src/resource/resource.cc

Remove restrictions on resource creation.
* Remove restrictions on resource creation in the SDK.
* With declarative configuration, resources can be created after parsing a `config.yaml` file, calling a resource detector is no longer the only way to build a resource.

[CONFIGURATION] File configuration - sdk resource

---

exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
exporters/prometheus/include/opentelemetry/exporters/prometheus/prometheus_pull_builder.h
exporters/prometheus/src/exporter_options.cc
exporters/prometheus/src/prometheus_pull_builder.cc

This is a partial fix, to implement the prometheus exporter builder.
* Add a new option constructor, that ignores environment variables
* Implement the prometheus exporter builder

[CONFIGURATION] File configuration - prometheus exporter builder

---

CMakeLists.txt

[BUILD] Remove cmake support for thrift as Jaeger was removed

---

.github/workflows/ci.yml
.github/workflows/cmake_install.yml
CHANGELOG.md
CMakeLists.txt
INSTALL.md
install/cmake/CMakeLists.txt
install/test/cmake/CMakeLists.txt
install/test/cmake/component_tests/api/CMakeLists.txt
install/test/cmake/component_tests/exporters_elasticsearch/CMakeLists.txt
install/test/cmake/component_tests/exporters_etw/CMakeLists.txt
install/test/cmake/component_tests/exporters_in_memory/CMakeLists.txt
install/test/cmake/component_tests/exporters_ostream/CMakeLists.txt
install/test/cmake/component_tests/exporters_otlp_common/CMakeLists.txt
install/test/cmake/component_tests/exporters_otlp_file/CMakeLists.txt
install/test/cmake/component_tests/exporters_otlp_grpc/CMakeLists.txt
install/test/cmake/component_tests/exporters_otlp_http/CMakeLists.txt
install/test/cmake/component_tests/exporters_prometheus/CMakeLists.txt
install/test/cmake/component_tests/exporters_zipkin/CMakeLists.txt
install/test/cmake/component_tests/ext_common/CMakeLists.txt
install/test/cmake/component_tests/ext_dll/CMakeLists.txt
install/test/cmake/component_tests/ext_http_curl/CMakeLists.txt
install/test/cmake/component_tests/sdk/CMakeLists.txt
install/test/cmake/component_tests/shims_opentracing/CMakeLists.txt
install/test/cmake/examples_test/CMakeLists.txt
install/test/cmake/fetch_content_test/CMakeLists.txt
install/test/cmake/package_test/CMakeLists.txt
install/test/cmake/usage_tests/missing_components/CMakeLists.txt
install/test/cmake/usage_tests/no_components/CMakeLists.txt
install/test/cmake/usage_tests/unsorted_components/CMakeLists.txt
install/test/cmake/usage_tests/unsupported_components/CMakeLists.txt

Fixes #3598 
- upgrade cmake min version from 3.14 to 3.16
- test against 3.16 in CI

[CMAKE] upgrade cmake minimum version to 3.16

---

.github/workflows/cmake_install.yml
cmake/opentracing-cpp.cmake

Fixes #3648 
CMake 4.x removed compatibility with versions older than 3.5. 
https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
OpenTracing is no longer being updated and sets the minimum CMake version required to 3.1. This creates a CMake configure error when using CMake 4.x. 
Older versions of many dependencies depend on minimum versions of CMake < 3.5 (those in the `install/cmake/third_party_<minimum,stable>` and `install/conan/conanfile_stable.txt`). 
- Set `CMAKE_POLICY_VERSION_MINIMUM=3.5` when building opentracing-cpp from source using FetchContent
- Install CMake 3.31 in the MacOS CMake install test with `conanfile_stable.txt` dependency versions. 

[CMAKE] Fix CMake 4.x build error on MacOS runner and when building opentracing 

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
sdk/src/metrics/state/temporal_metric_storage.cc
sdk/test/metrics/attributes_hashmap_test.cc

This pull request makes a consistent naming correction across the codebase, changing the method name `GetAllEnteries` to the correct spelling `GetAllEntries`. This update affects the implementation, usage in metric storage logic, and related unit tests.

[SDK] Fix typo in hashmap method GetEnteries
