open-telemetry/opentelemetry-cpp

api/test/nostd/CMakeLists.txt
api/test/trace/CMakeLists.txt

A suggestion to reduce copy/paste efforts when maintaining the CMake files.

Add CMake tests from a test list

---

docs/abi-policy.md
docs/library-distribution.md

Several minor fixes for typos that sneaked in during: https://github.com/open-telemetry/opentelemetry-cpp/pull/38

Minor typos/fixes from previous PR

---

api/include/opentelemetry/nostd/function_ref.h
api/test/nostd/BUILD
api/test/nostd/CMakeLists.txt
api/test/nostd/function_ref_test.cc

Add a non-owning function reference.
See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0792r0.html for background.
Used in #60

Add function_ref

---

README.md

I haven't been able to contribute to this SIG. Please remove me.
Will be glad to return if I get a chance to work on C++ in the future. :-)

Remove Tigran Najaryan from Approvers list

---

docs/cpp-metrics-api-design.md
docs/cpp-metrics-sdk-design.md
docs/cpp-ostream-exporter-design.md

This PR adds design documents for the Metrics API and SDK to the docs folder.

Add Metrics Design Documents

---

sdk/include/opentelemetry/sdk/metrics/controller.h

This PR fixes a thread-safety issue introduced in the controller class (PR #231) by replacing atomic loads  and sets with atomic exchanges.

Controller Thread-Safety Fix

---

exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
ext/test/zpages/threadsafe_span_data_test.cc
sdk/include/opentelemetry/sdk/trace/attribute_utils.h
sdk/test/trace/CMakeLists.txt
sdk/test/trace/attribute_utils_test.cc
sdk/test/trace/span_data_test.cc
sdk/test/trace/tracer_test.cc

Add int32_t support for SpanData attributes

---

README.md

We've discussed this during the early Nov. SIG meeting. Now I'm getting back to it and sorry for the delay.

Clarify that supporting plain old C is not the current goal

---

README.md

Fix for an inconsistency in README.md :)

README: move and add links to community documentation

---

examples/metrics_simple/README.md

The links are broken, I think these are the correct ones, but I could be wrong.

doc: fix some broken links

---

CONTRIBUTING.md

According to our policy, only maintainers are permitted to merge PRs.

Correct the doc about that approver is not expected to merge PR

---

bazel/repository.bzl

Use opentelemetry-proto from released versions

---

README.md

A few minor cleanup on README.md

Minor cleanup on project README.md

---

.github/workflows/ci.yml
Versioning.md
api/include/opentelemetry/common/spin_lock_mutex.h
api/include/opentelemetry/metrics/instrument.h
api/include/opentelemetry/trace/span.h
api/include/opentelemetry/trace/trace_state.h
api/test/common/spinlock_benchmark.cc
ci/ports/protobuf/portfile.cmake
docs/cpp-metrics-api-design.md
examples/metrics_simple/README.md
exporters/elasticsearch/src/es_log_exporter.cc
exporters/otlp/src/otlp_exporter.cc
ext/include/opentelemetry/ext/zpages/zpages_http_server.h
ext/src/zpages/tracez_data_aggregator.cc
ext/test/zpages/tracez_data_aggregator_test.cc
sdk/include/opentelemetry/sdk/logs/logger.h
sdk/include/opentelemetry/sdk/metrics/aggregator/aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/counter_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/histogram_aggregator.h
sdk/include/opentelemetry/sdk/metrics/aggregator/sketch_aggregator.h
sdk/test/metrics/ungrouped_processor_test.cc
sdk/test/trace/trace_id_ratio_sampler_test.cc

Trying to capture the obvious spelling mistakes before merge.

Add spell check to CI

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/ci.yml
CONTRIBUTING.md
README.md
RELEASING.md
examples/otlp/README.md
examples/simple/README.md
exporters/otlp/README.md
ext/src/zpages/README.md

Following the process https://docs.google.com/document/d/1lkA0Re3vWfqXmuYLhL93Y6ABR27Sg6DzPcwi4kPXj0Y/edit.

Move from master to main (step1)

---

examples/batch/main.cc
sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
sdk/src/trace/batch_span_processor.cc
sdk/test/trace/batch_span_processor_test.cc

Fixes https://github.com/open-telemetry/opentelemetry-cpp/issues/497

Add options to construct BatchSpanProcessor

---

README.md

Was looking at the readme file and noticed the nits, trying to fix them.

Fix inconsistent spacing in the doc

---

README.md

Other language SIGs have been following this tradition, which I think is a good practice.

Include contributors in the README

---

CHANGELOG.md
api/docs/Doxyfile
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/src/version/version.cc

Release 0.3.0
New alpha release 0.3.0

Release for 0.3.0

---

api/include/opentelemetry/trace/propagation/detail/context.h
api/include/opentelemetry/trace/propagation/detail/hex.h
api/include/opentelemetry/trace/propagation/detail/string.h

API: add missing inline specifiers

---

exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h

Similar to #698, replacing std::getenv by getenv_s to stop the warning emitted by MSVC.

Remove std::getenv in Zipkin test as reported by MSVC

---

CHANGELOG.md
api/docs/Doxyfile
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/src/version/version.cc

Release 0.6.0
Changes
New alpha release 0.6.0

Release for 0.6.0 

---

api/include/opentelemetry/trace/propagation/http_trace_context.h

Minor update to comment of `HttpTraceContext` to keep update to date with #715.

Update code example in comment of HttpTraceContext

---

exporters/zipkin/BUILD
exporters/zipkin/src/zipkin_exporter.cc
exporters/zipkin/test/zipkin_recordable_test.cc

Bazel build for zipkin. Also removed some code warnings during bazel build.

Bazel build for Zipkin

---

exporters/jaeger/src/udp_transport.cc

Fixes regression introduced by https://github.com/open-telemetry/opentelemetry-cpp/pull/877.

Fix reference to error code in Jaeger logging

---

api/include/opentelemetry/trace/trace_state.h

Bugfix: regex is neither working on GCC 4.9.x

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Prepare for releasing 1.1.0

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

As we discussed in the last community meeting, we'll do a patch release this month.

Prepare for patch release v1.1.1

---

CHANGELOG.md
Versioning.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Prepare for 1.2.0 release

---

sdk/CMakeLists.txt

Fixes #1272 (issue)
installs `sdk_config.h`.

install sdk config header

---

.github/workflows/ci.yml

Fixes #1308 
Add `async-changes` branch to pull_request of github action. We can remove it when this branch is ready.

Add `async-changes` branch to pull_request of github action

---

ext/CMakeLists.txt
ext/src/http/client/nosend/CMakeLists.txt
ext/src/zpages/CMakeLists.txt

Fixes #1335 
+ Link `opentelemetry_ext` with `opentelemetry_api`

Link `opentelemetry_ext` with `opentelemetry_api`

---

api/include/opentelemetry/context/propagation/composite_propagator.h

Added a missing include guard to a public header

Add missing include guard

---

exporters/otlp/CMakeLists.txt

export opentelemetry_otlp_recordable

---

api/include/opentelemetry/trace/propagation/http_trace_context.h
api/test/trace/propagation/http_text_format_test.cc

Fixes #1366
- Fixed Tracestate propagation tests
- Fixed empty Tracestate header propagation

Fix empty tracestate header propagation

---

examples/common/logs_foo_library/foo_library.cc

Log current timestamp instead of epoch time

---

.github/workflows/stale.yml

Don't close inactive issues by the stable bot

---

sdk/include/opentelemetry/sdk/metrics/meter.h
sdk/src/metrics/meter.cc
sdk/src/metrics/state/sync_metric_storage.cc

Fixes some compiler warnings.
Fixes unused success result and unused variable declaration.

fix compiler warnings

---

exporters/prometheus/test/CMakeLists.txt

Add resources to dep list of Prometheus exporter test

---

buildscripts/pre-commit

Fixes the format of generated file by precommit script, to avoid format the auto generated files manually.

Fix format in precommit script

---

README.md

Update metrics status to Release Candidate

---

CHANGELOG.md
bazel/repository.bzl
cmake/opentelemetry-proto.cmake
third_party_release

Fixes # N/A
Upgrade otlp-proto

Upgrade opentelemetry-proto to v0.19.0

---

CHANGELOG.md

Fix some typo in CHANGELOG

---

examples/otlp/BUILD
examples/otlp/grpc_metric_main.cc

Add otlp-grpc example bazel

---

CHANGELOG.md
api/include/opentelemetry/version.h
docs/public/conf.py
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Prepare v1.8.1 release

---

examples/jaeger/main.cc
examples/metrics_simple/metrics_ostream.cc
examples/multi_processor/main.cc
examples/otlp/grpc_main.cc
examples/otlp/grpc_metric_main.cc
examples/otlp/http_log_main.cc
examples/otlp/http_main.cc
examples/prometheus/main.cc
examples/zipkin/main.cc

Remove unused namespace alias for nostd

---

exporters/jaeger/CMakeLists.txt
exporters/zipkin/CMakeLists.txt

Update copyright headers in zipkin and Jaeger exporters for consistency

---

buildscripts/pre-commit
sdk/include/opentelemetry/sdk/version/version.h
sdk/src/version/version.cc

Fixes potential name clash for the fix for #2012, as below below comment.
https://github.com/open-telemetry/opentelemetry-cpp/issues/2007#issuecomment-1453942779

Change SDK version global variable name to lowercase

---

api/include/opentelemetry/common/string_util.h

Checking indices before dereference in string utils

---

api/include/opentelemetry/trace/semantic_conventions.h
buildscripts/semantic-convention/generate.sh
examples/grpc/client.cc
sdk/include/opentelemetry/sdk/resource/semantic_conventions.h

Fixes #2366
Upgrade semantic conventions.

[SEMANTIC CONVENTION] Upgrade to semconv 1.22.0

---

third_party_release

The vcpkg submodule was updated, but the version recorded in third_party_release was missed to update.

Updated the recorded vcpkg submodule version

---

README.md

[DOC] Fix calendar link

---

docs/public/performance/benchmarks.rst

[DOC] Fix typo in benchmarks.rst

---

exporters/otlp/src/otlp_grpc_client.cc

[BUILD] Incorrect test on ENABLE_OTLP_GRPC_SSL_MTLS_PREVIEW

---

third_party_release

Update submodule vcpkg to the latest release.

[BUILD] update vcpkg submodule to 2024.02.14

---

bazel/repository.bzl
third_party_release

Upgrade to benchmark 1.8.3

---

bazel/repository.bzl
exporters/prometheus/CMakeLists.txt
third_party_release

Upgrade to prometheus 1.2.4

---

api/include/opentelemetry/metrics/meter.h

[doc] Fix typo: Asynchronouse -> Asynchronous in meter.h

---

CHANGELOG.md
bazel/repository.bzl

Fixes #2613
* Upgrade to opentelemetry-proto 1.2.0

[PROTO] Upgrade to opentelemetry-proto 1.2.0

---

MODULE.bazel

Update bzlmod version

---

README.md

* Add FOSSA badges in README.md

[ADMIN] Add FOSSA badges

---

.github/workflows/ci.yml
ci/do_ci.ps1
exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
exporters/etw/test/etw_perf_test.cc
exporters/etw/test/etw_tracer_test.cc

Fixes #3283 
+ Fix tracer implementation in ETW exporter with abiv2

[BUILD] Fix compiling problems with abiv2 and MSVC

---

sdk/include/opentelemetry/sdk/metrics/meter_config.h
sdk/include/opentelemetry/sdk/trace/tracer_config.h
sdk/src/metrics/meter_config.cc
sdk/src/trace/tracer_config.cc

[SDK] Use OPENTELEMETRY_EXPORT and static local variables

---

README.md

Add Doug Barker (@dbarker) to approvers
Per https://github.com/open-telemetry/opentelemetry-cpp/pull/3220#issuecomment-2749393716

[ADMIN] Add Doug Barker to approvers

---

.github/workflows/benchmark.yml
.github/workflows/clang-tidy.yaml
.github/workflows/iwyu.yml

Follow up after PR #3338 
Part of https://github.com/open-telemetry/sig-security/issues/87
* Fix remaining github actions.

[StepSecurity] Harden GibHub Actions, part 2

---

api/include/opentelemetry/semconv/incubating/app_attributes.h
api/include/opentelemetry/semconv/incubating/code_attributes.h
api/include/opentelemetry/semconv/incubating/cpython_attributes.h
api/include/opentelemetry/semconv/incubating/cpython_metrics.h
api/include/opentelemetry/semconv/incubating/db_attributes.h
api/include/opentelemetry/semconv/incubating/device_attributes.h
api/include/opentelemetry/semconv/incubating/error_attributes.h
api/include/opentelemetry/semconv/incubating/feature_flag_attributes.h
api/include/opentelemetry/semconv/incubating/gcp_attributes.h
api/include/opentelemetry/semconv/incubating/otel_attributes.h
api/include/opentelemetry/semconv/incubating/otel_metrics.h
api/include/opentelemetry/semconv/incubating/profile_attributes.h
api/include/opentelemetry/semconv/incubating/vcs_attributes.h
api/include/opentelemetry/semconv/schema_url.h
buildscripts/semantic-convention/generate.sh

[SEMANTIC CONVENTIONS] Upgrade semantic conventions to 1.32.0

---

.github/workflows/benchmark.yml

Fixes #3350  (issue)
uses latest commit for download and upload actions. this was needed as the versions used in the CI were from 2019 and since then there was no releases for the actions.
tested [here](https://github.com/esigo/opentelemetry-cpp/actions/runs/14541521419/job/40800302713).

[CI] fix artifacts download/upload

---

.devcontainer/Dockerfile.conan
.devcontainer/Dockerfile.dev
.github/workflows/ci.yml
.github/workflows/cmake_install.yml
docker/ubuntuLatest/Dockerfile
functional/otlp/Dockerfile

as reported - https://github.com/open-telemetry/opentelemetry-cpp/security/code-scanning

Harden Github actions - pinned-dependencies (part -1)

---

CHANGELOG.md
ext/src/CMakeLists.txt
ext/src/dll/CMakeLists.txt

[BUILD] Error out when building DLL without MSVC

---

exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_builder.h
exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter_options.h
exporters/zipkin/src/zipkin_builder.cc

This is a partial fix, to implement the zipkin exporter builder.
* Add a new option constructor, that ignores environment variables
* Implement the zipkin exporter builder

[CONFIGURATION] File configuration - zipkin exporter builder

---

CHANGELOG.md
sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
sdk/test/metrics/attributes_hashmap_test.cc

[METRICS SDK] Fix copying overflow attributes in attribute hashmap

---

install/conan/conanfile_latest.txt
install/conan/conanfile_stable.txt

- add the conan recipe for `rapidyaml/0.9.0` to the conan files for install testing 

[TEST] add ryml to the conan files for install tests
